filecoin-project/builtin-actors

bundle/bundler/src/lib.rs, bundle/src/lib.rs
=> bundle: fix path of embedded CAR.

.github/actions/rust-sccache/action.yml, .github/workflows/ci.yml
=> ci: publish bundle as a build artifact.

actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/runtime/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml, bundle/Cargo.toml, bundle/bundler/Cargo.toml, bundle/bundler/src/lib.rs
Now that https://github.com/filecoin-project/ref-fvm/pull/351 is merged.
=> Cargo.toml: point to master branch of ref-fvm.

.github/workflows/ci.yml
seems broken and it cancels the other workflows.
=> remove package workflow

actors/multisig/Cargo.toml, actors/multisig/tests/multisig_actor_test.rs
Introduce multisig testing package and write the very first test.
=> Hello rust, hello rust actors, hello firt msig builtin actors test

actors/miner/tests/miner_actor_test_construction.rs, actors/miner/tests/miner_actor_test_peer_info.rs, actors/miner/tests/util.rs, actors/runtime/src/test_utils.rs
On top of #42; should merge that first.
=> miner actor: peer info tests

actors/miner/tests/miner_actor_test_ctl_addrs.rs, actors/miner/tests/util.rs
single test pr this time, I didn't want to conflate with the wdpost tests I'll be working on next (will be on top).
=> miner actor: add control_addresses test

Cargo.lock, README.md, actors/miner/src/deadline_state.rs, actors/miner/src/lib.rs, actors/miner/src/state.rs, actors/miner/src/types.rs, actors/runtime/src/runtime/actor_blockstore.rs, actors/runtime/src/runtime/actor_code.rs, actors/runtime/src/runtime/fvm.rs, actors/runtime/src/runtime/mod.rs, actors/runtime/src/runtime/policy.rs, actors/runtime/src/test_utils.rs, build.rs
Part of https://github.com/filecoin-project/ref-fvm/pull/360.
Closes https://github.com/filecoin-project/builtin-actors/pull/50.
=> Switch to nv15

actors/miner/src/deadline_state.rs, actors/miner/src/partition_state.rs, actors/runtime/src/runtime/fvm.rs, build.rs
(because warnings are annoying)
=> chore: fix some clippy lints

Cargo.lock, Cargo.toml, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/runtime/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml, bundler/Cargo.toml
=> chore: update FVM and switch to released versions

Cargo.lock, actors/runtime/Cargo.toml, actors/runtime/src/test_utils.rs, build.rs, bundler/Cargo.toml, bundler/src/bin/bundler.rs, bundler/src/lib.rs
See https://github.com/filecoin-project/ref-fvm/pull/382
=> fix: remove multihash::Code::Identity

Cargo.lock, Cargo.toml, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/runtime/Cargo.toml, actors/runtime/src/builtin/sector.rs, actors/runtime/src/runtime/policy.rs, actors/system/Cargo.toml, actors/verifreg/Cargo.toml, actors/verifreg/src/types.rs
And add configs for caterpillernet and devnet.
To use, specify `default-features = false` and `features = ["caterpillernet"]`.
=> feat: make policy configurable at compile time

Cargo.lock, actors/multisig/tests/multisig_actor_test.rs, actors/multisig/tests/util.rs, actors/runtime/src/test_utils.rs
Joint effort with @jennijuju who will likely take the non happy path test cases in a follow up later on.
=> Multisig Add signer scaffold

actors/multisig/tests/multisig_actor_test.rs, actors/multisig/tests/util.rs
Approve and ApproveOK added to msig harness
Simple approve test
=> Multisig approval testing

actors/multisig/tests/multisig_actor_test.rs, actors/multisig/tests/util.rs
1. Harness function for each multisig method
2. Happy path test exercising each method
=> Cancel, SwapSigner and RemoveSigner multisig tests

actors/system/src/lib.rs
This is a bit strained since we'll never run this code, but for completeness. #32
=> System actor test

actors/verifreg/tests/harness/mod.rs, actors/verifreg/tests/verifreg_actor_test.rs
This finishes off the verifreg tests #33
=> Verified registry tests for consuming and restoring datacap

actors/multisig/tests/multisig_actor_test.rs
Generalize and add remaining test cases for add signer.
=> More AddSigner test cases

actors/miner/src/lib.rs, actors/miner/tests/miner_actor_test_wpost.rs, actors/miner/tests/util.rs, actors/runtime/src/test_utils.rs
Note the error message discrepancy with the deadline in the "Deadline not open" test.
=> miner actor: window post tests: invalid submissions

.github/workflows/ci.yml, actors/miner/src/lib.rs, actors/miner/tests/miner_actor_test_wpost.rs, actors/miner/tests/util.rs, actors/multisig/tests/multisig_actor_test.rs, actors/multisig/tests/util.rs, actors/power/tests/harness/mod.rs, actors/runtime/src/test_utils.rs, actors/verifreg/src/types.rs, actors/verifreg/tests/harness/mod.rs, actors/verifreg/tests/verifreg_actor_test.rs
=> deny warnings to keep things clean

actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/runtime/Cargo.toml, actors/system/Cargo.toml, actors/system/src/lib.rs, actors/verifreg/Cargo.toml, bundler/Cargo.toml, bundler/src/lib.rs
for #122
Depends on https://github.com/filecoin-project/ref-fvm/pull/401 which needs to be merged and published first, for the From type to string converter.
=> Builtin actor registry

actors/miner/tests/miner_actor_test_wpost.rs, bundler/src/lib.rs
I noticed that master is failing with a clippy check when submitting another PR.  This PR attempts to fix the issue.
=> Fix clippy failures on master

actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/runtime/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml, bundler/Cargo.toml, bundler/src/lib.rs
Cherrypicks and backports the new bundler from #132
=> Backport  manifest v1 bundler to release/v7

Cargo.toml, actors/runtime/src/test_utils.rs, test_vm/Cargo.toml, test_vm/src/lib.rs, test_vm/tests/test_vm_test.rs
Resolves first check box for #40
=> Rust Ref VM for integration tests

.github/workflows/ci.yml, .gitignore, Makefile, build-bundle.sh
=> Fix build asset publishing

Cargo.lock, Cargo.toml, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/runtime/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml
=> chore: release 7.1.3

.github/workflows/ci.yml, .github/workflows/release.yml, scripts/publish-release.sh
master, release/*, and experimental/* are the blessed ones
=> add workflow to publish release bundles on certain branches

.github/workflows/ci.yml, .github/workflows/release.yml, scripts/publish-release.sh
for pushes to certain branches: `master`, `release/*`, and `experimental/*`
=> add workflow to publish release bundles

.github/workflows/ci.yml, .github/workflows/release.yml, Cargo.toml, actors/runtime/build.rs, build.rs
Accepts `testing` as a fil network and configures appropriate features.
=> add testing policy configuration & bundle

scripts/publish-release.sh
tested targeting `experimental/test`; see https://github.com/filecoin-project/builtin-actors/releases/tag/37ad94effadab2c6
=> publish bundle hashes as part of the release

actors/market/src/lib.rs, actors/market/src/policy.rs, actors/market/src/state.rs, actors/runtime/Cargo.toml, actors/runtime/build.rs, actors/runtime/src/runtime/policy.rs, actors/verifreg/src/lib.rs, actors/verifreg/src/types.rs, actors/verifreg/tests/verifreg_actor_test.rs
So that we have everything in one place and properly pass features at build.
=> consolidate verifreg and market policy constants into runtime policy

actors/account/src/lib.rs, actors/cron/src/lib.rs, actors/init/src/lib.rs, actors/market/src/lib.rs, actors/miner/src/lib.rs, actors/multisig/src/lib.rs, actors/paych/src/lib.rs, actors/power/src/lib.rs, actors/reward/src/lib.rs, actors/runtime/Cargo.toml, actors/system/src/lib.rs, actors/verifreg/src/lib.rs
Unfortunately, we haven't backported the CI fixes, so CI doesn't run for external contributors on this branch...
=> fix v7 runtime build

actors/market/tests/market_actor_test.rs
=> Market actor unit tests (part 13)

actors/market/src/lib.rs, actors/market/tests/market_actor_test.rs
=> Market actor unit tests (part 14)

actors/power/tests/power_actor_tests.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/power/power_test.go#L80) and [there](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/power/power_test.go#L131).
* claimed_power_given_caller_is_not_storage_miner_should_fail
* create_miner_given_caller_is_not_of_signable_type_should_fail
* create_miner_given_send_to_init_actor_fails_should_fail
* claimed_power_given_claim_does_not_exist_should_fail
=> power actor tests part 1 & 2

actors/miner/tests/miner_actor_test_wpost.rs, actors/miner/tests/util.rs
Note the discrepancy with the vesting schedule in the recoveries test.
=> miner actor: remaining wpost tests

actors/power/tests/harness/mod.rs, actors/power/tests/power_actor_tests.rs
=> Power actor unit tests (part 4)

actors/power/tests/power_actor_tests.rs
=> Power actor unit tests (part 6)

actors/power/tests/harness/mod.rs, actors/power/tests/power_actor_tests.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/power/power_test.go#L541).
* `call_reward_actor`
* `amount_sent_to_reward_actor_and_state_change`
* `event_scheduled_in_null_round_called_next_round`
=> Power actor tests part 8

actors/multisig/tests/multisig_actor_test.rs
=> Finish multisig constructor tests

actors/market/tests/market_actor_test.rs
=> Market Actor Tests (part 10)

actors/market/tests/market_actor_test.rs
=> Market Actor Tests (part 9)

actors/multisig/tests/multisig_actor_test.rs
=> Multisig Propose Unit tests

Cargo.lock, Cargo.toml, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/runtime/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml
Updates the CBOR encoding library.
=> chore: release 7.3.0

Cargo.lock, Cargo.toml, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/runtime/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml
Updates cbor encoding for cbor4ii.
=> chore: release v6.3.0

actors/multisig/tests/multisig_actor_test.rs
=> Multisig Approve unit tests

actors/multisig/tests/multisig_actor_test.rs
=> Multisig cancel unit tests

actors/market/tests/harness.rs
https://github.com/filecoin-project/builtin-actors/pull/319/files#r865099343
=> refactor publish_deals_expect_abort

actors/market/tests/cron_tick_timedout_deals.rs, actors/market/tests/harness.rs
=> Implement 3 CronTickTimedoutDeals tests.

actors/multisig/tests/multisig_actor_test.rs, actors/multisig/tests/util.rs, actors/runtime/tests/multimap_test.rs
=> Multisig Unit tests for remove and swap signer 

actors/miner/tests/expiration_queue.rs
=> Miner tests (part 11)

actors/miner/src/deadline_state.rs, actors/miner/tests/deadline_assignment.rs
=> Miner unit test (part 1)

actors/miner/src/deadline_info.rs, actors/miner/tests/deadline_helper.rs
=> Miner unit test (part 3)

actors/miner/src/deadline_info.rs, actors/miner/tests/deadlines.rs
=> Miner tests (part 10)

actors/miner/src/partition_state.rs, actors/miner/tests/deadline_state_test.rs, actors/miner/tests/util.rs, actors/runtime/src/test_utils.rs
The first batch of miner deadline invariants checks. More to come but I'm a fan of merging often and relatively small PRs.
=> Miner deadline invariants check part 1

actors/miner/tests/deadline_state_test.rs, actors/miner/tests/util.rs
The second batch of miner deadline invariants checks. Found some fiascoes in the tests I've written before those checks, it should be good now.
=> miner deadline invariants check part 2

actors/miner/src/state.rs, actors/miner/src/types.rs, actors/miner/tests/precommitted_sector_stores.rs, actors/miner/tests/state_harness.rs, actors/miner/tests/util.rs
=> Miner tests (part 18)

Cargo.lock, Cargo.toml, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/runtime/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml
=> chore: release 7.4.0

Makefile
=> make rules for building all network-specific bundles

actors/miner/src/partition_state.rs
@ZenGround0 backporting the fix from [here](https://github.com/filecoin-project/builtin-actors/pull/367#discussion_r874930997)
=> backport retracting recoveries fix

Cargo.lock, actors/power/Cargo.toml, actors/power/tests/harness/mod.rs, actors/power/tests/power_actor_tests.rs
=> Power actor unit tests part 14

actors/miner/src/deadline_state.rs
@ZenGround0 backporting the fix from [here](https://github.com/filecoin-project/builtin-actors/pull/362)
=> backport remove partitions count fix

actors/market/tests/market_actor_test.rs
Implemented missing test from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/market/market_test.go#L46)
=> market test remove all error

actors/miner/tests/declare_faults.rs, actors/miner/tests/util.rs
=> Miner Actor Tests (Part 29)

actors/miner/tests/terminate_sectors_test.rs, actors/miner/tests/util.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/miner/miner_test.go#L2114)
* `removes_sector_with_correct_accounting`
* `cannot_terminate_a_sector_when_the_challenge_window_is_open`
=> miner actor tests p32

Cargo.lock, Cargo.toml, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/runtime/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml
Sorry, but I ended up pushing commits to upgrade upstream deps directly to the `release/v7` branch. Oops!
=> release v7.5.0.

actors/miner/tests/check_sector_proven_test.rs, actors/miner/tests/util.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/miner/miner_test.go#L2560)
* `successfully_check_sector_is_proven`
* `fails_if_sector_is_not_found`
=> miner test part 37

actors/miner/tests/deadline_cron.rs, actors/miner/tests/util.rs, actors/runtime/src/test_utils.rs
This PR also allows the hash function to be overwritten for testing.
=> Miner tests (part 27)

actors/miner/tests/util.rs, actors/miner/tests/withdraw_balance.rs
=> Miner tests (part 33)

actors/miner/tests/repay_debts.rs, actors/miner/tests/util.rs
=> Miner tests (part 34)

actors/miner/tests/miner_actor_test_bitfield_queue.rs, actors/miner/tests/precommit_expiry.rs, actors/miner/tests/state_harness.rs, actors/miner/tests/util.rs
=> Add AddPreCommitExpiry tests

actors/miner/src/lib.rs
I _think_ this is correct (and seems to build), but @Stebalien please advise.
=> Miner: PRU: Fix init of new_sectors

Cargo.lock, Cargo.toml, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/runtime/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml
Updates FVM for RC2 changes. Importantly, fixes a bug in the block read logic.
=> Release v7.5.1

actors/market/src/lib.rs, actors/market/tests/market_actor_test.rs
Transports https://github.com/filecoin-project/specs-actors/pull/1589, thanks to @IversonHan for the fix!
=> fix: market: PSD: handle collateral tracking correctly

Cargo.lock, actors/miner/tests/deadline_cron.rs, actors/miner/tests/declare_recoveries.rs, actors/miner/tests/miner_actor_test_wpost.rs, actors/miner/tests/util.rs
Ran into issues rebasing onto main in PR #396 so creating a new PR to clean up the history.
=> Miner Tests (Part 30) v2

Cargo.lock, actors/multisig/src/types.rs, test_vm/Cargo.toml, test_vm/src/lib.rs, test_vm/tests/multisig_test.rs
=> Test self remove

Cargo.lock, actors/market/Cargo.toml, actors/market/src/balance_table.rs, actors/market/tests/harness.rs, actors/market/tests/market_actor_test.rs, actors/market/tests/on_miner_sectors_terminate.rs, actors/runtime/src/test_utils.rs, actors/runtime/src/util/set_multimap.rs
Implemented invariants checks from [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/market/market_test.go#L3298), also added some missing checks and fixed broken tests.
=> market actor invariants check

actors/miner/src/vesting_state.rs, actors/miner/tests/apply_rewards.rs, actors/miner/tests/change_owner_address_test.rs, actors/miner/tests/change_peer_id_test.rs, actors/miner/tests/change_worker_address_test.rs, actors/miner/tests/check_sector_proven_test.rs, actors/miner/tests/compact_partitions_test.rs, actors/miner/tests/compact_sector_numbers_tests.rs, actors/miner/tests/confirm_update_worker_key_test.rs, actors/miner/tests/deadline_cron.rs, actors/miner/tests/deadline_cron_defers_stops_restarts.rs, actors/miner/tests/declare_faults.rs, actors/miner/tests/declare_recoveries.rs, actors/miner/tests/extend_sector_expiration_test.rs, actors/miner/tests/miner_actor_test_commitment.rs, actors/miner/tests/miner_actor_test_construction.rs, actors/miner/tests/miner_actor_test_ctl_addrs.rs, actors/miner/tests/miner_actor_test_peer_info.rs, actors/miner/tests/miner_actor_test_wpost.rs, actors/miner/tests/prove_commit.rs, actors/miner/tests/repay_debts.rs, actors/miner/tests/terminate_sectors_test.rs, actors/miner/tests/util.rs, actors/miner/tests/withdraw_balance.rs, actors/runtime/src/test_utils.rs
From [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/testing.go#L29)
=> Miner test invariant state check

test_vm/tests/multisig_test.rs
=> Swap tests

actors/power/src/lib.rs, actors/power/src/testing.rs, actors/power/tests/harness/mod.rs, actors/power/tests/power_actor_tests.rs
https://github.com/filecoin-project/builtin-actors/pull/436 needs to be reviewed & merged first, I cherry-picked it for now.
Implemented power actor invariants check from [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/power/testing.go) and added missing state checks.
=> Power actor invariants check

actors/cron/src/lib.rs, actors/cron/src/testing.rs, actors/cron/tests/cron_actor_test.rs
Implemented invariant checks from [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/cron/testing.go)
=> cron actor invariant checks

actors/paych/src/lib.rs, actors/paych/src/testing.rs, actors/paych/tests/paych_actor_test.rs
Implemented checks from [here](https://github.com/filecoin-project/builtin-actors/blob/paych-invariant-checks/actors/paych/src/testing.rs).
=> paych invariant checks

actors/multisig/src/lib.rs, actors/multisig/src/testing.rs, actors/multisig/src/types.rs, actors/multisig/tests/multisig_actor_test.rs
Implemented checks from [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/multisig/testing.go).
=> multisig invariant checks

actors/verifreg/src/lib.rs, actors/verifreg/src/testing.rs, actors/verifreg/tests/harness/mod.rs, actors/verifreg/tests/verifreg_actor_test.rs
Implemented checks from [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/verifreg/testing.go)
=> verified registry invariant check

actors/miner/tests/miner_actor_test_wpost.rs
@lemmih fixed the hash function in #368 so the failure no longer occurs
=> Last wpost test -- successful recoveries recover power

test_vm/src/lib.rs, test_vm/src/util.rs, test_vm/tests/publish_deals_test.rs
=> Publish Deals Integration Test

actors/miner/src/types.rs, test_vm/tests/commit_post_test.rs
=> Add commit_post tests

test_vm/src/lib.rs, test_vm/tests/commit_post_test.rs
Adds the remaining commit_post tests, except for TestBatchOnboarding, which @tyshko5 has claimed.
Towards #75
=> Add more commit_post tests

actors/miner/src/lib.rs, actors/miner/tests/report_consensus_fault.rs, actors/miner/tests/util.rs
=> Miner tests (part 42)

actors/miner/src/types.rs, test_vm/src/util.rs, test_vm/tests/extend_sectors_test.rs
=> Add extend_sectors_test

Cargo.lock, Cargo.toml, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/miner/src/lib.rs, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/runtime/Cargo.toml, actors/state/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml, test_vm/Cargo.toml
=> release: v8.0.0-rc.1

actors/miner/src/types.rs, test_vm/src/lib.rs, test_vm/src/util.rs, test_vm/tests/replica_update_test.rs
=> Add replica_update test

Cargo.lock, Cargo.toml, Makefile, README.md, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml, test_vm/Cargo.toml
These two patches make `make publish` actually work.
=> Cargo & Publishing Cleanup

.github/workflows/ci.yml, Cargo.toml, actors/market/src/lib.rs, actors/market/src/types.rs, actors/market/tests/harness.rs, actors/market/tests/verify_deals_for_activation_test.rs, actors/miner/Cargo.toml, actors/miner/src/commd.rs, actors/miner/src/ext.rs, actors/miner/src/lib.rs, actors/miner/src/policy.rs, actors/miner/src/types.rs, actors/miner/tests/aggregate_prove_commit.rs, actors/miner/tests/batch_method_network_fees_test.rs, actors/miner/tests/extend_sector_expiration_test.rs, actors/miner/tests/miner_actor_test_commitment.rs, actors/miner/tests/miner_actor_test_precommit_batch.rs, actors/miner/tests/precommitted_sector_stores.rs, actors/miner/tests/prove_commit.rs, actors/miner/tests/util.rs, runtime/src/test_utils.rs, test_vm/src/lib.rs, test_vm/src/util.rs, test_vm/tests/commit_post_test.rs, test_vm/tests/extend_sectors_test.rs, test_vm/tests/publish_deals_test.rs, test_vm/tests/replica_update_test.rs
Trying this out rather than force pushing to leave a trail of what we're doing and to act as a model for what to do when the integration branch has commits that are not on master complicating the rebase.
=> chore -- merge master into fil+ integration branch

.github/workflows/ci.yml, .github/workflows/release.yml
=> ci: ensure that Cargo.lock is up-to-date

.github/workflows/ci.yml, Makefile
=> refine check-clippy with makefile

.github/workflows/ci.yml, Makefile
Resolves https://github.com/filecoin-project/builtin-actors/issues/556
=> move rustfmt CI job into makefile

actors/init/src/state.rs, actors/init/tests/init_actor_test.rs
Resolves https://github.com/filecoin-project/builtin-actors/issues/567
=> Introduce a check for unique Robust Address in the Init Actor

actors/evm/src/interpreter/opcode.rs
Cleaner code, order by opcode, and O(1) lookup for resolution (instead of linear scan); also removes the cost thingie, as part of https://github.com/filecoin-project/ref-fvm/issues/796
=> EVM: cleanup opcode definition and resolution

actors/evm/src/interpreter/execution.rs, actors/evm/src/interpreter/instructions/arithmetic.rs, actors/evm/src/interpreter/instructions/call.rs, actors/evm/src/interpreter/instructions/control.rs, actors/evm/src/interpreter/instructions/hash.rs, actors/evm/src/interpreter/instructions/memory.rs, actors/evm/src/interpreter/output.rs
No more linear scans with match, uses a trampoline with a dispatch table.
=> Fast interpreter

test_vm/src/lib.rs
Improves `extend_sector_with_deals` by 40%
=> Optimize test_vm get_actor

actors/cron/src/lib.rs, actors/init/src/lib.rs, actors/market/src/lib.rs, actors/miner/src/lib.rs, actors/multisig/src/lib.rs, actors/paych/src/lib.rs, actors/power/src/lib.rs, actors/reward/src/lib.rs, runtime/src/builtin/shared.rs, runtime/src/runtime/fvm.rs, runtime/src/runtime/mod.rs, runtime/src/test_utils.rs, runtime/src/util/chaos/mod.rs, test_vm/src/lib.rs
=> change address type to a reference

actors/evm/tests/asm.rs, actors/evm/tests/calc.rs
Adds some macros to simplify dispatch in asm contracts and avoids an extra stack copy.
=> Some housekeeping

actors/evm/src/interpreter/instructions/call.rs, actors/evm/src/interpreter/instructions/memory.rs, actors/evm/src/interpreter/output.rs, actors/evm/src/interpreter/precompiles.rs, actors/evm/src/interpreter/uints.rs, actors/evm/src/lib.rs, actors/evm/tests/call.rs, actors/evm/tests/precompile.rs
=> EVM: Implement CALL

actors/evm/src/interpreter/instructions/call.rs, actors/evm/src/interpreter/instructions/ext.rs, actors/evm/src/interpreter/instructions/memory.rs
=> copy memory tests

actors/init/tests/init_actor_test.rs, runtime/Cargo.toml
A bunch of test things is broken on next, probably as a result of a bad merge.
=> Next: fix broken tests

Cargo.lock, actors/datacap/Cargo.toml, actors/datacap/src/lib.rs, actors/verifreg/Cargo.toml
This provides the recipient's response data to the receiver hook back to the caller of Transfer[From].
=> Update token library

actors/evm/src/interpreter/address.rs, actors/evm/src/interpreter/instructions/call.rs, actors/evm/src/interpreter/instructions/context.rs, actors/evm/src/interpreter/instructions/ext.rs, actors/evm/src/interpreter/instructions/lifecycle.rs, actors/evm/tests/call.rs
closes https://github.com/filecoin-project/ref-fvm/issues/882
=> rename evm actor's `Address` to `EthAddress`

test_vm/src/lib.rs
Previously, we weren't taking the nonce into account which prevented us
from testing multiple messages from the same account.
=> test: correctly compute the f2 address in the test vm (#686)

Cargo.lock, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/embryo/Cargo.toml, actors/evm/Cargo.toml, actors/init/Cargo.toml, actors/init/src/lib.rs, actors/init/src/state.rs, actors/init/src/testing.rs, actors/init/src/types.rs, actors/init/tests/init_actor_test.rs, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml, runtime/Cargo.toml, runtime/src/builtin/singletons.rs, runtime/src/runtime/fvm.rs, state/Cargo.toml, test_vm/Cargo.toml, test_vm/src/lib.rs, test_vm/tests/init_test.rs, test_vm/tests/test_vm_test.rs
- Adds a create4 method to the init actor.
- Adds embryo actor creation to the test vm.
=> feat: basic f4 support

actors/init/src/lib.rs, actors/init/src/state.rs, actors/multisig/src/lib.rs, actors/multisig/src/state.rs, actors/multisig/tests/multisig_actor_test.rs, actors/paych/src/lib.rs, actors/paych/tests/paych_actor_test.rs, actors/system/src/lib.rs, actors/verifreg/src/lib.rs, actors/verifreg/tests/verifreg_actor_test.rs, runtime/src/actor_error.rs, runtime/src/builtin/shared.rs
Co-authored-by: dignifiedquire <me@dignifiedquire.com>
=> Traits and impls for adding context and exit codes to results. (#589)

actors/market/src/ext.rs, actors/market/src/lib.rs, actors/market/tests/harness.rs, actors/market/tests/market_actor_test.rs, actors/verifreg/src/lib.rs, actors/verifreg/src/state.rs, actors/verifreg/src/types.rs, actors/verifreg/tests/harness/mod.rs, actors/verifreg/tests/verifreg_actor_test.rs, runtime/src/util/batch_return.rs, test_vm/src/util.rs
=> Implement extension of claims by spending new datacap

actors/verifreg/src/expiration.rs, actors/verifreg/src/lib.rs, actors/verifreg/src/types.rs, actors/verifreg/tests/harness/mod.rs, actors/verifreg/tests/verifreg_actor_test.rs, runtime/src/util/batch_return.rs
=> Implement removal of expired claims.

actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml, runtime/src/lib.rs, runtime/src/runtime/hash_algorithm.rs, runtime/src/runtime/mod.rs, state/Cargo.toml
Fixes | https://github.com/filecoin-project/ref-fvm/issues/636
Hello @Stebalien,
Refactored the code based on comments & suggestion.
& PR is re-based to `master` branch.
As Replacement for - [PR711](https://github.com/filecoin-project/builtin-actors/pull/711)
=> Optimization for #636 | Perform HAMT SHA256 hashes natively via a syscall

Cargo.lock, actors/account/Cargo.toml, actors/account/src/lib.rs, actors/datacap/Cargo.toml, actors/datacap/src/lib.rs, actors/datacap/src/state.rs, actors/datacap/tests/harness/mod.rs, actors/market/Cargo.toml, actors/market/src/lib.rs, actors/market/tests/harness.rs, actors/market/tests/market_actor_test.rs, actors/multisig/Cargo.toml, actors/multisig/src/lib.rs, actors/verifreg/Cargo.toml, actors/verifreg/src/lib.rs, actors/verifreg/tests/harness/mod.rs, actors/verifreg/tests/verifreg_actor_test.rs, runtime/src/builtin/shared.rs, test_vm/Cargo.toml, test_vm/src/util.rs
Note: we will need to upgrade frc42_dispatch again after https://github.com/helix-onchain/filecoin/issues/111
=> Update token library to released crate

actors/miner/src/types.rs, actors/miner/tests/change_owner_address_test.rs, test_vm/src/lib.rs, test_vm/src/util.rs, test_vm/tests/change_beneficiary_test.rs, test_vm/tests/change_owner_test.rs, test_vm/tests/withdraw_balance_test.rs
close https://github.com/filecoin-project/builtin-actors/issues/548
=> test: add integration test for change beneficiary and withdraw balance

test_vm/src/util.rs, test_vm/tests/extend_sectors_test.rs, test_vm/tests/publish_deals_test.rs, test_vm/tests/replica_update_test.rs, test_vm/tests/terminate_test.rs, test_vm/tests/verified_claim_test.rs, test_vm/tests/verifreg_remove_datacap_test.rs
This is more or less good to merge as progress, but unfinished. I can't get any further until the miner claims the allocation (#715).
=> Partial integration test for verified claims

actors/miner/src/lib.rs, test_vm/src/lib.rs, test_vm/src/util.rs, test_vm/tests/extend_sectors_test.rs, test_vm/tests/verified_claim_test.rs
I think this more or less covers #530
=> Expand verified claim test to cover extension and dropping claims

test_vm/src/util.rs, test_vm/tests/verified_claim_test.rs
I think this covers off most of what we want for #530, but will leave the issue open for a little bit, especially in case @ZenGround0 has more ideas.
=> Integration test for expired allocation

actors/miner/tests/extend_sector_expiration_test.rs, actors/miner/tests/util.rs
=> Claim drop test

actors/miner/src/types.rs, actors/miner/tests/extend_sector_expiration_test.rs, actors/miner/tests/util.rs
Took some inspiration from @Kubuxu's work in #650 
Closes #744
=> Exercise extend2 with all old extend1 tests

actors/market/src/testing.rs, actors/miner/src/testing.rs, state/src/check.rs
=> Remaining FIP 45 state invariant checks 

Cargo.lock, build.rs, runtime/src/runtime/builtins.rs, runtime/src/test_utils.rs, state/src/check.rs, test_vm/Cargo.toml, test_vm/src/lib.rs, test_vm/tests/init_test.rs
- Add a new type.
- Add it to the bundle.
- Add it to the test VM.
=> fix: register the EAM

actors/eam/src/lib.rs, actors/eam/tests/create.rs
Part of https://github.com/filecoin-project/ref-fvm/issues/973.
=> feat: allow anyone to call EAM::create2

runtime/src/lib.rs, runtime/tests/mapmap_test.rs
=> MapMap test

actors/miner/src/lib.rs, actors/miner/tests/util.rs, test_vm/src/lib.rs
Cherry-picks https://github.com/filecoin-project/builtin-actors/pull/761 into `release/v9`
=> fix: Add runtime caller validation for change_beneficiary (#761)

Cargo.lock, Cargo.toml, Makefile, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/datacap/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml, runtime/Cargo.toml, state/Cargo.toml, test_vm/Cargo.toml
Seems to also fix https://github.com/filecoin-project/builtin-actors/issues/506
=> Bump version for release

Makefile
Closes https://github.com/filecoin-project/builtin-actors/issues/506
=> Fix: make bump-version and make set-version

actors/evm/src/interpreter/instructions/context.rs, actors/evm/tests/misc.rs, runtime/src/test_utils.rs
1. Fix the BLOCKHASH instruction.
2. Fix the limits (HEIGHT-1 to HEIGHT-257).
3. Test everything.
=> fix: blockhash takes a height, not an offset

actors/evm/src/interpreter/instructions/arithmetic.rs, actors/evm/src/interpreter/instructions/bitwise.rs, actors/evm/src/interpreter/instructions/boolean.rs, actors/evm/src/interpreter/uints.rs
And fix a bunch of them (or at least the exponentiation).
=> fix: refactor mathops

Cargo.lock, actors/evm/Cargo.toml, actors/evm/src/interpreter/execution.rs, actors/evm/src/interpreter/instructions/hash.rs
This should significantly speedup smart contracts.
=> feat: do sha3 hashing with the runtime

actors/evm/src/interpreter/instructions/log.rs
For a better testnet experience.
=> fix: implement logging as a no-op in production

actors/datacap/src/lib.rs, test_vm/tests/datacap_tests.rs
Backports https://github.com/filecoin-project/builtin-actors/pull/794 to `release/v9`
=> backport: datacap: fix Name and Symbol methods

actors/datacap/src/lib.rs
Backports https://github.com/filecoin-project/builtin-actors/pull/795
=> backport: datacap: add allowance to exported methods

test_vm/tests/datacap_tests.rs
Quick test to sanity-check #795
=> datacap: test invoking allowance

Cargo.lock, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/datacap/Cargo.toml, actors/eam/Cargo.toml, actors/embryo/Cargo.toml, actors/evm/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml, runtime/Cargo.toml, state/Cargo.toml, test_vm/Cargo.toml
My Cargo patches are failing to apply, and this is why.
=> upgrade fvm_shared@3.0.0-alpha.9, fvm_sdk@3.0.0-alpha.9.

.github/actions/rust-cargo-run/action.yml
=> chore: bump cache version

.github/workflows/ci.yml, .github/workflows/release.yml, Cargo.toml, Makefile, build.rs, runtime/build.rs
We will want to test the migration on that network.
=> v9: generate bundles for the Wallaby testnet.

Cargo.lock, actors/account/Cargo.toml, actors/cron/Cargo.toml, actors/datacap/Cargo.toml, actors/eam/Cargo.toml, actors/embryo/Cargo.toml, actors/evm/Cargo.toml, actors/init/Cargo.toml, actors/market/Cargo.toml, actors/miner/Cargo.toml, actors/multisig/Cargo.toml, actors/paych/Cargo.toml, actors/power/Cargo.toml, actors/reward/Cargo.toml, actors/system/Cargo.toml, actors/verifreg/Cargo.toml, runtime/Cargo.toml, state/Cargo.toml, test_vm/Cargo.toml
Includes refactored network/message context syscalls.
=> chore: update fvm sdk

actors/market/src/lib.rs, actors/market/tests/market_actor_test.rs
=> Market actor: Export PublishStorageDeals

actors/power/src/lib.rs, actors/power/src/types.rs, actors/power/tests/harness/mod.rs, actors/power/tests/power_actor_tests.rs
=> Power actor: Export methods to CreateMiner and get miner counts

actors/evm/src/interpreter/instructions/arithmetic.rs
issue https://github.com/filecoin-project/ref-fvm/issues/993
=> EVM: Unit tests for some math opcodes

actors/evm/src/interpreter/precompiles.rs, actors/miner/src/lib.rs
* fix call_actor precompile
* modify error message to include more information
=> fix call_actor precompile

actors/eam/src/lib.rs, actors/eam/tests/create.rs
And add some basic tests.
fixes #866
=> fix: correctly compute addresses in CREATE

actors/evm/src/interpreter/instructions/arithmetic.rs, actors/evm/src/interpreter/instructions/bitwise.rs
=> chore: cleanup instruction tests

actors/evm/src/interpreter/instructions/call.rs, actors/evm/src/interpreter/precompiles.rs, actors/evm/src/interpreter/system.rs, actors/evm/src/lib.rs, runtime/src/runtime/fvm.rs, runtime/src/runtime/mod.rs, runtime/src/test_utils.rs, test_vm/src/lib.rs
This PR correctly implements staticcall through the "readonly" mode.
fixes https://github.com/filecoin-project/ref-fvm/issues/1177
=> feat: correctly implement staticcall

actors/evm/src/interpreter/instructions/call.rs, actors/evm/src/interpreter/precompiles.rs, actors/evm/src/interpreter/system.rs, actors/evm/src/interpreter/uints.rs, runtime/src/runtime/fvm.rs, runtime/src/runtime/mod.rs, runtime/src/test_utils.rs, test_vm/src/lib.rs
Closes https://github.com/filecoin-project/ref-fvm/issues/1178
Note that I have some concerns about existing tooling hardcoding eth gas values here, but in general it is the right thing to do.
=> EVM: thread gas limit in send

actors/evm/src/interpreter/instructions/call.rs
Fixes https://github.com/filecoin-project/ref-fvm/issues/1180
=> EVM: thread gas go delegatecall

actors/evm/src/interpreter/execution.rs
1. Lift the "is none" check into the loop. This is actually _slower_ for short programs, but faster over the long-run. I measured that by moving the check _above_ the step operation and determining that it was slower.
2. Remove the unsafe and inline.
1. Inlining is faster overall (at least in terms of gas usage).
2. Inlining lets rust elide the bounds checks (no difference in gas usage).
3. Don't bother checking instructions. Instead, we just dispatch and let run the "undefined instruction" function on undefined instructions. It gives the same result, but saves some time.
Before: 2227772
After: 2210592
Slightly less than 1%... but I don't think the contract we're testing is complex enough to really make proper measurements.
=> feat: further optimize instruction dispatch

actors/evm/src/interpreter/instructions/lifecycle.rs
=> fix: allow creating empty contracts

actors/evm/src/interpreter/instructions/call.rs
Closes https://github.com/filecoin-project/ref-fvm/issues/980
=> EVM: value + magic gas limit 23k implies METHOD_SEND

actors/evm/src/interpreter/instructions/call.rs, actors/evm/src/interpreter/precompiles.rs, actors/evm/tests/call.rs, actors/evm/tests/precompile.rs
Closes https://github.com/filecoin-project/ref-fvm/issues/874
=> reserve gas for return on CALL

actors/evm/src/interpreter/precompiles/evm.rs, actors/evm/src/interpreter/precompiles/fvm.rs, actors/evm/src/interpreter/precompiles/mod.rs, actors/evm/src/interpreter/precompiles/parameter.rs, actors/evm/tests/call.rs
1.5k LOC was getting very annoying to scroll through and find things.
=> EVM: Split precompiles into smaller, more readable files

actors/evm/src/interpreter/instructions/call.rs, actors/evm/src/interpreter/precompiles/evm.rs, actors/evm/src/interpreter/precompiles/fvm.rs, actors/evm/src/interpreter/precompiles/mod.rs, actors/evm/src/interpreter/system.rs, actors/evm/tests/call.rs, runtime/src/runtime/fvm.rs, runtime/src/runtime/mod.rs, runtime/src/test_utils.rs, test_vm/src/lib.rs
also fixes https://github.com/filecoin-project/ref-fvm/issues/1201 and https://github.com/filecoin-project/ref-fvm/issues/1216
=> EVM: Call with flags through runtime

actors/evm/src/interpreter/instructions/call.rs
Also, always don't abort/revert if we fail to decode the revert data. Instead, just return the data without decoding it.
This shouldn't happen if we call an EVM contract, but may happen if we call another contract.
fixes https://github.com/filecoin-project/ref-fvm/issues/1253
=> fix: decode revert data

actors/evm/src/interpreter/instructions/ext.rs, actors/evm/src/lib.rs, actors/evm/tests/ext_opcodes.rs
- test for account codehash
- test getbytecodehash method
- assert that embedded empty bytecode has value is correct
=> Add test case for extcodehash

Cargo.lock, actors/account/Cargo.toml, actors/datacap/Cargo.toml, actors/datacap/src/lib.rs, actors/datacap/src/testing.rs, actors/datacap/tests/harness/mod.rs, actors/market/Cargo.toml, actors/multisig/Cargo.toml, actors/verifreg/Cargo.toml, actors/verifreg/src/lib.rs, actors/verifreg/tests/harness/mod.rs, actors/verifreg/tests/verifreg_actor_test.rs, state/Cargo.toml, state/src/check.rs, test_vm/Cargo.toml, test_vm/src/util.rs
=> Update frc46_token, fvm_actor_utils, and frc42_dispatch

actors/account/src/state.rs, actors/cron/src/state.rs, actors/datacap/src/state.rs, actors/init/src/state.rs, actors/market/src/deal.rs, actors/market/src/lib.rs, actors/market/src/state.rs, actors/miner/src/beneficiary.rs, actors/miner/src/lib.rs, actors/miner/src/state.rs, actors/miner/tests/util.rs, actors/multisig/src/state.rs, actors/paych/src/state.rs, actors/power/src/state.rs, actors/reward/src/state.rs, actors/system/src/lib.rs, actors/verifreg/src/state.rs, runtime/src/runtime/fvm.rs, runtime/src/runtime/mod.rs, runtime/src/test_utils.rs, runtime/src/util/batch_return.rs, test_vm/src/lib.rs
=> Purge all uses of Cbor trait

runtime/src/actor_error.rs
=> Remove unused macro

actors/eam/src/lib.rs
This is just dead code at this point.
fixes https://github.com/filecoin-project/ref-fvm/issues/1292
=> fix: remove EAM::CreateAccount

actors/ethaccount/src/lib.rs
https://github.com/filecoin-project/ref-fvm/issues/1354
=> EthAccount: Fixup and clarify comments

actors/eam/src/lib.rs
I think this was missed in #979
=> EAM: Remove InitAccountParams

actors/evm/src/interpreter/instructions/call.rs, actors/evm/src/interpreter/system.rs, actors/evm/src/lib.rs, actors/evm/tests/delegate_call.rs
closes https://github.com/filecoin-project/ref-fvm/issues/1369
cc @samuerio
=> EVM: Pass original caller through to callee for Delegate Call 

actors/evm/src/interpreter/precompiles/fvm.rs, actors/evm/src/interpreter/precompiles/mod.rs, actors/evm/src/interpreter/precompiles/parameter.rs
closes https://github.com/filecoin-project/ref-fvm/issues/1344
=> EVM: Disable get-randomness precompile

actors/eam/src/lib.rs
fixes https://github.com/filecoin-project/ref-fvm/issues/1394
=> EAM: Check addresses for reserved range of native precompile

actors/evm/src/interpreter/stack.rs
=> EVM: fix the stack underflow check on swap

.github/workflows/ci.yml, .github/workflows/release.yml, Makefile, build.rs, runtime/build.rs
Part of https://github.com/filecoin-project/ref-fvm/issues/1250.
=> add Hyperspace testnet parameters and build config.

actors/placeholder/src/lib.rs
Avoid user confusion by explaining the situation loud and clear.
Closes https://github.com/filecoin-project/ref-fvm/issues/1304
=> EVM: fix embryo method error message

actors/evm/src/interpreter/precompiles/fvm.rs, actors/evm/src/interpreter/precompiles/parameter.rs, actors/evm/tests/precompile.rs
Also test `remaining_x` a bit, depends on ~~#1016~~ now https://github.com/filecoin-project/builtin-actors/pull/1036 and will need a rebase before merge
=> EVM: Test resolve_address precompile

actors/evm/src/interpreter/precompiles/evm.rs
=> EVM: Pad ripemd160 precompile to 32 bytes

actors/evm/src/interpreter/precompiles/fvm.rs, actors/evm/tests/call.rs
https://github.com/filecoin-project/ref-fvm/issues/1056
Needs #1043 for test
=> Restrict CALLACTOR to methodnum >= 1024

actors/evm/src/interpreter/instructions/bitwise.rs
fixes https://github.com/filecoin-project/ref-fvm/issues/1465
=> EVM: fix sar behavior, and test bit shifts

actors/evm/src/interpreter/execution.rs, actors/evm/src/interpreter/instructions/mod.rs, actors/evm/src/interpreter/instructions/stack.rs
fixes https://github.com/filecoin-project/ref-fvm/issues/1400
=> feat: implement push0

actors/evm/src/interpreter/instructions/lifecycle.rs, actors/evm/tests/create.rs, test_vm/tests/evm_test.rs
And improve the lifecycle tests.
=> fix: correctly decode EAM return on resurrect

actors/evm/src/interpreter/precompiles/fvm.rs
Has been disabled for a while now and it's implementation would change anyway with the new Parameter reader, so it's not worth keeping around.
=> EVM: Remove get_randomness precompile

Cargo.lock, actors/datacap/src/lib.rs, actors/datacap/tests/datacap_actor_test.rs, actors/eam/src/lib.rs, actors/market/src/ext.rs, actors/market/src/lib.rs, actors/market/tests/cron_tick_timedout_deals.rs, actors/market/tests/deal_api_test.rs, actors/market/tests/harness.rs, actors/market/tests/market_actor_test.rs, actors/market/tests/on_miner_sectors_terminate.rs, actors/market/tests/verify_deals_for_activation_test.rs, actors/miner/tests/miner_actor_test_peer_info.rs, actors/paych/Cargo.toml, actors/verifreg/src/lib.rs, actors/verifreg/src/state.rs, runtime/src/runtime/fvm.rs, runtime/src/runtime/mod.rs, test_vm/src/util.rs, test_vm/tests/account_authenticate_message_test.rs
=> chore: merge master into next

actors/paych/src/lib.rs
Only @mriise is allowed to approve this PR.
=> fix: paych: correct error message

actors/evm/src/interpreter/instructions/arithmetic.rs
Part of https://github.com/filecoin-project/ref-fvm/issues/1541.
=> EVM: fix addmod and test

actors/evm/src/interpreter/stack.rs
simple regression test for unused behavior, but being pedantic.
=> EVM: test swap 0

actors/evm/src/interpreter/instructions/mod.rs, actors/evm/src/interpreter/instructions/stack.rs, actors/evm/tests/basic.rs
adds a bit of documentation for them as well.
=> EVM: Test `PUSH*` opcodes a bit more

actors/evm/src/interpreter/instructions/arithmetic.rs, actors/evm/src/interpreter/uints.rs
finishes https://github.com/filecoin-project/ref-fvm/issues/1541
=> EVM: test remaining math ops

actors/evm/src/interpreter/instructions/boolean.rs
=> EVM: Test boolean ops

test_vm/src/lib.rs
This is the expected behaviour per the latest FIPs.
=> fix: test_vm: Don't set predictable address for accounts

actors/evm/src/interpreter/stack.rs
=> EVM: Test `POP` opcode

runtime/src/runtime/fvm.rs, runtime/src/runtime/mod.rs, test_vm/src/lib.rs
This reduces some duplicated logic, and depends on `set_state_root` to enforce read-onliness for `create`.
=> refactor: Runtime: Move create and state into default impl

test_vm/src/lib.rs
Supports the flow described in FIP-0048.
=> test_vm: support creating actors over placeholders

actors/cron/tests/cron_actor_test.rs, actors/datacap/tests/harness/mod.rs, actors/init/tests/init_actor_test.rs, actors/market/tests/activate_deal_failures.rs, actors/market/tests/cron_tick_deal_slashing.rs, actors/market/tests/cron_tick_timedout_deals.rs, actors/market/tests/deal_api_test.rs, actors/market/tests/harness.rs, actors/market/tests/market_actor_test.rs, actors/market/tests/publish_storage_deals_failures.rs, actors/market/tests/random_cron_epoch_during_publish.rs, actors/miner/tests/apply_rewards.rs, actors/miner/tests/change_worker_address_test.rs, actors/miner/tests/miner_actor_test_construction.rs, actors/miner/tests/miner_actor_test_precommit_batch.rs, actors/miner/tests/repay_debts.rs, actors/miner/tests/util.rs, actors/miner/tests/withdraw_balance.rs, actors/multisig/tests/multisig_actor_test.rs, actors/paych/tests/paych_actor_test.rs, actors/power/tests/harness/mod.rs, actors/power/tests/power_actor_tests.rs, actors/reward/tests/reward_actor_test.rs, actors/verifreg/tests/harness/mod.rs, actors/verifreg/tests/verifreg_actor_test.rs, runtime/src/test_utils.rs
Supports changes introduced in #1126, will be needed for further FVM work.
=> Runtime: test: Refactor to add expect_send_simple

actors/evm/src/interpreter/instructions/control.rs, actors/evm/src/interpreter/instructions/hash.rs, actors/evm/src/interpreter/instructions/memory.rs, actors/evm/src/interpreter/instructions/state.rs, actors/evm/src/interpreter/test_util.rs
context: https://filecoinproject.slack.com/archives/C029MT4PQB1/p1675277933939939
=> EVM: refactor unit test macro params

runtime/src/runtime/fvm.rs, runtime/src/runtime/mod.rs, runtime/src/test_utils.rs, test_vm/src/lib.rs
Unused, shrinks the diff with master further :)
=> Runtime: Drop unused user_get_randomness methods

Cargo.lock, actors/eam/Cargo.toml, actors/eam/src/lib.rs, actors/eam/tests/create.rs, actors/evm/shared/src/address.rs
fixes https://github.com/filecoin-project/ref-fvm/issues/974
=> EVM: use shared evm create in the EAM

actors/evm/src/interpreter/instructions/lifecycle.rs, actors/evm/tests/create.rs
fixes https://github.com/filecoin-project/ref-fvm/issues/1499
=> EVM: apply EIP150 to CREATE/CREATE2

actors/evm/shared/src/address.rs, actors/evm/src/interpreter/instructions/context.rs, actors/evm/src/interpreter/instructions/lifecycle.rs, actors/evm/src/interpreter/precompiles/fvm.rs, actors/evm/tests/precompile.rs
Fixes https://github.com/filecoin-project/ref-fvm/issues/1407
Fixes https://github.com/filecoin-project/builtin-actors/pull/1084
=> EVM: address some TODOs

actors/evm/Cargo.toml, build.rs
The hyperspace feature was missing.
=> fix: added hyperspace feature for build

actors/account/src/lib.rs, actors/account/tests/account_actor_test.rs
=> FIP-0055: Account: Accept all MethodNums past FIRST_EXPORTED_METHOD_NUMBER

actors/evm/src/interpreter/instructions/call.rs, actors/evm/src/interpreter/instructions/control.rs
On top of https://github.com/filecoin-project/builtin-actors/pull/1182
Closes https://github.com/filecoin-project/ref-fvm/issues/1546
=> EVM: call tests

actors/market/src/lib.rs, actors/market/tests/cron_tick_timedout_deals.rs, actors/market/tests/harness.rs, actors/market/tests/market_actor_test.rs, actors/market/tests/publish_storage_deals_failures.rs, actors/paych/src/lib.rs, actors/paych/tests/paych_actor_test.rs, actors/verifreg/src/lib.rs
Fixes #1140 
Needs:
Can be reviewed commit-by-commit.
=> feat: Market actor: Harden PublishStorageDeals

actors/evm/src/interpreter/execution.rs, actors/evm/src/interpreter/test_util.rs
none should panic.
This is something that came up in discussion with steb; no issue associated afaik.
=> EVM: check all instructions for stack underflow behaviour

actors/evm/src/interpreter/execution.rs, actors/evm/src/interpreter/test_util.rs
EVM: check all instructions for stack underflow behaviour
=> chore: backport #1188

actors/init/tests/init_actor_test.rs
Mirror what's in next, because that makes more sense.
=> init_actor_test: tweak test detail

README.md
Honestly this README needs more cleanup, but this can land for now.
=> README: Drop stale version

actors/miner/tests/terminate_sectors_test.rs
=> test: miner: deal termination errors are swallowed for cron only

test_vm/src/lib.rs, test_vm/src/util.rs, test_vm/tests/authenticate_message_test.rs, test_vm/tests/batch_onboarding.rs, test_vm/tests/change_beneficiary_test.rs, test_vm/tests/change_owner_test.rs, test_vm/tests/commit_post_test.rs, test_vm/tests/datacap_tests.rs, test_vm/tests/evm_test.rs, test_vm/tests/extend_sectors_test.rs, test_vm/tests/init_test.rs, test_vm/tests/market_miner_withdrawal_test.rs, test_vm/tests/multisig_test.rs, test_vm/tests/power_scenario_tests.rs, test_vm/tests/publish_deals_test.rs, test_vm/tests/replica_update_test.rs, test_vm/tests/terminate_test.rs, test_vm/tests/test_vm_test.rs, test_vm/tests/verified_claim_test.rs, test_vm/tests/verifreg_remove_datacap_test.rs, test_vm/tests/withdraw_balance_test.rs
Closes https://github.com/filecoin-project/builtin-actors/issues/554
=> Refactor TestVM fixtures to take Address and TokenAmount by reference

actors/market/src/policy.rs, runtime/src/runtime/policy.rs, test_vm/tests/extend_sectors_test.rs, test_vm/tests/publish_deals_test.rs
=> FIP-0052 - extend max sector and deal duration to 3.5 years

test_vm/src/deals.rs, test_vm/src/lib.rs, test_vm/tests/publish_deals_test.rs
A prefactor for #1298 to enable use of the DealBatcher there.
=> Extract DealBatcher to new module and simplify in preparation for wider use

test_vm/tests/verified_claim_test.rs
Adding a test around state invariants with the new batched commit confirmation behavior.
=> Test ProveCommit batched deal activation

actors/miner/src/deadline_info.rs, actors/miner/tests/deadlines.rs
This PR optimizes `next_not_elapsed` so that no iteration is needed
=> optimize next_not_elapsed

runtime/src/runtime/policy.rs
I've left the semantic descriptions on the `Policy` struct, and justifications for specific values where those values are defined.
=> Remove duplicated comments in policy values

actors/init/src/state.rs, actors/init/src/testing.rs, actors/market/src/balance_table.rs, actors/market/src/lib.rs, actors/market/src/state.rs, actors/market/src/testing.rs, actors/market/tests/harness.rs, actors/market/tests/market_actor_test.rs, integration_tests/src/tests/batch_onboarding_deals_test.rs, runtime/src/util/map.rs
I'll chunk this migration up into a few smaller PRs. Here's the first.
=> Use Map2 instead of Map and raw HAMTs in market actor

runtime/src/runtime/fvm.rs, runtime/src/runtime/mod.rs, runtime/src/test_utils.rs, test_vm/src/messaging.rs
=> chore: remove support for verifying single seals

actors/miner/src/deadline_state.rs, actors/miner/src/lib.rs, actors/miner/src/sectors.rs, actors/miner/src/state.rs, actors/miner/src/types.rs
=> Implement new ProveReplicaUpdates3 for direct data onboarding.

Cargo.lock, Cargo.toml
=> chore: update eth deps and remove default features

actors/miner/src/lib.rs, actors/miner/tests/miner_actor_test_precommit_batch.rs, actors/miner/tests/prove_replica_test.rs, actors/miner/tests/util.rs, runtime/src/test_utils.rs
This is just a start, sharing for review to get much of the harness stuff out of the way first. 
@ZenGround0 I intend to add a bunch of state checking to this simple test before merging, would appreciate ✅ if everything else looks good so I can land it independently after that.
=> Basic unit tests for ProveReplicaUpdate3

Cargo.lock, Cargo.toml, actors/miner/tests/miner_actor_test_wpost.rs, actors/miner/tests/state_harness.rs, actors/paych/src/lib.rs, actors/paych/tests/paych_actor_test.rs, actors/power/src/state.rs, actors/power/tests/power_actor_tests.rs, runtime/Cargo.toml, runtime/src/runtime/fvm.rs, runtime/src/runtime/mod.rs, runtime/src/runtime/randomness.rs, runtime/src/test_utils.rs, test_vm/src/messaging.rs
Will be merged by rebase. I'm doing this in a _new_ branch to avoid re-writing fvm-next (which would break ref-fvm & helix CI at the moment because commits will disappear).
=> Merge fvm-next into master

actors/verifreg/src/lib.rs, actors/verifreg/tests/harness/mod.rs
=> Invoke Verif reg balance method with read only perms

integration_tests/src/tests/extend_sectors_test.rs
see https://github.com/filecoin-project/builtin-actors/pull/1229/files#r1348107574
=> test: validate that sector updates correctly update sector metadata

actors/miner/tests/declare_recoveries.rs, actors/miner/tests/miner_actor_test_commitment.rs, actors/miner/tests/report_consensus_fault.rs, actors/miner/tests/util.rs
=> Test to handle consensus fault verification errors

actors/miner/src/lib.rs, runtime/src/runtime/policy.rs
=> feat: limit PoSted partitions to 3

integration_tests/src/util/workflows.rs, vm_api/src/util/mod.rs
Small bug in cron-execution during integration tests that affects virtual machines with gas-accounting mechanics.
=> execute cron actor implicitly

test_vm/src/lib.rs, vm_api/src/lib.rs
Part 1 (MachineContext "constants") of #1348
=> simulate machine context fields in the TestVM

actors/miner/src/emit.rs, actors/miner/tests/util.rs
Addresses https://github.com/filecoin-project/FIPs/discussions/754#discussioncomment-7384878.
=> Rename miner to provider in Miner Actor events

actors/miner/src/emit.rs, actors/miner/src/lib.rs, actors/miner/tests/util.rs, integration_tests/src/expects.rs, integration_tests/src/tests/commit_post_test.rs, integration_tests/src/tests/extend_sectors_test.rs, integration_tests/src/tests/move_partitions_test.rs, integration_tests/src/tests/replica_update_test.rs, integration_tests/src/tests/terminate_test.rs, integration_tests/src/tests/verified_claim_test.rs, integration_tests/src/tests/verifreg_remove_datacap_test.rs, integration_tests/src/util/workflows.rs, test_vm/src/messaging.rs, vm_api/src/trace.rs
For #1464. Integration tests refactor for actor events.
=> integration tests for actor events

Cargo.lock, Cargo.toml
Unintentionally downgraded in #1481
=> chore: deps: update to fvm_ipld_amt 0.6.2

integration_tests/src/tests/batch_onboarding_deals_test.rs, integration_tests/src/tests/change_owner_test.rs, integration_tests/src/tests/replica_update2_test.rs, integration_tests/src/tests/replica_update_test.rs
This annotation was added on master while DDO work was on this branch. Some of these were missed in the rebase.
=> Add missing vm_test annotations.

actors/market/src/lib.rs, actors/market/src/state.rs, actors/market/tests/batch_activate_deals.rs, actors/market/tests/harness.rs, actors/market/tests/on_miner_sectors_terminate.rs, actors/market/tests/sector_content_changed.rs, actors/miner/src/commd.rs, actors/miner/src/notifications.rs, actors/miner/tests/util.rs, integration_tests/src/util/mod.rs
Implements changes to most of the comments in https://github.com/filecoin-project/builtin-actors/pull/1486.
=> Response to review on #1486

actors/market/src/lib.rs, actors/market/src/state.rs, actors/market/src/testing.rs, actors/market/src/types.rs, actors/market/tests/batch_activate_deals.rs, actors/market/tests/cron_tick_deal_expiry.rs, actors/market/tests/cron_tick_deal_slashing.rs, actors/market/tests/cron_tick_timedout_deals.rs, actors/market/tests/deal_api_test.rs, actors/market/tests/deal_termination.rs, actors/market/tests/harness.rs, actors/market/tests/market_actor_legacy_tests.rs, actors/market/tests/market_actor_test.rs, actors/market/tests/on_miner_sectors_terminate.rs, actors/market/tests/random_cron_epoch_during_publish.rs, actors/market/tests/sector_content_changed.rs, actors/market/tests/settle_deal_payments.rs, actors/market/tests/transient_marked_for_termination.rs, actors/market/tests/verify_deals_for_activation_test.rs, integration_tests/src/expects.rs, integration_tests/src/tests/batch_onboarding_deals_test.rs, integration_tests/src/tests/extend_sectors_test.rs, integration_tests/src/tests/terminate_test.rs, integration_tests/src/tests/verified_claim_test.rs, integration_tests/src/util/mod.rs, integration_tests/src/util/workflows.rs, runtime/src/util/message_accumulator.rs, test_vm/tests/suite/verified_claim_test.rs
See https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0074.md
This code was originally reviewed when landing on integration/manual-settlement [in these PRs](https://github.com/filecoin-project/builtin-actors/pulls?q=is%3Apr+base%3Aintegration%2Fmanual-settlement). For any blocking changes (or sufficient non-blocking ones), I'll make a new PR against that base to resolve them.
Closes #1399
=> FIP-0074 Merge integration/manual-settlement into master

actors/verifreg/src/emit.rs, actors/verifreg/tests/harness/mod.rs, actors/verifreg/tests/verifreg_actor_test.rs, integration_tests/src/util/workflows.rs
=> chore: backport #1511 and #1516

Cargo.lock, Cargo.toml
Updates workspace package version to 14.0 as per release instructions for the NV23 v14 Actors release.
=> Update actors version for v14.0 release

state/src/check.rs
=> Update Typo in check.rs

actors/miner/src/lib.rs, actors/miner/src/state.rs, actors/miner/tests/daily_fees_test.rs, actors/miner/tests/deadline_cron.rs, actors/miner/tests/declare_faults.rs, actors/miner/tests/declare_recoveries.rs, actors/miner/tests/extend_sector_expiration_test.rs, actors/miner/tests/miner_actor_test_wpost.rs, actors/miner/tests/util.rs, integration_tests/src/tests/commit_post_test.rs
Without 0.5x24hBR cap applied.
Stacked on https://github.com/filecoin-project/builtin-actors/pull/1622
No unique tests added here yet, but plenty extended to account for it.
=> fip-0100: apply fee payment at end of deadline

actors/miner/src/lib.rs, actors/miner/tests/prove_replica_test.rs
=> fip-0100: update daily fee on replica update when zero

actors/miner/src/lib.rs, actors/miner/src/monies.rs, actors/miner/src/types.rs, actors/miner/tests/compact_partitions_test.rs, actors/miner/tests/initial_pledge.rs, actors/miner/tests/monies_test.rs, actors/miner/tests/pledge_penalty_for_termination.rs, actors/miner/tests/terminate_sectors_test.rs, actors/miner/tests/util.rs, actors/power/src/lib.rs, actors/power/src/types.rs, actors/power/tests/power_actor_tests.rs, integration_tests/src/tests/extend_sectors_test.rs, integration_tests/src/util/workflows.rs
Draft based on the current state of the FIP. I will update (especially tests) once all the information needed is in place.
https://github.com/filecoin-project/FIPs/pull/1128#issuecomment-2674126309
=> fip-0098: simplify termination fee

Cargo.lock, Cargo.toml, actors/miner/src/state.rs, actors/miner/src/testing.rs, actors/miner/tests/miner_actor_test_partitions.rs, actors/miner/tests/sector_assignment.rs, actors/miner/tests/util.rs, integration_tests/src/tests/replica_update_test.rs
And handle the `window_post_partitions_sector` to `window_post_partition_sectors` rename.
=> chore: update ref-fvm to v4.6.0 (and update the actors utils to match)

Cargo.lock, Cargo.toml
=> chore: release 16.0.0-rc2

actors/miner/src/lib.rs, actors/miner/tests/terminate_sectors_test.rs
Kudos to @beck-8 for noticing this @ https://github.com/filecoin-project/builtin-actors/pull/1639#issuecomment-2731950713
Adds some testing that fails without the fix.
=> fix(miner): termination fee should use full sector duration

Cargo.lock, Cargo.toml
=> chore: release 16.0.0-rc3

Cargo.lock, Cargo.toml, actors/evm/tests/call.rs, actors/evm/tests/env.rs, integration_tests/src/tests/evm_test.rs
This is only used for testing the EVM.
=> chore(evm): update alloy
