- actors/miner/src/lib.rs
As part of the review of https://github.com/filecoin-project/ref-fvm/pull/351.
> `is_principal` predicate has moved to `Type` as an associated fn.

- actors/miner/Cargo.toml
- actors/miner/tests/miner_actor_test_construction.rs
- actors/miner/tests/util.rs
> miner actor: construction tests

- README.md
- bundle/build.rs
The `v6` lineage will be maintained in the `v6` branch.
> switch master to v7.

- actors/multisig/src/types.rs
- actors/multisig/tests/multisig_actor_test.rs
- actors/runtime/src/test_utils.rs
Addresses #58 adding expect abort and expect abort contains message helper functions.  This makes it easier to translate go tests by using the same error checking pattern.  Trying it out on an existing multisig test it makes things more compact and nice imo.
I ran into the borrow checker when trying to implement these on the mock runtime since the closures they call need mutable references to the runtime since they are always going to run `rt.call`.  Conveniently the rust mock runtime's call function handles state rollback (where expect abort does in go) so the expect abort methods need 0 runtime state and implementing these as free functions works out fine.  But I'm open to suggestions on any nice ways to get past the borrow checker and get these on the mock runtime.
Also this PR adds …
> Second msig test and expect_abort helpers

- Cargo.lock
- Cargo.toml
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/runtime/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
The magic command is:
`cargo set-version --exclude fil_actor_bundler --workspace --bump major`
(from the cargo-edit crate)
edit: this is the kind of magic command that looks like it works, but doesn't.
> chore: release v7 versions of all actors

- actors/runtime/src/test_utils.rs
- actors/verifreg/Cargo.toml
- actors/verifreg/tests/verifreg_actor_test.rs
Check out the `expect_error` function added to test_utils.
Also experimented with the use of modules to group tests. It adds extra import noise, but otherwise seems like a decent organisation tool. For giant actors we could also separate into more files.
> Verified registry constructor and verifier mutation tests

- Cargo.toml
- bundler/Cargo.toml
We need a new release that uses the released FVM.
> chore: release bundler

- Cargo.lock
- Cargo.toml
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/runtime/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- bundler/Cargo.toml
This:
- Ensures that we use the correct IPLD version everywhere by switching to the latest FVM version.
- Avoids publishing the bundler crate from "old" releases...
- Skips 6.0.3 so the bundle and actor versions are identical.
NOTE: I think we'll want to move the bundler into a new repo. Keeping it here is going to be a _pain_.
> chore: switch to released fvm and publish

- actors/account/tests/account_actor_test.rs
I audited the account actor tests, and tweaked them to use the `expect_abort` function.
> Use expect_abort in account tests

- actors/runtime/src/test_utils.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
A few notes
- Fixed a bug in the mock runtime that returned the wrong `ErrForbidden` from caller verification
- Extracted the test harness into a submodule of the tests module, following the pattern [described in the Rust Book here](https://doc.rust-lang.org/book/ch11-03-test-organization.html#submodules-in-integration-tests).
> More verified registry tests

- Cargo.lock
- Cargo.toml
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/runtime/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
Done using `cargo-edit`.
```sh
$ cargo set-version --exclude fil_actor_bundler --workspace 7.0.3-alpha.1
```
This way, this branch is ready to take in new changes.
> set `release/v7` version to `7.0.3-alpha.1`.

- actors/market/Cargo.toml
- actors/market/src/lib.rs
- actors/market/src/types.rs
- actors/miner/Cargo.toml
- actors/miner/src/bitfield_queue.rs
- actors/miner/src/deadline_state.rs
- actors/miner/src/expiration_queue.rs
- actors/miner/src/lib.rs
- actors/miner/src/partition_state.rs
- actors/miner/src/sector_map.rs
- actors/miner/src/sectors.rs
- actors/miner/src/state.rs
- actors/miner/src/termination.rs
- actors/miner/src/types.rs
Instead of renaming `fvm_ipld_bitfield` to `bitfield`, use its original
name. This also makes patching easier.
> refactor: don't rename package

- actors/power/tests/harness/mod.rs
- actors/power/tests/power_actor_tests.rs
Someone should extract the `collect_keys` to somewhere common later. I think it should go on a wrapper type (like `Set`) but doing so is a bit beyond me at the moment.
> Initial power actor test harness and test for construction and creating a miner.

- .cargo/config.toml
- actors/power/tests/harness/mod.rs
- actors/power/tests/power_actor_tests.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
This prevents code (especially tests) from accidentally discarding a Result containing an error, such as from an actor call.
I found a way to set this project-wide rather than per file. I think it's appropriate to do so for this whole project, actor code and test code.
Closes #100. [This guide](https://github.com/rust-unofficial/patterns/blob/main/anti_patterns/deny-warnings.md) lists a raft of other warnings which we might consider denying in actor code (while cautioning against a blanket deny-all-warnings configuration). It might be worth following through with them too.
> Build configuration to deny unused results

- Cargo.lock
- Cargo.toml
- actors/runtime/build.rs
- build.rs
We can now configure the current network by either:
1. Specifying the correct network as a feature flag on the bundle.
2. Or by setting the `BUILD_FIL_NETWORK` environment variable to the correct network name (at build time).
Possible network names are:
- devnet
- caterpillarnet
- default
Importantly, the _runtime_ crate no longer cares about the devnet/caterpillarnet features. Instead, it looks for the `BUILD_FIL_NETWORK` environment variable, and configures itself (via a build script).
If we decide that we don't need it, we can simplify further by removing the bundle-level feature entirely (using _only_ the environment variable).
> Use environment variables to configure the network

- Makefile
- README.md
- Add targets for test/check
- Add a target for bumping versions and releasing.
- Explicitly use GNU make because the default make implementation on macos is garbage.
> feat: improve makefile

- Cargo.lock
- Cargo.toml
- bundler/Cargo.toml
This version removes the identity hash feature to avoid panics.
> chore: release bundler v1.0.3

- Makefile
- README.md
- `make` now runs `make check`.
- We now automatically install the `wasm32-unknown-unknown` target.
- Rename `release` to `bump-version` to make it clear that that's _all_ it does.
- Add a `set-version` target to set a specific version.
And improve the documentation.
> feat: refactor makefile again

- Cargo.lock
- Cargo.toml
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/runtime/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
removes the "identity" multihash feature from the build script
> chore: release 6.0.6

- Cargo.lock
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/runtime/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- bundler/Cargo.toml
- bundler/src/lib.rs
Companion to #145 
Cherrypicks and backports the new bundler from https://github.com/filecoin-project/builtin-actors/pull/132
> Backport manifest v1 bundler to release/v6

- actors/account/src/lib.rs
- actors/cron/src/lib.rs
- actors/init/src/lib.rs
- actors/market/src/lib.rs
- actors/miner/src/lib.rs
- actors/multisig/src/lib.rs
- actors/paych/src/lib.rs
- actors/power/src/lib.rs
- actors/reward/src/lib.rs
- actors/runtime/src/actor_error.rs
- actors/runtime/src/runtime/mod.rs
- actors/runtime/src/util/cbor.rs
- actors/runtime/src/util/chaos/mod.rs
- actors/runtime/src/util/mod.rs
- actors/verifreg/src/lib.rs
Also added a mirroring serialization function. Note that there are still many paths which go through `ActorError::from(e: fvm_shared::encoding::Error)` via the `?` operator, which thus don't have the opportunity to describe the object that failed to de/serialize.
> Replace Runtime.deserialize_params with static helper function

- Cargo.lock
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/miner/src/bitfield_queue.rs
- actors/miner/src/deadline_state.rs
- actors/miner/src/expiration_queue.rs
- actors/miner/src/lib.rs
- actors/miner/src/partition_state.rs
- actors/miner/src/sector_map.rs
- actors/miner/tests/util.rs
1. Validates that we can't try to "set" the u64::MAX bit.
2. Validates that input bitfields are "minimally encoded".
> Switch to the new BitField version with better validation

- build.rs
Rerun if the source, dependencies, build options, build script _or_ actors have changed. We need to check if the actors have changed because otherwise, when building in a workspace, we won't re-run the build script and therefore won't re-compile them.
This _isn't_ an issue when building as a dependency fetched from crates.io (because the crate is immutable).
> build: re-run bundle build if workspace actors have changed

- build.rs
This is supported (and enabled by default) in wasmtime, and should increase actor performance.
Fixes #164
> build: enable bulk memory operations in wasm

- actors/miner/src/lib.rs
Mirror fix in specs-actors [here](https://github.com/filecoin-project/specs-actors/pull/1582).
When PRU specifies multiple deadlines this should not cause failure.
Calling out no merge because this is consensus breaking.  This goes in wherever the v8 changes are merging.
> Fix prove replica update multi dline bug

- Cargo.toml
- actors/account/Cargo.toml
- actors/account/src/lib.rs
- actors/cron/Cargo.toml
- actors/cron/src/lib.rs
- actors/init/Cargo.toml
- actors/init/src/lib.rs
- actors/market/Cargo.toml
- actors/market/src/lib.rs
- actors/miner/Cargo.toml
- actors/miner/src/lib.rs
- actors/multisig/Cargo.toml
- actors/multisig/src/lib.rs
- actors/paych/Cargo.toml
- actors/paych/src/lib.rs
- actors/power/Cargo.toml
- actors/power/src/lib.rs
- actors/reward/Cargo.toml
- actors/reward/src/lib.rs
- actors/runtime/Cargo.toml
- actors/runtime/src/actor_error.rs
- actors/runtime/src/lib.rs
- actors/runtime/src/runtime/mod.rs
- actors/system/Cargo.toml
- actors/system/src/lib.rs
- actors/verifreg/Cargo.toml
- actors/verifreg/src/lib.rs
- build.rs
This way, the actors can be bundled with other wasm software as libraries.
fixes #109
> feat: use a fil-actor feature instead of relying on the wasm target

- actors/miner/src/deadline_state.rs
Go code: https://github.com/filecoin-project/specs-actors/blob/3c87d38a4829460c92a084465521f649d7613796/actors/builtin/miner/miner_actor.go#L1702
This is needed to prevent the risk of FVM nodes falling out of sync on mainnet today. I'm not sure whether we _also_ want this in `master` (v8 actors), I'm inclined to say no.
> Miner: Declare_faults_recovered: fix exitcode to match specs-actors

- .github/workflows/ci.yml
- upload-bundle.sh
Notice the -k in the curl invocation; estuary's certificates have expired.
We'll have to fix that once the certs have been renewed.
> add workflow to upload bundle from CI to estuary

- Cargo.toml
- actors/runtime/src/runtime/fvm.rs
Ideally, we'd be able to inject a full-on custom panic _handler_ instead of adding a hook (smaller build). But we can't do that and also use the standard library.
> feat: call the abort syscall on panic

- .github/workflows/ci.yml
- upload-bundle.sh
so that we don't have to download the bundle ourselves to get the hash.
> output sha256sum for uploaded bundle

- actors/paych/tests/paych_actor_test.rs
> Implement voucher_invalid_after_settling unit test for paych actor.

- actors/paych/tests/paych_actor_test.rs
Not sure what happen here or why it wasn't caught by the CI.
> Fix typo in paych unit test.

- Cargo.lock
- Cargo.toml
- build.rs
- Upgrades transitive fvm_shared dependency to the same version as the one used here (0.2 -> 0.5).
- Changes the interface to take actor "types" by string, instead of by the shared "actor type". That way, updating the bundler's fvm_shared dependency isn't a semver breaking change.
> chore: upgrade bundler

- Cargo.lock
- Cargo.toml
- build.rs
Backports: #224
- Upgrades transitive fvm_shared dependency to the same version as the one used here (0.2 -> 0.5).
- Changes the interface to take actor "types" by string, instead of by the shared "actor type". That way, updating the bundler's fvm_shared dependency isn't a semver breaking change.
> backport: upgrade bundler

- Cargo.lock
- Cargo.toml
- build.rs
- Upgrades transitive fvm_shared dependency to the same version as the one used here (0.2 -> 0.5).
- Changes the interface to take actor "types" by string, instead of by the shared "actor type". That way, updating the bundler's fvm_shared dependency isn't a semver breaking change.
> backport: upgrade bundler (#224)

- actors/miner/src/deadline_state.rs
This was a bug in state-mismatch fix. It doesn't affect master.
> fix: propagate fault recovery error

- actors/paych/tests/paych_actor_test.rs
- TestActor_UpdateChannelStateRedeem
> Implement last test in the UpdateChannelStateRedeem category for paych.

- Makefile
crates.io is async, so publishing will fail if we immediately publish a second crate after publishing the first. There are definitely more reliable ways to fix this, but this is "good enough" for a makefile. It's idempotent anyways...
> fix(Makefile): add a delay between cargo publish steps

- actors/account/tests/account_actor_test.rs
- actors/cron/tests/cron_actor_test.rs
- actors/init/tests/init_actor_test.rs
- actors/market/tests/market_actor_test.rs
- actors/miner/tests/miner_actor_test_construction.rs
- actors/miner/tests/util.rs
- actors/multisig/tests/multisig_actor_test.rs
- actors/multisig/tests/util.rs
- actors/paych/tests/paych_actor_test.rs
- actors/power/tests/harness/mod.rs
- actors/power/tests/power_actor_tests.rs
- actors/reward/tests/reward_actor_test.rs
- actors/runtime/src/test_utils.rs
- actors/system/src/lib.rs
- actors/verifreg/tests/harness/mod.rs
> Fixes to mock runtime

- Cargo.toml
- actors/account/Cargo.toml
- actors/account/src/lib.rs
- actors/cron/Cargo.toml
- actors/cron/src/lib.rs
- actors/init/Cargo.toml
- actors/init/src/lib.rs
- actors/market/Cargo.toml
- actors/market/src/lib.rs
- actors/miner/Cargo.toml
- actors/miner/src/lib.rs
- actors/multisig/Cargo.toml
- actors/multisig/src/lib.rs
- actors/paych/Cargo.toml
- actors/paych/src/lib.rs
- actors/power/Cargo.toml
- actors/power/src/lib.rs
- actors/reward/Cargo.toml
- actors/reward/src/lib.rs
- actors/runtime/Cargo.toml
- actors/runtime/src/actor_error.rs
- actors/runtime/src/lib.rs
- actors/runtime/src/runtime/mod.rs
- actors/system/Cargo.toml
- actors/system/src/lib.rs
- actors/verifreg/Cargo.toml
- actors/verifreg/src/lib.rs
- build.rs
feat: use a fil-actor feature instead of relying on the wasm target #175 
This way, the actors can be bundled with other wasm software as libraries.
fixes #109
> backport: `fil-actor` feature

- Cargo.lock
- Cargo.toml
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/runtime/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
Adds the `fil-actor` feature so users can import these actors as libraries.
> chore: release v7.2.1

- actors/market/tests/market_actor_test.rs
> Market actor unit tests (part 12)

- Cargo.lock
- Cargo.toml
- actors/account/Cargo.toml
- actors/account/src/lib.rs
- actors/cron/Cargo.toml
- actors/cron/src/lib.rs
- actors/init/Cargo.toml
- actors/init/src/lib.rs
- actors/market/Cargo.toml
- actors/market/src/lib.rs
- actors/miner/Cargo.toml
- actors/miner/src/lib.rs
- actors/multisig/Cargo.toml
- actors/multisig/src/lib.rs
- actors/paych/Cargo.toml
- actors/paych/src/lib.rs
- actors/power/Cargo.toml
- actors/power/src/lib.rs
- actors/reward/Cargo.toml
- actors/reward/src/lib.rs
- actors/runtime/Cargo.toml
- actors/runtime/src/actor_error.rs
- actors/runtime/src/lib.rs
- actors/runtime/src/runtime/mod.rs
- actors/system/Cargo.toml
- actors/system/src/lib.rs
- actors/verifreg/Cargo.toml
- actors/verifreg/src/lib.rs
- build.rs
Unfortunately, this feature breaks the bundler build script because it's not possible to specify features outside of the current workspace. It's theoretically possible to fix this by using environment variable hacks, but the correct solution is #263.
fixes #264
> Revert "fil-actor" feature

- actors/runtime/build.rs
This was wrongly set to 2GiB; it should be 2KiB.
> policy: fix minimum consensus power for caterpillarnet

- actors/power/src/state.rs
- actors/power/tests/harness/mod.rs
- actors/power/tests/power_actor_tests.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/power/power_test.go#L169).
* `enroll_cron_epoch_multiple_events`
* `enroll_cron_epoch_before_current_epoch`
* `enroll_cron_epoch_given_negative_epoch_should_fail`
> power actor tests part 3

- actors/power/tests/harness/mod.rs
- actors/power/tests/power_actor_tests.rs
Implemented test from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/power/power_test.go#L518).
* `given_no_miner_claim_update_pledge_total_should_abort`
> power actor tests part 7

- Cargo.lock
- actors/multisig/src/lib.rs
- actors/multisig/tests/multisig_actor_test.rs
- actors/multisig/tests/util.rs
- test_vm/Cargo.toml
- test_vm/src/lib.rs
> Multisig vesting unit tests 

- actors/power/src/lib.rs
- actors/power/tests/harness/mod.rs
- actors/power/tests/power_actor_tests.rs
- actors/runtime/src/test_utils.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/power/power_test.go#L643).
* `event_scheduled_in_past_called_next_round`
* `fails_to_enroll_if_epoch_negative`
* `skips_invocation_if_miner_has_no_claim`
* `handles_failed_call`
* `success_with_one_miner_and_one_confirmed_sector`
* `success_with_one_miner_and_multiple_confirmed_sectors`
* `duplicate_sector_numbers_are_ignored_for_a_miner`
I omitted verify log checks, doesn't seem we are exposing those and it's not done in other tests? If we still want it, I can spend some time trying to catch those "somehow". :)
Sorry for so many tests in one PR, I wanted to avoid having conflicts with myself.
> power actor tests part 9, 10 & 12

- actors/market/src/lib.rs
- actors/market/src/policy.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/market/market_test.go#L2378)
* `TestMarketActorDeals`
* `TestMaxDealLabelSize`
Note: `TestMaxDealLabelSize` does not exactly assert what the Go reference does as the underlying type is just plain `String`. Does this divergence have any bad implications?
> Market actor tests p6

- actors/market/tests/harness.rs
- actors/market/tests/random_cron_epoch_during_publish.rs
> Five RandomCronEpochDuringPublish tests

- actors/market/src/lib.rs
- actors/market/src/policy.rs
- actors/market/tests/harness.rs
- actors/market/tests/verify_deals_for_activation_test.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/market/market_test.go#L2629)
* `verify_deal_and_get_deal_weight_for_unverified_deal_proposal`
* `verify_deal_and_get_deal_weight_for_verified_deal_proposal`
* `verification_and_weights_for_verified_and_unverified_deals`
* `fail_when_caller_is_not_a_storage_miner_actor`
* `fail_when_deal_proposal_is_not_found`
* `fail_when_caller_is_not_the_provider`
* `fail_when_current_epoch_is_greater_than_proposal_start_epoch`
* `fail_when_deal_end_epoch_is_greater_than_sector_expiration`
* `fail_when_the_same_deal_id_is_passed_multiple_times`
> market actor tests p8

- actors/miner/src/deadline_state.rs
- actors/miner/tests/deadline_assignment.rs
> Miner unit test (part 2)

- actors/miner/tests/deadline_state_test.rs
- actors/miner/tests/util.rs
Implementing tests from [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/deadline_state_test.go).
* `adds_sectors`
* `adds_sectors_and_proves`
* `terminates_sectors`
* `terminates_unproven_sectors`
* `pops_early_terminations`
* `removes_partitions`
* `marks_faulty`
* `marks_unproven_sectors_faulty`
* `cannot_remove_partitions_with_early_terminations`
* `can_pop_early_terminations_in_multiple_steps`
I will add the invariants check implementation in a separate PR to limit the PR size.
> miner deadlines test part 7 without invariants

- actors/miner/tests/miner_actor_test_construction.rs
- actors/miner/tests/util.rs
It's a copy-paste from [here](https://github.com/filecoin-project/builtin-actors/blob/remove-duplicate/actors/runtime/src/test_utils.rs#L1226]. Or the other way around. Anyway, one duplicate less.
> remove duplicate `new_bls_addr` from miner utils

- .github/workflows/ci.yml
- actors/miner/src/internal_tests.rs
- actors/miner/tests/expiration_queue.rs
- actors/multisig/tests/multisig_actor_test.rs
- actors/multisig/tests/util.rs
So it can bash you also when you are doing redundant clones in your tests!
> enable all-targets for clippy

- actors/miner/src/partition_state.rs
- actors/miner/tests/deadline_state_test.rs
Implementing tests from [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/deadline_state_test.go).
* `post_all_the_things`
* `post_with_unproven_faults_recoveries_untracted_recoveries`
* `post_with_skipped_unproven`
* `post_missing_partition`
* `post_partition_twice`
* `retract_recoveries`
* `cannot_declare_faults_in_missing_partitions`
* `cannot_declare_faults_recovered_in_missing_partitions`
Fixed a particular fiasco in `Partition::record_faults` that was making `retract_recoveries` test fail.
> miner deadlines test p9

- actors/miner/tests/change_peer_id_test.rs
- actors/miner/tests/util.rs
Implemented test from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/miner/miner_test.go#L2331)
* `successfully_change_peer_id`
> miner tests part 35

- Cargo.lock
- actors/runtime/Cargo.toml
- actors/runtime/src/runtime/fvm.rs
This matches Lotus fake proofs behaviour and makes one of our tests pass. I assume it's okay for all other clients (but if not we can change things as needed).
Also, I'm not sure whether or not the distinction between `testing` and `testing-fake-proofs` introduced in https://github.com/filecoin-project/builtin-actors/pull/261 is actually needed. I think we might be able to get rid of one of them, but that requires some investigation on my part.
> fake-proofs: match lotus verify post behaviour

- build.rs
Otherwise, it can fail and we can end up using the cached version.
> fix: check actor build status in build script

- actors/miner/tests/confirm_update_worker_key_test.rs
- actors/miner/tests/util.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/miner/miner_test.go#L2890)
* `successfully_changes_the_worker_address`
* `does_nothing_before_the_effective_date`
* `does_nothing_when_no_update_is_set`
> miner tests part 40

- actors/market/tests/compute_data_commitment.rs
- actors/runtime/src/test_utils.rs
> Implement remaining market actor ComputeDataCommitment tests

- actors/miner/tests/deadline_cron_defers_stops_restarts.rs
- actors/miner/tests/util.rs
> Miner tests (part 28)

- actors/miner/src/lib.rs
- actors/miner/tests/miner_actor_test_wpost.rs
- Test to come, though the bug is already demonstrated by a lotus test.
- Needs a backport to v7 upon approval.
`verify_windowed_post` returns `Ok(true)` on a valid post, `Ok(false)` on an invalid post, and `Err` on some errors. We cannot assume that a non-error return from `verify_windowed_post` means a valid post.
This is related to the fix in https://github.com/filecoin-project/builtin-actors/pull/63/commits/c81794b708df7dc3f849e69345d6d2098d2cf1db, but for the other relevant callsite.
> miner actor: fix submit_windowed_post

- actors/miner/tests/extend_sector_expiration_test.rs
- actors/miner/tests/util.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/miner/miner_test.go#L1802)
* `rejects_negative_extensions`
* `rejects_extension_too_far_in_future`
* `rejects_extension_past_max_for_seal_proof`
* `updates_expiration_with_valid_params`
* `updates_many_sectors`
* `supports_extensions_off_deadline_boundary`
~~Long test warning :warning:~~
> miner tests part 31

- actors/miner/tests/check_sector_proven_test.rs
- actors/miner/tests/compact_partitions_test.rs
- actors/miner/tests/util.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/miner/miner_test.go#L2347)
* `compacting_a_partition_with_both_live_and_dead_sectors_removes_dead_sectors_retains_live_sectors`
* `fail_to_compact_partitions_with_faults`
* `fails_to_compact_partitions_with_unproven_sectors`
* `fails_if_deadline_is_equal_to_wpost_period_deadlines`
* `fails_if_deadline_is_open_for_challenging`
* `fails_if_deadline_is_next_up_to_be_challenged`
* `deadline_after_next_deadline_should_still_be_open_for_compaction`
* `deadlines_challenged_last_proving_period_should_still_be_in_dispute_window`
* `compaction_should_be_forbidden_during_the_dispute_window`
* `compaction_should_be_allowed_following_the_dispute_window`
* …
> Miner test p36

- actors/miner/tests/change_owner_address_test.rs
- actors/miner/tests/util.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/miner/miner_test.go#L2954)
* `proposed_must_be_valid`
* `only_owner_can_propose`
* `withdraw_proposal`
* `nominee_must_confirm_self_explicitly`
* `only_owner_can_change_proposal`
* `successful_change`
* `only_nominee_can_confirm`
> miner tests part 41

- actors/miner/src/monies.rs
- actors/miner/tests/expected_reward_for_power_clampted_at_atto_fil_test.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/miner/monies_test.go#L172)
* `expected_zero_valued_br_clamped_at_1_attofil`
* `expected_negative_value_br_clamped_at_1_atto_fil`
> miner tests part 47

- actors/miner/tests/change_worker_address_test.rs
- actors/miner/tests/util.rs
- actors/runtime/src/test_utils.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/miner/miner_test.go#L2619)
* `fails_if_new_worker_address_does_not_have_a_code`
* `fails_if_new_worker_is_not_account_actor`
* `fails_if_unable_to_resolve_worker_address`
* `fails_if_worker_public_key_is_not_bls`
* `fails_when_caller_is_not_the_owner`
* `fails_if_unable_to_resolve_control_address`
* `fails_if_control_addresses_length_exceeds_maximum_limit`
* `successfully_change_only_the_worker_address`
* `successfully_resolve_and_change_only_control_addresses`
* `successfully_clear_all_control_addresses`
* `successfully_change_both_worker_and_control_addresses`
* `change_cannot_be_overridden`
> miner tests part 39

- actors/miner/tests/precommit_deposit_and_initial_pledge_positive_test.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/miner/monies_test.go#L199)
* `initial_pledge_clamped_at_one_attofil`
* `precommit_deposit_is_clamped_at_one_attofil`
> Miner test p48

- actors/miner/src/state.rs
- actors/runtime/src/actor_error.rs
- actors/runtime/src/runtime/fvm.rs
- actors/runtime/src/runtime/mod.rs
- actors/runtime/src/test_utils.rs
- Enforce state-transaction prohibition on create and delete actor calls
- Replace panics with explicit abort codes
- Distinguish proof verification error from invalid proof; propagate error numbers
- Rename ActorError::user_assertion_failed to follow concise convention
> Fixes to FVM runtime from internal audit.

- actors/miner/tests/sector_map_test.rs
Implemented tests from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/miner/sector_map_test.go)
* `deadline_sector_map_empty`
* `deadline_sector_map_overflow`
* `deadline_sector_map_values`
* `partition_sector_map_empty`
* `partition_sector_map_overflow`
* `partition_sector_map_values`
* `deadline_sector_map_sorted`
* `partition_sector_map_sorted`
* `deadline_sector_map`
:warning: I omitted `TestDeadlineSectorMapError` as it doesn't seem to be relevant given map API.
> miner test part 54 and 55

- Cargo.toml
This brings the uncompressed bundle size down to 5.23MiB uncompressed, or 640KiB compressed (zstd, level 18).
> chore: strip debug info in release builds

- Cargo.lock
- actors/miner/src/lib.rs
- actors/miner/src/types.rs
- actors/miner/tests/miner_actor_test_commitment.rs
- actors/power/src/state.rs
- actors/runtime/src/test_utils.rs
- test_vm/Cargo.toml
- test_vm/src/lib.rs
- test_vm/tests/commit_post_test.rs
- test_vm/tests/power_scenario_tests.rs
This completes the first of four subcases of TestCommitPoStFlow.  It introduces helpers that are needed for other integration tests.  It also fixes some testing harness bugs.
Helpers:
- `get_miner_balances`
- `with_epoch`
- `create_miner`
- `precommit_sectors`
- `advance_by_deadline` and variations
- `submit_windowed_post`
Fixes:
- `ExpectInvoction` can now match on `from`
- Runtime methods no longer fall when acting on an receiver called with a non id address
- Cron actor actually written at cron address by `new_with_singletons`
> post commit happy path itest

- actors/account/src/lib.rs
- actors/account/src/testing.rs
- actors/account/tests/account_actor_test.rs
Implemented invariant checks from [here](https://github.com/filecoin-project/specs-actors/blob/0afe155bfffa036057af5519afdead845e0780de/actors/builtin/account/testing.go)
> account actor invariant checks

- actors/reward/src/lib.rs
- actors/reward/src/testing.rs
Implemented checks from [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/reward/testing.go). 
I didn't add those checks in the existing crate tests as it fails on several invariants, just like Go tests do (they don't include the checks as well).
> reward invariant checks

- Cargo.lock
- Cargo.toml
- actors/market/src/testing.rs
- actors/market/tests/harness.rs
- actors/miner/src/testing.rs
- actors/miner/tests/apply_rewards.rs
- actors/miner/tests/util.rs
- actors/power/src/testing.rs
- actors/state/Cargo.toml
- actors/state/src/check.rs
- actors/state/src/lib.rs
Mother of all invariant checks from [here](https://github.com/filecoin-project/specs-actors/blob/master/actors/states/check.go). I extracted it into a separate crate to not bloat runtime crate dependencies.
Fixed some minor issues with existing invariant checks:
* always pass `State` by reference and not move it,
* Power actor check didn't aggregate cron events, only the last one was in the `StateSummary`.
Closes https://github.com/filecoin-project/builtin-actors/issues/44
> all invariants check

- actors/verifreg/src/lib.rs
- actors/verifreg/src/types.rs
- test_vm/src/lib.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
This PR fixes five bugs in https://github.com/filecoin-project/ref-fvm/pull/306:
- Checking status of verified clients using is_verifier is wrong
- is_verifier should load verifiers, not verified_clients
- use_proposal_id should return curr_id, not next_id
- introduce the domain separation of remove data cap signatures
- remove_verified_client_data_cap should actually return RemoveDataCapReturn
Also adds an equivalent test to https://github.com/filecoin-project/specs-actors/blob/master/actors/test/verifreg_remove_datacap_test.go, which resolves #86
> fix implementation of FIP-0028

- actors/paych/tests/paych_actor_test.rs
This test was ported from go-actors and reveals a discrepancy, but we are willing to let the discrepancy stand. See https://github.com/filecoin-project/builtin-actors/issues/29#issuecomment-1154126298 for more.
> Paych tests: Remove bad signing test

- Cargo.lock
- actors/market/tests/harness.rs
- actors/miner/src/testing.rs
- actors/reward/src/testing.rs
- actors/runtime/Cargo.toml
- actors/runtime/src/util/message_accumulator.rs
- actors/state/Cargo.toml
- actors/state/src/check.rs
- test_vm/Cargo.toml
- test_vm/src/lib.rs
- test_vm/src/util.rs
- test_vm/tests/commit_post_test.rs
- test_vm/tests/multisig_test.rs
- test_vm/tests/power_scenario_tests.rs
- test_vm/tests/publish_deals_test.rs
- test_vm/tests/replica_update_test.rs
- test_vm/tests/terminate_test.rs
- test_vm/tests/test_vm_test.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
Added invariant checks in some of the integration tests. Many of the existing ones are breaking those invariants on purpose so the checks should be added carefully considering each case.
Fixed one bug in miner invariant check and introduced a workaround for reward invariant, see more in https://github.com/filecoin-project/builtin-actors/issues/459.
> invariant checks in integration tests

- test_vm/src/util.rs
- test_vm/tests/batch_onboarding.rs
- test_vm/tests/commit_post_test.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/replica_update_test.rs
- test_vm/tests/terminate_test.rs
Calling submit_windowed_post with PowerPair::zero() will now assert that the miner's power has not changed by asserting that there are no subinvocations in the call to SubmitWindowedPoSt.
Closes https://github.com/filecoin-project/builtin-actors/issues/465
> Tests: allow submit_windowed_post to check for unchanged power

- Cargo.lock
- Cargo.toml
- Makefile
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- runtime/Cargo.toml
- state/Cargo.toml
- test_vm/Cargo.toml
Also removes testing from the set-version target, as it's _really_ slow and we test in CI anyways.
> chore: bump version to 9.0.0-alpha.1

- runtime/src/runtime/policy.rs
Made the `Policy` API more ergonomic and less surprising. Without this, some implementations will end up with rather brittle workarounds like [here](https://github.com/ChainSafe/forest/blob/606351ee0587aedd475b837fd642de87044daadd/types/networks/src/lib.rs#L154-L216).
> make Policy struct API more ergonomic

- Cargo.lock
- Cargo.toml
- actors/init/Cargo.toml
- actors/init/src/lib.rs
- actors/init/src/state.rs
- actors/init/src/types.rs
- actors/miner/tests/miner_actor_test_wpost.rs
- runtime/Cargo.toml
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- test_vm/Cargo.toml
- test_vm/src/lib.rs
This brings #216 into master, feature gated by m2-native.
TODO:
> [m2 native] user actor installation

- runtime/build.rs
- runtime/src/runtime/policy.rs
- minimum consensus power is 16GiB.
- short precommit challenge delay (10 epochs).
> adjust Wallaby parameters.

- .github/workflows/ci.yml
This change makes CI trigger whenever:
- a pull request is opened/updated
- a commit is pushed to `master` branch
The main advantage of this setup is that it enables CI runs on PRs originating from forks.
> ci: change CI trigger to pull_request + push to master

- test_vm/src/lib.rs
- test_vm/src/util.rs
- test_vm/tests/publish_deals_test.rs
A "valid" signature has its bytes equal to the plaintext. Anything else is considered invalid.
More context here: https://github.com/filecoin-project/builtin-actors/pull/502#discussion_r932383910.
> test: modify test_vm's verify_signature behaviour

- Cargo.toml
Locally, it reduces the size of the bundle by over 5%.
Before `5505513B`. After `5224309`.
The drawback is that it may increase compilation time, but if I understand correctly, creating the bundle is not done very often in the development cycle.
I took the suggestion from [here](https://github.com/johnthagen/min-sized-rust#reduce-parallel-code-generation-units-to-increase-optimization). There may be some other automatic tricks we could use, e.g. treating the wasm bundle with [wasm-opt](https://github.com/WebAssembly/binaryen#binaryen-optimizations).
> set codegen units to 1 for wasm

- Cargo.lock
- actors/datacap/Cargo.toml
- actors/datacap/src/lib.rs
- actors/datacap/src/state.rs
- actors/datacap/src/testing.rs
- actors/datacap/src/types.rs
- actors/datacap/tests/datacap_actor_test.rs
- actors/datacap/tests/harness/mod.rs
- runtime/Cargo.toml
- runtime/src/actor_error.rs
Implements a standalone datacap fungible token actor, using the Helix fungible token actor library in development for https://github.com/filecoin-project/FIPs/discussions/407
Part of https://github.com/filecoin-project/FIPs/discussions/313. Not yet integrated with anything. I haven't written tests yet as we're merging to a development branch with priority on ensuring the end-to-end hookup is correct.
This is ready for review, with following caveats:
> Implements datacap token actor

- Cargo.lock
- README.md
- actors/init/src/lib.rs
- actors/market/src/lib.rs
- actors/miner/src/lib.rs
- actors/multisig/src/lib.rs
- actors/paych/src/lib.rs
- actors/power/src/lib.rs
- runtime/src/builtin/shared.rs
- runtime/src/runtime/builtins.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- runtime/src/util/chaos/mod.rs
- state/Cargo.toml
- state/src/check.rs
- test_vm/Cargo.toml
- test_vm/src/lib.rs
This PR copies the builtin actor `Type` enum out of the FVM SDK into the built-in actors repo.
Breaking coupling is necessary to enable development of the built-in actors (e.g. adding a new one) without depending on changes to the FVM SDK. Since the FVM doesn't want to depend on the actors, any changes to the enum need to be propagated to the FVM.
This removes all but one reference to the path `fvm_shared::actor`, the holdout being the conversion between the two `Type` enums at the SDK syscall. This last one should be removed by changing the SDK to pass through the bare i32 value that it wrapped.
```
[~/p/f/builtin-actors](anorth/builtin-type)$ rg 'fvm_shared::actor'
runtime/src/runtime/fvm.rs
173:        let t = fvm_shared::actor::builtin::Type::from_i32(typ as i32).unwrap();
```
Closes …
> Duplicate fvm_shared::actor::builtin::Type into runtime::builtins::Type

- actors/account/src/lib.rs
- actors/account/tests/account_actor_test.rs
- actors/multisig/src/lib.rs
- actors/multisig/tests/multisig_actor_test.rs
- runtime/src/builtin/shared.rs
Implements a token receiver hook that always succeeds. The receivers don't deserialise parameters because they don't inspect them.
I've avoided adding a dependency on the fungible token library from runtime/shared by copying the method number, and avoiding the hook parameter type. I don't think it would be a big deal to add the dep, but it's painful while we depend on a github hash[*].
Even if the calling convention or receiver hook is not standardised, this is a reasonable way for the data cap token specifically to interact with account-type actors, and opens it up to user contracts. But hopefully this standard will be adopted.
*: We depend on a hash because no crates yet, because name will depend on FIP number, which we have't allocated yet).
> Implement could-be-standard token receiver hook in account and multisig

- actors/evm/src/lib.rs
- actors/evm/tests/basic.rs
Let's avoid wearing clown shoes, bytes are bytes.
Also improves the test to check both condition for balances.
> EVM: don't encode contract invocation output data

- actors/evm/src/interpreter/bytecode.rs
- actors/evm/src/interpreter/execution.rs
- actors/evm/src/interpreter/opcode.rs
- removes the explicit instruction array.
- removes the undefined instructions.
- removes the need for ordering instructions in a specific way.
- ensures that we can't talk about invalid instructions.
> feat: enum-based opcodes

- runtime/src/runtime/mod.rs
Fix compile when not compiling as a "fil actor" (e.g., for testing).
> fix: non-fil-actor-compile

- Cargo.lock
- actors/datacap/Cargo.toml
- actors/datacap/src/lib.rs
- actors/datacap/src/types.rs
Updates to latest `main` commit on the token library branch.
The token receiver flow is a little awkward, the library has plans to improve this.
Closes #534. Closes #535.
FYI @alexytsu @abright
> Upgrade fungible token library. Use standard exit codes. Use standard token method params/return types.

- actors/miner/src/beneficiary.rs
- actors/miner/src/lib.rs
- actors/miner/src/state.rs
- actors/miner/src/types.rs
- actors/miner/tests/change_beneficiary_test.rs
- actors/miner/tests/change_owner_address_test.rs
- actors/miner/tests/util.rs
- actors/miner/tests/withdraw_balance.rs
This is an implementation for FIP-0029 PR https://github.com/filecoin-project/specs-actors/pull/1571 to provide Beneficiary address support. In this implementation, version and upgrading is not considered, that is, directly put the code change into the current version. The back-compliance could be done once the next version content is determined.
Closes #422
> feat:implement beneficiary fip0029

- Cargo.lock
- Cargo.toml
- build.rs
- runtime/src/runtime/builtins.rs
This change upgrades to the v4 bundler that _does not_ depend on the FVM to map actor types to IDs. Instead, it relies on the Type enum defined in this repo.
This means new actor types can be added here without having to make changes in multiple places.
> feat: use Type from builtin-actors when building the bundle

- Cargo.lock
- Cargo.toml
- README.md
- actors/init/src/lib.rs
- actors/market/src/lib.rs
- actors/miner/src/lib.rs
- actors/multisig/src/lib.rs
- actors/paych/src/lib.rs
- actors/power/src/lib.rs
- build.rs
- runtime/src/builtin/shared.rs
- runtime/src/runtime/builtins.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- runtime/src/util/chaos/mod.rs
- state/Cargo.toml
- state/src/check.rs
- test_vm/Cargo.toml
- test_vm/src/lib.rs
This ports two changes from master to avoid depending on ref-fvm's Type definition.
> Unlink "Type" from ref-fvm

- Cargo.lock
- actors/account/Cargo.toml
- actors/account/src/lib.rs
- actors/account/src/types.rs
- actors/account/tests/account_actor_test.rs
- actors/market/src/ext.rs
- actors/market/src/lib.rs
- actors/market/tests/cron_tick_timedout_deals.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/market/tests/publish_storage_deals_failures.rs
- test_vm/src/util.rs
- test_vm/tests/account_authenticate_message_test.rs
- test_vm/tests/publish_deals_test.rs
This PR is a prototype of https://github.com/filecoin-project/FIPs/discussions/413 for illustrative purpsoses.
UPDATE: [The FIP draft](https://github.com/filecoin-project/FIPs/pull/424) has since been opened. It uses a different name for the method than this PR, we'll reconcile them based on which is better received.
resolves #533
> feat: Implement FIP-0044

- actors/miner/tests/prove_commit.rs
- actors/miner/tests/util.rs
- actors/reward/src/lib.rs
- actors/reward/src/state.rs
- prefer is_positive/negative/zero over comparisons with TokenAmount::zero (saves an allocation).
- Prefer div_floor over div_rem
> fix: idiomatic math operations

- actors/init/src/lib.rs
- actors/init/src/state.rs
- actors/multisig/src/lib.rs
- actors/multisig/src/state.rs
- actors/multisig/tests/multisig_actor_test.rs
- actors/paych/src/lib.rs
- actors/paych/tests/paych_actor_test.rs
- actors/system/src/lib.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- runtime/src/actor_error.rs
- runtime/src/builtin/shared.rs
This is a backport from the `decouple-fil+` branch. The new traits and conversion methods are extracted from @dignifiedquire's work in #214. We can have them now without necessarily following through all the work to convert everything over. I've converted a couple of the simpler actors to demonstrate, and we should use the new traits for new code.
> Traits and impls for adding context and exit codes to results.

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/runtime/fvm.rs
We renamed hash to hash_owned to allow for a hash_into method.
> chore: update sdk

- actors/market/tests/harness.rs
- actors/miner/tests/expiration_queue.rs
- actors/miner/tests/miner_actor_test_bitfield_queue.rs
- actors/verifreg/tests/harness/mod.rs
- runtime/src/test_utils.rs
With the real FvmRuntime, we expect that cloning the &Blockstore returned by Runtime#store() would simply clone the reference.
This is because inside the FVM, blockstore calls proxy out to FVM syscalls; the proxy itself holds no state, and cloning it is
unimportant.
However, in the MockRuntime, we were using a owned MemoryBlockstore. Cloning it would return a new physical copy, thus breaking the expectation.
This commit makes MockRuntime use an Rc<MemoryBlockstore>, so all clones will point to the same MemoryBlockstore, thus preserving the expectation.
> test runtime: use Rc<MemoryBlockstore>.

- .github/workflows/ci.yml
- Cargo.lock
- actors/evm/Cargo.toml
- runtime/Cargo.toml
Fixes https://github.com/filecoin-project/ref-fvm/issues/840.
We were depending on getrandom as a result of not disabling default features in the brand new runtime dependencies libsecp256k1, substrate-bn. `rand` with default features also drags in `getrandom`, but I'm not sure why this wasn't failing already because `rand` also pulls in `getrandom` through default features 🤷  Maybe tree shaking? 
Also adds a CI check to verify that Wasm bytecode has no references to bindgen, so this shouldn't happen again.
> fix: remove dependency on getrandom.

- actors/evm/tests/selfdestruct.rs
Before this change, even if we commented out [the selfdestruct execution logic](https://github.com/filecoin-project/builtin-actors/blob/next/actors/evm/src/interpreter/execution.rs#L849) the test was still passing.
> Make test verify if selfdestruct actually works

- Cargo.lock
- actors/evm/Cargo.toml
- actors/evm/tests/asm.rs
- actors/evm/tests/calc.rs
This integrates the etk assmbler, so that we can write EVM contracts in assembly for test purposes.
Also includes a magic calc test contract to make sure the whole contraption works.
See also https://github.com/filecoin-project/ref-fvm/issues/831
> basic contract assembler for testing EVM

- Makefile
Otherwise, rust will "unify" the features between the test targets and the non-test targets, so we'll miss non-test dependency issues.
> fix: check code both with all targets and without

- Cargo.lock
- Cargo.toml
- build.rs
- runtime/src/runtime/builtins.rs
I realised we need to add extra configuration to have a new builtin actor build for use in a network.
@Stebalien I'm more or less forced to use `Datacap = 12` here because the build requires these to be sequential. When EVM merges into main some time after this, it'll have to take `13`.
> Include datacap actor in build bundle

- actors/datacap/src/lib.rs
- actors/datacap/src/types.rs
- actors/datacap/tests/datacap_actor_test.rs
- actors/datacap/tests/harness/mod.rs
- actors/verifreg/src/ext.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/tests/harness/mod.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
Minting is not a standard token method, so adding a parameter to mint allows this to happen with the business logic of which account to approve encapsulated in the verified registry, but no additional inter-actor sends.
Closes #529.
> Automatically approve built-in market as operator for all minted datacap

- actors/evm/src/interpreter/instructions/call.rs
Residual from #614:
- add comment for gas
- barf for very large output address size
> EVM: some small fixes

- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/lib.rs
- actors/evm/tests/basic.rs
- `GetBytecode` returns the CID of the bytecode block. In the future, the FVM's reachability analysis should add this CID to the reachable set of the caller. `GetBytecode` is publicly callable.
- `GetStorageAt` returns the value stored in the supplied EVM storage key. This method is private and only intended for calls from instrumentation and client functionality, such as the `eth_getStorageAt` JSON-RPC API operation. In order to make it private, it validates that the caller is the zero address. It needs to be private to preserve EVM guarantees: no contract is able to arbitrarily access storage keys from another contract. The client must form a message from the 0x0 sender address for this method to work.
Supports https://github.com/filecoin-project/ref-fvm/issues/838
Supports …
> EVM runtime: implement GetBytecode and GetStorageAt getters.

- actors/datacap/src/lib.rs
- actors/datacap/src/state.rs
- actors/datacap/src/testing.rs
- actors/datacap/tests/harness/mod.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/src/state.rs
- test_vm/src/lib.rs
@ZenGround0 challenged me on this earlier, and now I think I was wrong. We'll be deploying new code any time this could possibly change anyway.
I still think the datacap token actor holding the address of its governor (the verified registry) in state makes sense, so that the datacap actor has no conceptual dependency back on the other builtins.
> Verifreg uses a constant for datacap token actor addr, rather than state.

- actors/verifreg/src/lib.rs
- actors/verifreg/src/state.rs
- actors/verifreg/src/types.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
As discussed.
In this PR I haven't also migrated the `verifiers` map to be keyed by actor ID. This would require a migration, but a small one and we're touching this actor anyway. LMK whether you think I should do that, and if so in this PR or a follow-up.
> Use ActorID rather than addresses in new verifreg state

- actors/datacap/src/lib.rs
- actors/datacap/tests/datacap_actor_test.rs
- actors/datacap/tests/harness/mod.rs
If I understand the way datacap works with the TokenAmount type it is 1) measured in units of bytes 2) measured at a base level of atto bytes when tokenized.  That is a token amount of 10^18 should represent one byte.
If these assumptions are correct then the [recent infinite limit](https://github.com/filecoin-project/builtin-actors/pull/611/files#diff-b372537e46dbaa904e6da0d0c5d07314a080245f3146a86a0fde77d718b54e20R40) is not actually that big ~GBs.  This PR changes it to ~1000 EiB.  Unfortunately `TokenAmount::from_whole` takes i64 not i128 so creating this constant is now messy.
> Raise market allowance infinite constant

- .github/actions/rust-cargo-run/action.yml
- .github/workflows/ci.yml
- Cargo.toml
- Enable CI caching. Not that it seems to help much...
- Optimize critical dependencies (hashing, test_vm, bigint).
- Avoid building bundles when testing. That gets tested in a separate step.
Ideally we'd just optimize all dependencies, but caching doesn't seem very effective for some reason.
> optimized tests & ci caching

- .cargo/config.toml
- .github/workflows/ci.yml
- Cargo.toml
- build.rs
This can cause issues with caching. Unfortunately, we can only specify them per-target, not per-profile.
> build: avoid RUSTFLAGS

- Cargo.toml
This isn't as big of an issue as hashing, but it still matters for tests.
> build: optimize bitfield operations in tests

- actors/market/src/deal.rs
- actors/market/src/lib.rs
- actors/market/src/policy.rs
- actors/market/src/types.rs
- actors/market/tests/verify_deals_for_activation_test.rs
- actors/miner/src/ext.rs
- actors/miner/src/lib.rs
- actors/miner/src/types.rs
- actors/miner/tests/aggregate_prove_commit.rs
- actors/miner/tests/prove_commit.rs
- actors/miner/tests/util.rs
- ~[ ] change so that new sectors are done the right way~
Closes #528 (as I understand it) -- does not do any miner actor, FIL+ interaction to ensure claim terms are satisfied or any weight rebalancing during expiration extension.  I can do these here rather than in the planned follow ons if preferred.
> Adapt sector info and weight calculation for fip 0045

- actors/miner/src/lib.rs
- actors/miner/tests/change_beneficiary_test.rs
- actors/miner/tests/withdraw_balance.rs
Related PR opened in FIPs repo [here](https://github.com/filecoin-project/FIPs/pull/454)
> WithdrawBalance fails when beneficiary is expired or out of quota

- actors/evm/src/lib.rs
- actors/evm/tests/basic.rs
- actors/evm/tests/calc.rs
- actors/evm/tests/call.rs
- actors/evm/tests/ext_opcodes.rs
- actors/evm/tests/precompile.rs
- actors/evm/tests/selfdestruct.rs
EVM contracts don't take parameters on construction.
> fix: remove input_data from EVM constructor

- actors/verifreg/src/lib.rs
- actors/verifreg/src/types.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
> Delete deprecated UseBytes and RestoreBytes methods from verified registry

- Cargo.lock
- actors/evm/Cargo.toml
- actors/evm/src/interpreter/precompiles.rs
- actors/evm/src/interpreter/uints.rs
Fixes broken ec_recover implementation.
Fixes precompiles that were failing improperly. 
Adds cow for adding padding as needed.
Adds remaining tests
- ec_recover
- modexp
- ec_pair
> EVM: Fix Precompile Failure Modes & Implement Remaining Precompile Tests

- Cargo.lock
- actors/verifreg/Cargo.toml
- actors/verifreg/src/lib.rs
- actors/verifreg/src/state.rs
- actors/verifreg/src/types.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
This was fairly straightforward.
One possibly controversial decision was to allow extension of claims that have already expired. I couldn't find a good reason to deny it. I think this will harmonise with my intentions to (in the future) allow re-committing a verified piece if the original sector fails within a claim's lifetime. The "failure" in the case I've implemented is the client forgetting to extend their claim term in time, so the sector was forced to drop it and the provider will need to re-seal.
Closes #550.
> Implement verified claim term extension by client

- Cargo.lock
- Cargo.toml
- actors/embryo/Cargo.toml
- actors/embryo/src/lib.rs
- build.rs
- runtime/src/runtime/builtins.rs
- runtime/src/test_utils.rs
- state/src/check.rs
- test_vm/src/lib.rs
The embryo actor:
- Has no constructor (the system is expected to simply "set" the embryo code CID, not construct it).
- Immediately aborts when called with a non-zero method.
We could, alternatively, use some well-known "id" address. But it's nice to make this actual valid wasm.
> feat: add an embryo actor

- runtime/Cargo.toml
- runtime/src/runtime/empty.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- test_vm/src/lib.rs
Otherwise, we'll perform a hash in WASM when we first dereference (max once per call) which is just wasteful.
This also fixes the integration tests to use the "correct" empty object. Previously, they were using `()` which mapped to null, not `[]`.
> fix: make the empty array CID const and export it

- runtime/Cargo.toml
- runtime/src/runtime/empty.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- test_vm/src/lib.rs
Otherwise, we'll perform a hash in WASM when we first dereference (max once per call) which is just wasteful.
This also fixes the integration tests to use the "correct" empty object. Previously, they were using `()` which mapped to null, not `[]`.
> fix: make the empty array CID const and export it (#668)

- actors/verifreg/src/lib.rs
- actors/verifreg/src/types.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- runtime/src/util/batch_return.rs
- runtime/src/util/mapmap.rs
This raises a bit of a question about the return value when no allocation IDs were specified. If this were a separate method, maybe we'd return the list of removed IDs. In either case maybe we'd like to return the total datacap reclaimed. I've taken the simplest possible path here of returning nothing.
We could merge these into a return value that includes all these, like:
```
{
specified_allocations: BatchReturn // only non-empty when specified
found_allocations: Vec<AllocationID> // only non-empty when none specified
datacap: DataCap
}
```
What do you think @ZenGround0 ?
Closes #606.
> Remove all expired allocations for a client when none specified

- test_vm/src/lib.rs
Previously, we weren't taking the nonce into account which prevented us from testing multiple messages from the same account.
> test: correctly compute the f2 address in the test vm

- Cargo.lock
- actors/verifreg/Cargo.toml
- actors/verifreg/src/lib.rs
- runtime/src/util/mapmap.rs
See discussion https://github.com/filecoin-project/builtin-actors/pull/669#discussion_r973810703
> Remove ineffective optimisation of HAMT writes in ExtendClaimTerms

- runtime/src/util/batch_return.rs
While I don't think using usizes here will cause any problems, u32 seems like the correct thing to do.
> feat: replace usize with u32

- test_vm/src/lib.rs
- test_vm/tests/init_test.rs
create_actor was overwriting the actor when deploying over an embryo, instead of just changing the code id.
> fix: keep the embryo balance on deploy

- actors/datacap/src/lib.rs
Add `rt.validate_immediate_caller_accept_any()?;` to any method calls in the datacap actor that currently don't have any caller validation. These methods will fail otherwise.
> fix: datacap actor: fix caller validation

- actors/miner/src/expiration_queue.rs
The reschedule recovered while searching, for each expiration set, was
performing a loop Recovering a number of times to look up in a set of
Expiring sectors. This leads to scaling `O(recovering*log(expiring))`.
Following PR changes it such that the work performed is
`O(expiring*log(recovering))`. This should improve the gas usage as on
expectation there are 3-5 sectors expiring in any given queue entry
until we find the right queue.
> Change the complexity scaling of reschedule recovered search

- actors/market/src/lib.rs
- actors/market/src/types.rs
- actors/market/tests/verify_deals_for_activation_test.rs
- actors/miner/src/ext.rs
- actors/miner/src/lib.rs
- actors/miner/tests/aggregate_prove_commit.rs
- actors/miner/tests/extend_sector_expiration_test.rs
- actors/miner/tests/prove_commit.rs
- actors/miner/tests/util.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/src/types.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- runtime/src/util/batch_return.rs
> Claim verifreg allocations from miner actor

- actors/verifreg/src/lib.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
Discovered a minor tweak to avoid burning zero datacap when claims fail.
Closes #664.
> Expand verified registry unit tests

- actors/verifreg/src/lib.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
> Verified registry burns datacap tokens received for successful claim extensions

- Cargo.lock
- actors/datacap/Cargo.toml
- actors/market/Cargo.toml
- actors/verifreg/Cargo.toml
- test_vm/Cargo.toml
Update frc46 token library to 1.1.0 to import fix to token state to use valid HAMT keys
> Update token state

- actors/evm/src/interpreter/address.rs
- actors/evm/src/interpreter/instructions/state.rs
- actors/evm/tests/misc.rs
turns out balance 0 is a valid call and bogus addresses shouldn't bomb.
> EVM runtime: fix BALANCE behaviour to match EVM

- actors/datacap/src/testing.rs
- actors/datacap/tests/datacap_actor_test.rs
- actors/verifreg/src/testing.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- state/src/check.rs
This addresses a large part of #537. I've checked off the items there that I think are done.
> Implement state checks for allocs/claims and between verified registry and datacap.

- Cargo.lock
- actors/datacap/Cargo.toml
- actors/datacap/src/lib.rs
- test_vm/tests/datacap_tests.rs
- test_vm/tests/verified_claim_test.rs
Exercise the datacap actor directly and exercise error paths
Discovered the missing propagation of universal receiver hook errors back to data cap and modified the messenger trait implementation accordingly
> Datacap integration tests

- actors/miner/tests/extend_sector_expiration_test.rs
- test_vm/tests/extend_sectors_test.rs
Add a test that the old extend method will fail when attempting to extend a new (simple qap) sector with deals and inversely test that the new extend method will succeed when extending a legacy (non simple qp) sector with deals.
> Legacy sector tests

- Cargo.lock
- Cargo.toml
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/embryo/Cargo.toml
- actors/evm/Cargo.toml
- actors/evm/src/interpreter/instructions/state.rs
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- runtime/Cargo.toml
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- state/Cargo.toml
- test_vm/Cargo.toml
- test_vm/src/lib.rs
This updates fvm_sdk and fvm_shared to the latest released version ahead of some f4 changes (so we can atomically back out of those changes).
> chore: update fvm_sdk and fvm_shared

- actors/datacap/src/lib.rs
- actors/datacap/tests/datacap_actor_test.rs
- actors/datacap/tests/harness/mod.rs
Finish identifying and testing out non standard behaviors of the datacap token
Closes #543
> Finish datacap tests

- runtime/tests/batch_return_test.rs
> BatchReturn tests

- actors/miner/src/lib.rs
- actors/miner/tests/util.rs
- test_vm/src/lib.rs
Acceptable callers for `change_beneficiary` are `owner` `beneficiary` or `pending_term.new_beneficiary`. We could unwrap all the miner info and check if the caller is one of these three addresses, but caller validation is already handled in the logic of this function, so I opted for using `rt.validate_immediate_caller_accept_any()?;`.
Closes https://github.com/filecoin-project/builtin-actors/issues/760
> fix: Add runtime caller validation for change_beneficiary

- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/lib.rs
- actors/evm/tests/basic.rs
- actors/evm/tests/calc.rs
- actors/evm/tests/call.rs
- actors/evm/tests/create.rs
- actors/evm/tests/env.rs
- actors/evm/tests/ext_opcodes.rs
- actors/evm/tests/misc.rs
- actors/evm/tests/precompile.rs
- actors/evm/tests/selfdestruct.rs
- actors/evm/tests/util.rs
The previous code was passing parameters as raw bytes, but telling the system that these bytes were valid CBOR. Unfortunately:
- This is incorrect and will break once we actually start enforcing this.
- This makes it _very_ difficult to test the EVM because we have quite a bit of testing code that assumes CBOR.
The long-term solution is to correctly handle IPLD (see https://github.com/filecoin-project/builtin-actors/issues/758). But the short-term solution is to just encode/decode parameters as CBOR.
part of https://github.com/filecoin-project/ref-fvm/issues/884
> fix: encode/decode EVM parameters as CBOR

- actors/evm/src/interpreter/bytecode.rs
- actors/evm/src/interpreter/execution.rs
- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/lifecycle.rs
- actors/evm/src/interpreter/instructions/storage.rs
- actors/evm/src/interpreter/system.rs
- actors/evm/src/lib.rs
- actors/evm/src/state.rs
- actors/evm/tests/create.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- test_vm/src/lib.rs
This also refactors the "system" object to manage state. We should probably rename/move it.
We could also consider not _storing_ the runtime inside this object and instead passing it in when we need to?
It also fixes the lifetime issues we were having before without having to reborrow. Apparently, it was just an issue with some of the opcode definitions.
fixes https://github.com/filecoin-project/ref-fvm/issues/960
fixes https://github.com/filecoin-project/ref-fvm/issues/961
> EVM: save/restore state before/after send

- actors/evm/src/interpreter/instructions/call.rs
- runtime/src/test_utils.rs
Currently we have no way to transfer value to embryos (or actors that don't exist yet).
This adds an embryonic state check and turns the call into a send if that's the case.
Also adds a check that we don't transfer value in staticcall context, as this would be a violation of readonly semantics.
Fixes https://github.com/filecoin-project/ref-fvm/issues/1004.
> Transfer value in embryonic actor calls

- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/tests/call.rs
- Allow calling accounts.
- Allow calling embryos by ID.
And oxidize it a bit.
> fix: allow calling more non-contract actors

- actors/evm/src/interpreter/address.rs
- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/ext.rs
- actors/evm/src/interpreter/instructions/lifecycle.rs
- actors/evm/src/interpreter/instructions/state.rs
This is what the EVM does. They're defined to take the low 20 bytes.
> fix: truncate addresses in instructions

- actors/eam/src/lib.rs
- actors/eam/tests/create.rs
This will allow lotus to call this from the fake embryo accounts. This isn't behind a feature gate because it should be secure regardless.
> feat: allow anyone to call EAM::create

- actors/evm/src/interpreter/instructions/bitwise.rs
- actors/evm/src/interpreter/uints.rs
- byte: use the built-in byte and don't touch u128s.
- sar: simplify a bit
- remove dead code
> feat: improve a few more math ops

- actors/verifreg/src/lib.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
`remove_verified_client_data_cap` is used by notaries to remove datacap from verified clients. The verified registry now has it's own datacap balance in the `datacap` actor to keep track of datacap tokens transferred to it by clients making allocations. `remove_verified_client_data_cap` should not be allowed to remove datacap from the verified registry, because the balance of the verified registry must always equal the tokens corresponding to all pending allocations.
I will add a test for this when I have time (soon)
> fix: notaries cannot remove datacap from verifreg

- actors/datacap/src/lib.rs
- test_vm/tests/datacap_tests.rs
I don't think calls to these methods will ever succeed right now.
2 changes:
- receive no params beside the runtime (cf. `Miner::control_addresses`)
- validate the caller (accept any), because all methods must do this.
And add a test.
> datacap: fix Name and Symbol methods

- actors/datacap/src/lib.rs
I'm not sure whether this was intentionally excluded, feel free to close if I'm wrong.
> datacap: add allowance to exported methods

- runtime/src/test_utils.rs
This can be useful for tests that need to track read/write stats.
Specifically, we use this in the EVM tests.
(ported from next, originally by @aakoshh)
> test: make the mock runtime generic over the blockstore

- actors/account/src/lib.rs
- actors/cron/src/lib.rs
- actors/datacap/src/lib.rs
- actors/init/src/lib.rs
- actors/market/src/lib.rs
- actors/market/src/state.rs
- actors/miner/src/lib.rs
- actors/multisig/src/lib.rs
- actors/paych/src/lib.rs
- actors/power/src/lib.rs
- actors/reward/src/lib.rs
- actors/system/src/lib.rs
- actors/verifreg/src/lib.rs
- runtime/src/builtin/shared.rs
- runtime/src/runtime/actor_code.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- runtime/src/util/chaos/mod.rs
- test_vm/src/lib.rs
And use `impl Runtime` where possible. We don't use this in `invoke_method` so implementers can name the runtime if desired.
> feat: refactor blockstore into associated type

- actors/account/src/lib.rs
- actors/account/tests/account_actor_test.rs
- runtime/src/builtin/shared.rs
- runtime/src/test_utils.rs
- test_vm/tests/test_vm_test.rs
This is an example mechanism for defining and enforcing an exported API for builtin actors. The existing low-valued method numbers are all restricted to built-in callers only. This means we can, if ever needed, change their parameters or behaviour while preserving compatibility for callers of exported method numbers. But for now exported method numbers map to the same implementation as the internal.
Before merging:
> Proof of concept exported API for Account actor

- Cargo.lock
- actors/datacap/src/lib.rs
- actors/datacap/tests/datacap_actor_test.rs
- actors/datacap/tests/harness/mod.rs
- actors/init/Cargo.toml
- actors/init/src/lib.rs
- actors/init/tests/init_actor_test.rs
- actors/market/Cargo.toml
- actors/market/src/lib.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/miner/Cargo.toml
- actors/miner/src/lib.rs
- actors/miner/tests/change_beneficiary_test.rs
- actors/miner/tests/declare_recoveries.rs
- actors/miner/tests/miner_actor_test_commitment.rs
- actors/miner/tests/miner_actor_test_construction.rs
- actors/miner/tests/report_consensus_fault.rs
- actors/multisig/src/lib.rs
- actors/multisig/tests/multisig_actor_test.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- runtime/src/builtin/shared.rs
- runtime/src/test_utils.rs
This is work towards #772, and is the first steps towards an implementation of https://github.com/filecoin-project/FIPs/discussions/401.
Using the pattern developed in #797, this PR exports the methods agreed upon in [this spreadsheet](https://docs.google.com/spreadsheets/d/1McCcCDHLagBFd5miTcTDBPuTIzmY6uKTxX6SS-xsKVY/edit#gid=0). It is somewhat sparingly tested.
This PR does not ADD any new methods, that work is deferred to a separate PR, nor does it implement other changes needed to make these exported useful (eg. #806).
> Export stable methods for public access

- actors/cron/src/lib.rs
- actors/cron/tests/cron_actor_test.rs
- actors/paych/src/lib.rs
- actors/paych/tests/paych_actor_test.rs
- actors/power/src/lib.rs
- actors/power/tests/harness/mod.rs
- actors/reward/src/lib.rs
- actors/reward/tests/reward_actor_test.rs
- actors/system/src/lib.rs
As in the title. Non-builtin actors (smart contracts) can now only call those methods that have been explicitly exported in #797 and #807.
> Restrict internal APIs of all actors

- actors/datacap/tests/datacap_actor_test.rs
- actors/miner/tests/batch_method_network_fees_test.rs
- actors/miner/tests/change_owner_address_test.rs
- actors/miner/tests/change_worker_address_test.rs
- actors/miner/tests/compact_partitions_test.rs
- actors/miner/tests/compact_sector_numbers_tests.rs
- actors/miner/tests/declare_recoveries.rs
- actors/miner/tests/extend_sector_expiration_test.rs
- actors/miner/tests/miner_actor_test_commitment.rs
- actors/miner/tests/miner_actor_test_precommit_batch.rs
- actors/miner/tests/miner_actor_test_wpost.rs
- actors/miner/tests/report_consensus_fault.rs
- actors/miner/tests/withdraw_balance.rs
- actors/multisig/tests/multisig_actor_test.rs
- actors/paych/tests/paych_actor_test.rs
- actors/power/tests/harness/mod.rs
- actors/power/tests/power_actor_tests.rs
- actors/reward/tests/reward_actor_test.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- runtime/src/test_utils.rs
It addresses https://github.com/filecoin-project/builtin-actors/issues/605
Another idea was to throw error if there's any unverified `expectation` which would be less automagical. But it would require checking all parts of `expectations` 1 by 1 which would be tedious to maintain.
> Implement Drop as a safeguard for programmer errors

- actors/miner/src/lib.rs
- actors/miner/src/state.rs
- actors/miner/src/types.rs
- actors/miner/tests/apply_rewards.rs
- actors/miner/tests/exported_getters.rs
- actors/miner/tests/util.rs
Adds all-but-one of the new miner methods proposed [here](https://docs.google.com/spreadsheets/d/1McCcCDHLagBFd5miTcTDBPuTIzmY6uKTxX6SS-xsKVY/edit#gid=0).
The missing method is the vesting funds themselves. I'm not sure whether we wanna expose the `VestingFunds` structure, which is a list of `(epoch, amount)` tuples. This is _probably_ stable, but I would like a thumbsup before adding it.
> Miner actor: Add exported getters for info and monies

- Cargo.lock
- actors/datacap/src/lib.rs
- actors/init/src/lib.rs
- actors/market/src/lib.rs
- actors/miner/src/lib.rs
- actors/miner/src/state.rs
- actors/miner/src/types.rs
- actors/miner/tests/apply_rewards.rs
- actors/miner/tests/exported_getters.rs
- actors/miner/tests/util.rs
- actors/multisig/src/lib.rs
- actors/power/Cargo.toml
- actors/power/src/lib.rs
- actors/power/src/state.rs
- actors/power/src/types.rs
- actors/power/tests/harness/mod.rs
- actors/power/tests/power_actor_tests.rs
- actors/verifreg/src/lib.rs
Adds the new power methods proposed [here](https://docs.google.com/spreadsheets/d/1McCcCDHLagBFd5miTcTDBPuTIzmY6uKTxX6SS-xsKVY/edit#gid=0).
> Power actor: Add exported getters for raw power

- actors/market/src/lib.rs
- actors/market/src/state.rs
- actors/market/src/types.rs
- actors/market/tests/deal_api_test.rs
This API is given as a bunch of smaller methods to:
- hide the DealProposal type, so it can change
- increase chance that some parts of this API can be matched by other markets
I haven't thought too deeply about standard deal APIs here, just exposing what we have. We can come and add new methods here to support some better standard in the future.
> Built-in market API for deal proposal metadata

- actors/eam/src/lib.rs
- actors/eam/tests/create.rs
We use the ETH address derived from the user's ID address.
fixes https://github.com/filecoin-project/ref-fvm/issues/1031
> fix: really allow anyone to call EAM::create

- actors/eam/src/lib.rs
Users shouldn't _naturally_ try to create actors with these addresses, but it's not theoretically impossible to _make_ this happen.
> fix: explicitly reject "reserved" eth addresses in the EAM

- actors/evm/src/interpreter/uints.rs
Always encode to a big-endian byte array.
fixes https://github.com/filecoin-project/ref-fvm/issues/912
> fix u256 encoding

- actors/evm/src/interpreter/instructions/storage.rs
- actors/evm/src/interpreter/system.rs
- actors/evm/src/lib.rs
- actors/evm/tests/basic.rs
1. The EVM doesn't distinguish between "exists" and "doesn't exist".
2. There was some interesting dead code.
3. Only mark the state-tree dirty if something has changed.
fixes the second half of https://github.com/filecoin-project/ref-fvm/issues/912
> EVM: simplify and fix evm storage

- actors/evm/src/lib.rs
- actors/evm/tests/call.rs
We only delegate methods >= 1024 to the contract. This is more than sufficient to cover any methods exported by [FRC0042](https://github.com/filecoin-project/FIPs/blob/master/FRCs/frc-0042.md).
part of https://github.com/filecoin-project/ref-fvm/issues/1056
I still haven't restricted _calling_ methods <= 1024, but we can handle that in a followup PR (if we still want to).
> EVM: reserve methods < 1024 for EVM internals

- actors/evm/src/interpreter/precompiles.rs
mainly just assuming that everything is u256 encoded numbers... bleh
> EVM: use more EVM style parameters for FVM syscall precompiles

- actors/market/src/lib.rs
- actors/market/tests/cron_tick_timedout_deals.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/market/tests/publish_storage_deals_failures.rs
- actors/miner/src/lib.rs
- actors/miner/src/state.rs
- actors/miner/tests/miner_actor_test_construction.rs
- actors/miner/tests/miner_actor_test_wpost.rs
- actors/miner/tests/state_harness.rs
- actors/miner/tests/util.rs
- actors/multisig/src/lib.rs
- actors/multisig/tests/multisig_actor_test.rs
- actors/multisig/tests/util.rs
- actors/power/src/lib.rs
- actors/power/tests/harness/mod.rs
- actors/power/tests/power_actor_tests.rs
- runtime/src/builtin/shared.rs
#806 
This PR changes all methods that validated callers were either Account / Multisigs to accepting any callers. This will allow for user-defined actors (eg. other multisigs) to call these methods.
Note that a lot of these methods are not yet exported, but likely will eventually be.
As part of this change, this PR rewires some of the miner actor/state's internal methods to use ActorIDs when referring to owner/worker/control address. This is in line with the enforced requirement today that all such addresses must be resolveable, though it does lead to some excessive type-converting when receiving input params and reading to / writing from state.
> Drop CALLER_TYPES_SIGNABLE and signable caller validation

- actors/market/src/lib.rs
- actors/market/src/types.rs
- actors/market/tests/deal_api_test.rs
> Market actor: Minor improvements to two exported getters

- actors/market/src/lib.rs
- actors/market/src/state.rs
- actors/market/src/types.rs
- actors/market/tests/deal_api_test.rs
- runtime/src/actor_error.rs
A basic API for deal state. This is far from an ideal state API, but works with what the market actor actually knows. There's no information preserved after a deal is cleaned up.
> Exported API for market deal activation state

- Cargo.lock
- Cargo.toml
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/datacap/src/lib.rs
- actors/eam/Cargo.toml
- actors/embryo/Cargo.toml
- actors/evm/Cargo.toml
- actors/evm/src/interpreter/instructions/log.rs
- actors/evm/tests/events.rs
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- runtime/Cargo.toml
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- state/Cargo.toml
- test_vm/Cargo.toml
- test_vm/src/lib.rs
Part of https://github.com/filecoin-project/ref-fvm/issues/1048.
---
* Adds support for `LOG{0..4}` EVM opcodes by emitting actor events.
* Adds a unit test for the above.
Prior to merging:
> EVM runtime: implement LOG{0..4} opcodes by emitting actor events (FIP-0049)

- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/ext.rs
- actors/evm/src/interpreter/instructions/memory.rs
- CALL: truncates the return value, but doesn't zero fill.
- CALLDATA, EXTCODECOPY, CODECOPY: treat input as if it were followed by infinite zeros.
- RETURNDATACOPY: explicitly forbids out-of-bounds reads.
We might be able to change the behavior of EXTCODECOPY and CODECOPY to match RETURNDATACOPY, but we _can't_ change CALLDATA as solidity abuses this feature for zeroing memory. So we're just going to match what the EVM does because it's safer (and because we need to implement that behavior _anyways_ for CALLDATA).
fixes https://github.com/filecoin-project/ref-fvm/issues/1021
fixes https://github.com/filecoin-project/ref-fvm/issues/1024
> fix: correctly handle out-of-bounds cases when copying memory

- Cargo.lock
- actors/paych/Cargo.toml
- actors/paych/src/ext.rs
- actors/paych/src/lib.rs
- actors/paych/src/state.rs
- actors/paych/tests/paych_actor_test.rs
- runtime/src/builtin/shared.rs
Part of #424.
In addition to obviating the need for Paych to/from addresses to be accounts, this also removes the need for them to exist in state at the time of creation -- this PR makes it possible to supply to/from ID addresses that don't actually exist in state at the time of paych creation.
We need to decide if this is something we want, or is undesirable. If the latter, we probably want a new syscall to check for ID addrs existing in state (we could achieve this by misusing existing syscalls, but I would prefer not to).
> Paych actor: Drop account req, use AuthenticateMessage to verify sigs

- actors/evm/src/interpreter/system.rs
- actors/evm/src/lib.rs
- test_vm/tests/evm_test.rs
We can already handle _executing_ with empty bytecode, we just didn't allow construction.
fixes https://github.com/filecoin-project/ref-fvm/issues/960
> fix: allow empty EVM code, init and runtime

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Cargo.toml
- Makefile
- build.rs
- runtime/build.rs
This testnet was created after the last and only release of v8 bundles (v8.0.0), but there's no reason it shouldn't be able to run v8 actors.
> v8: generate bundles for the Wallaby testnet.

- actors/account/src/lib.rs
- actors/account/tests/account_actor_test.rs
Only builtin actors call this method in v9 actors, and in v10 all uses have been updated to call the exported method. We can sunset this method.
> Account actor: Deprecate AuthenticateMessage

- actors/miner/src/lib.rs
- actors/miner/src/types.rs
- actors/miner/tests/change_owner_address_test.rs
- actors/miner/tests/change_peer_id_test.rs
- actors/miner/tests/change_worker_address_test.rs
- actors/miner/tests/confirm_update_worker_key_test.rs
- actors/miner/tests/miner_actor_test_peer_info.rs
- actors/miner/tests/repay_debts.rs
- actors/miner/tests/util.rs
- actors/miner/tests/withdraw_balance.rs
As in the commits:
[Miner: Export ChangeWorkerAddress](https://github.com/filecoin-project/builtin-actors/commit/b945adda81a22aeb56ef8bb2fcafda1e1aa801b3)
[Miner: Export ChangePeerID](https://github.com/filecoin-project/builtin-actors/commit/935c69f4076475cc8b12f2b901e1831c2734ed6e)
[Miner: Export WithdrawBalance](https://github.com/filecoin-project/builtin-actors/commit/4812c4c04dc4af91fcbc87ccf281ebe852eb1afb)
[Miner: Export ChangeMultiaddrs](https://github.com/filecoin-project/builtin-actors/commit/26dd56193d28b06bdfa3b2fd9fca312526d8d38c)
[Miner: Export ConfirmUpdateWorkerKey](https://github.com/filecoin-project/builtin-actors/commit/1d54c88c45a95f7b07b43b91d511c887f71c85f7)
[Miner: Export RepayDebt](https://github.com/filecoin-project/builtin-actors/commit/573f45dcbb92e38942215137dbdb …
> Miner: Export several more methods

- Cargo.lock
- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/precompiles.rs
- actors/evm/src/interpreter/uints.rs
- runtime/Cargo.toml
- runtime/src/runtime/fvm.rs
related: https://github.com/filecoin-project/ref-fvm/issues/1018
closes https://github.com/filecoin-project/ref-fvm/issues/1066
> EVM: Move `CALLACTOR` into a precompile 

- actors/evm/src/interpreter/bytecode.rs
- actors/evm/src/interpreter/execution.rs
- actors/evm/src/interpreter/instructions/arithmetic.rs
- actors/evm/src/interpreter/instructions/bitwise.rs
- actors/evm/src/interpreter/instructions/boolean.rs
- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/context.rs
- actors/evm/src/interpreter/instructions/control.rs
- actors/evm/src/interpreter/instructions/ext.rs
- actors/evm/src/interpreter/instructions/hash.rs
- actors/evm/src/interpreter/instructions/lifecycle.rs
- actors/evm/src/interpreter/instructions/log.rs
- actors/evm/src/interpreter/instructions/memory.rs
- actors/evm/src/interpreter/instructions/mod.rs
- actors/evm/src/interpreter/instructions/stack.rs
- actors/evm/src/interpreter/instructions/state.rs
- actors/evm/src/interpreter/instructions/storage.rs
- actors/evm/src/interpreter/stack.rs
Refactors dispatch logic so that:
- Do stack checks upfront, which allows us to remove bounds checks from stack ops
- Mechanize stack checks according to spec, so that programmer can't mess it up.
- Use a growable stack.
- Uniformize the instruction zoo.
TBD:
> EVM: Refactor Interpreter dispatch

- actors/verifreg/src/lib.rs
- actors/verifreg/src/types.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- test_vm/src/util.rs
- test_vm/tests/publish_deals_test.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
> Verifreg: Export AddVerifiedClient and GetClaims

- actors/evm/src/interpreter/execution.rs
- actors/evm/src/interpreter/instructions/arithmetic.rs
- actors/evm/src/interpreter/instructions/bitwise.rs
- actors/evm/src/interpreter/instructions/mod.rs
Ever so slightly faster (0.5% improvement over next head in simplecoin), but much nicer code.
And if we turn off overflow checks, it's a 3.24% improvement.
> EVM: Further dispatch refactoring

- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- test_vm/src/lib.rs
We exposed this for the GASLIMIT opcode, but didn't actually need it. I'm removing it here to reduce the diff and API surface area.
See https://github.com/filecoin-project/ref-fvm/issues/1168 for context.
> feat: avoid exposing the gas limit in the runtime

- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/ext.rs
- actors/evm/tests/asm.rs
- actors/evm/tests/create.rs
- actors/evm/tests/ext_opcodes.rs
- actors/evm/tests/util.rs
fixes https://github.com/filecoin-project/ref-fvm/issues/1134
> EVM: fix EXTCODE_ ops

- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/precompiles.rs
Unfortunately, this means we need to pass the "system" to the precompiles, which means we need an unsafe dance to pass a mutable pointer through. But it's not _too_ bad.
> fix: save state before callactor

- actors/evm/src/interpreter/execution.rs
This concludes the war on bounds checking:
```
vyzo@carbon6 fvm-bench $ ./target/debug/fvm-bench -b bundles/builtin-actors-next-dd76d3ea.car ../builtin-actors/actors/evm/tests/contracts/SimpleCoin.bin f8b2cb4f 000000000000000000000000ff00000000000000000000000000000000000064
Result: 0000000000000000000000000000000000000000000000000000000000002710
Gas Used: 2233792
vyzo@carbon6 fvm-bench $ cp /home/vyzo/src/fvm/builtin-actors/output/builtin-actors.car bundles/builtin-actors-next-dispatch-tweaks.car
vyzo@carbon6 fvm-bench $ ./target/debug/fvm-bench -b bundles/builtin-actors-next-dispatch-tweaks.car ../builtin-actors/actors/evm/tests/contracts/SimpleCoin.bin f8b2cb4f 000000000000000000000000ff00000000000000000000000000000000000064
Result: …
```
> EVM: further dispatch tweaks

- actors/evm/src/interpreter/execution.rs
- actors/evm/src/interpreter/instructions/control.rs
- actors/evm/src/interpreter/instructions/mod.rs
- avoid the Option and the resulting branches
- skip the noop seld to save a cycle
Results:
- base (68a2b1b4): 2212852
- drop option: 2211804
- skip sled: 2206548
Overall a nice little improvement in our trivial benchmark.
> EVM: rework jump instructions

- actors/evm/src/interpreter/execution.rs
- actors/evm/src/interpreter/instructions/control.rs
- actors/evm/src/interpreter/instructions/lifecycle.rs
- actors/evm/src/interpreter/instructions/mod.rs
- actors/evm/src/interpreter/output.rs
- actors/evm/src/lib.rs
My goal here was simplify the logic around "exiting" so that I could reason about it. Specifically, so I could fix some issues with SELFDESTRUCT. We had multiple error and success paths and that made me nervous.
In the process, I ended up changing a bunch of other things:
1. Exit early by setting the PC.
2. Go back to propagating the error through `step()` (makes things easier to read).
3. Fix some rust unsafety things.
4. Move _all_ of the instruction specific logic into the instruction definitions. This will let us eventually remove one of these tables.
- This means that instructions manage their own PCs.
5. Aggressively inline.
> refactor: rework opcodes definitions and control flow

- actors/evm/src/lib.rs
- actors/evm/tests/revert.rs
This will be _properly_ fixed in https://github.com/filecoin-project/ref-fvm/issues/987, but we need to return proper CBOR till then.
> fix: correctly encode revert data

- actors/evm/src/interpreter/instructions/lifecycle.rs
- actors/evm/tests/selfdestruct.rs
In the EVM:
1. Self destruct continues even if it sends funds into oblivion.
2. Self destruct will auto-create a beneficiary.
This lets us punt https://github.com/filecoin-project/ref-fvm/issues/736 to M2.2.
> fix: handle errors and non-existent addresses in selfdestruct

- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/precompiles.rs
- actors/evm/tests/call.rs
- actors/evm/tests/revert.rs
- runtime/src/actor_error.rs
- runtime/src/runtime/fvm.rs
- runtime/src/test_utils.rs
- test_vm/src/lib.rs
Also, avoid cloning unnecessarily.
> fix: return data from callactor on revert as well

- actors/evm/src/interpreter/instructions/stack.rs
A tiny bit faster in simplecoin, but that doesn't push all that much. I am pretty sure we could demonstrate more significant gains in a push-heavy benchmark.
Closes https://github.com/filecoin-project/ref-fvm/issues/1193
> EVM: optimize push ins for u64 sizes

- actors/datacap/src/lib.rs
- actors/datacap/src/types.rs
- actors/datacap/tests/datacap_actor_test.rs
- actors/datacap/tests/harness/mod.rs
- actors/market/src/ext.rs
- actors/verifreg/src/ext.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/tests/harness/mod.rs
- test_vm/src/util.rs
- test_vm/tests/datacap_tests.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
#808 
- Export the Mint & Destroy methods (restrictions on their caller addresses remain)
- Deprecate all internal methods:
- Built-in actor callsites are updated to use the exported callers
- There are no meaningful external callers of these methods today, so we deprecate them now
- Rename BalanceOf to Balance, to be in line with FRC-0046
- Add Granularity, to be in line with FRC-0046
> Datacap actor: Modify exported methods

- actors/datacap/src/lib.rs
- actors/datacap/src/types.rs
- actors/datacap/tests/datacap_actor_test.rs
- actors/datacap/tests/harness/mod.rs
- actors/init/src/lib.rs
- actors/market/src/ext.rs
- actors/market/src/lib.rs
- actors/market/src/state.rs
- actors/miner/src/lib.rs
- actors/verifreg/src/ext.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/tests/harness/mod.rs
- test_vm/src/util.rs
- test_vm/tests/datacap_tests.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
- `integration/builtin-api` is already on top of `master`
- This PR merges `integration/builtin-api` into `next`
> Merge master and integration/builtin-api into next

- Cargo.lock
- actors/embryo/Cargo.toml
- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/precompiles/evm.rs
- actors/evm/src/interpreter/precompiles/fvm.rs
- actors/evm/src/interpreter/precompiles/mod.rs
- actors/evm/tests/call.rs
- runtime/Cargo.toml
1. Update the FVM's SDK to the version that treats 0 as 0 instead of infinity.
2. Correctly set the gas limit to infinity if we're demoting a call to METHOD_SEND.
3. If the user passes 0 gas in the EVM, leave it at 0 (except when demoting to METHOD_SEND).
Tests:
1. We need integration tests in the FVM (or somewhere, at least).
2. Part of this will be tested in https://github.com/filecoin-project/builtin-actors/pull/923 now that we're actually checking the passed gas limits.
> fix: correctly handle "0" in EVM call gas

- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/lifecycle.rs
- actors/evm/src/interpreter/precompiles/fvm.rs
- actors/evm/src/interpreter/system.rs
- actors/evm/tests/call.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- test_vm/src/lib.rs
This removes the send_read_only variant and makes the simplified `send` variant just call `send_generalized.
> feat: refactor sends to use the unified function

- actors/account/tests/account_actor_test.rs
- actors/init/tests/init_actor_test.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/miner/tests/change_beneficiary_test.rs
- actors/miner/tests/change_owner_address_test.rs
- actors/miner/tests/change_peer_id_test.rs
- actors/miner/tests/change_worker_address_test.rs
- actors/miner/tests/exported_getters.rs
- actors/miner/tests/miner_actor_test_peer_info.rs
- actors/miner/tests/repay_debts.rs
- actors/miner/tests/util.rs
- actors/miner/tests/withdraw_balance.rs
- actors/multisig/tests/multisig_actor_test.rs
- actors/power/tests/power_actor_tests.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- runtime/src/builtin/shared.rs
I'm not thrilled about adding another use of `Type`. I'd like to replace this with explicit "is miner" and "is EVM" methods that should be all we need.
> Runtime: Restrict internal API away from EVM actors

- actors/evm/src/interpreter/instructions/log.rs
As reported by @wadeAlexC, the EVM doesn't allow logs in static mode.
> EVM reverts when logging in static mode

- actors/miner/src/lib.rs
- actors/miner/src/types.rs
- actors/miner/tests/change_owner_address_test.rs
As in the title.
We might want to add analogous methods for pending workers and beneficiaries, but I'd like to hear motivation for them first.
> Miner: Export method to GetPendingOwner

- actors/account/src/types.rs
- actors/datacap/src/types.rs
- actors/init/src/types.rs
- actors/market/src/types.rs
- actors/miner/src/types.rs
- actors/miner/tests/util.rs
- actors/multisig/src/types.rs
- actors/power/src/types.rs
- actors/verifreg/src/types.rs
- test_vm/src/lib.rs
- test_vm/src/util.rs
- test_vm/tests/account_authenticate_message_test.rs
- test_vm/tests/batch_onboarding.rs
- test_vm/tests/change_beneficiary_test.rs
- test_vm/tests/change_owner_test.rs
- test_vm/tests/commit_post_test.rs
- test_vm/tests/datacap_tests.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/market_miner_withdrawal_test.rs
- test_vm/tests/multisig_test.rs
- test_vm/tests/power_scenario_tests.rs
- test_vm/tests/publish_deals_test.rs
- test_vm/tests/replica_update_test.rs
- test_vm/tests/terminate_test.rs
- test_vm/tests/test_vm_test.rs
- test_vm/tests/verified_claim_test.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
- test_vm/tests/withdraw_balance_test.rs
Fixes #700 
- Changes the test_vm's apply methods to take an `Option<serde::Serialize>` as params. `None` is serialized as `RawBytes::default()`, `Some(p)` is serialized as CBOR.
- Drop the `impl Cbor` for all method params & returns types.
> Drop Cbor from method params and return types

- actors/market/src/ext.rs
- actors/market/src/lib.rs
- actors/market/src/types.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/market/tests/publish_storage_deals_failures.rs
- runtime/src/test_utils.rs
- test_vm/src/util.rs
Reopening #894 on correct branch
> MarketNotifyDeal

- actors/market/src/ext.rs
- actors/market/src/lib.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/src/types.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- test_vm/src/util.rs
- test_vm/tests/datacap_tests.rs
Changes:
- Verifreg AllocationRequest to use ActorID
- Verifreg ClaimExtensionRequest to use ActorID
- [Remove unused fn resolve_miner_id](https://github.com/filecoin-project/builtin-actors/commit/98bce0813cfdbcb5b63b72e78e58b56508269e0c)
- [Fix receive_alloc_requires_miner_actor test](https://github.com/filecoin-project/builtin-actors/commit/a7b0013bd340dc22029754faad92814949aa7527)
Closes #869
> Verifreg to use ActorID

- runtime/src/test_utils.rs
Otherwise, we'll just panic twice and abort.
> fix: don't verify mock runtime when already panicing

- actors/init/src/lib.rs
- actors/init/src/state.rs
- test_vm/src/lib.rs
Removes most duplication, and clarifies the logic a bit.
> Consolidate Init actor address mapping code

- actors/init/src/lib.rs
- actors/init/src/state.rs
- actors/init/tests/init_actor_test.rs
- runtime/src/test_utils.rs
- test_vm/src/lib.rs
We could also reject this in the FVM, but then we'd have to tell the FVM that we're re-assigning an existing ID address.
The downside of this method is that it's _slightly_ more expensive (we have to make multiple syscalls instead of one).
The benefit is that it makes auditing and testing this code _much_ simpler. Before, we were enforcing half the constraints in the FVM, and the other half in the init actor, which is why we had into this bug in the first place.
fixes https://github.com/filecoin-project/ref-fvm/issues/1175
> fix: reject (f4) actor redeploy after selfdestruct

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/runtime/policy.rs
The deserialization of a serialized Policy doesn't work with TOML and JSON. I assume the `fvm_shared::bigint::bigint_ser;` is supposed to be used for binary formats only. See more [here](https://github.com/ChainSafe/fil-actor-states/issues/2).
Given that [it was me](https://github.com/filecoin-project/builtin-actors/commit/7a65393774aea71f9b3cd19c240bc71623ea5a07) who introduced Serialization for this, I believe only Forest wants to use this feature for now so most likely nobody relies on it, especially the network.
> use universal (de)serializer for Policy

- actors/eam/src/lib.rs
- actors/eam/tests/create.rs
- actors/evm/src/lib.rs
- actors/evm/tests/env.rs
- actors/evm/tests/util.rs
Changes constructor caller checks to use singleton identity checks rather than actor type checks; this is towards our general goal of removing the use of `Type` from the built-in actors altogether.
Fixes EAM singleton to check its caller is the System actor, consistent with all other built-in actors. This actor is not constructed via `Init::Exec`.
> Fix caller check in EVM/EAM constructors

- actors/verifreg/src/ext.rs
- actors/verifreg/src/lib.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
Fixes #922 
- Call `AuthenticateMessageExported`
- "pop" proposals before verifying them: That way, any re-entrant funny-business can't cause any issues.
> Verifreg: Call AuthenticateMessage instead of validating siggys

- actors/multisig/src/lib.rs
- actors/multisig/tests/multisig_actor_test.rs
> Multisig: Do not export any functionality

- actors/evm/src/interpreter/precompiles/fvm.rs
- actors/evm/tests/call.rs
closes https://github.com/filecoin-project/ref-fvm/issues/1232
> EVM: Re-order address and data size params of call_actor precompile

- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/ext.rs
We are in desperate need of integration tests here. Not that it would've helped in this particular case, though.
The impact of this bug is that contracts cannot send value to accounts.
> fix: EVM: CALLs to EthAccount should be lowered to bare transfers.

- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/ext.rs
- actors/evm/src/lib.rs
- actors/evm/tests/delegate_call.rs
- actors/evm/tests/ext_opcodes.rs
- actors/evm/tests/util.rs
This is needed since ext* opcodes can/will be called during initcode.
Calling ext* on self during initcode must have _some_ state flushed, system.send will flush empty bytecode hashes to state before send for us so get_bytecode and code hash work properly then.
This _could_ be potentially unexpected behavior depending on what EVM does for these opcodes during initcode, since it may consider self as non-existent and return zeros. This also introduces the idea that self "exists" during initcode despite the potential for the constructor to fail and not _actually_ exist.
**Note:** This PR changes Ext opcodes to use readonly sends since those methods we call in them should never change state.
> EVM: Flush state before calling send in Ext opcodes 

- actors/evm/src/interpreter/precompiles/mod.rs
fixes https://github.com/filecoin-project/ref-fvm/issues/1389
> EVM: Check that precompile address index is within bounds

- actors/evm/src/interpreter/precompiles/fvm.rs
- actors/evm/src/interpreter/precompiles/parameter.rs
- actors/evm/tests/precompile.rs
- actors/evm/tests/util.rs
Adds a test for lookup_address, and assert_zero_bytes.
tests in https://github.com/filecoin-project/builtin-actors/pull/977 was originally part of this PR but split out to get it merged before carbonado.r1 
fixes [#1390](https://github.com/filecoin-project/ref-fvm/issues/1390)
> EVM: test lookup_address

- Cargo.lock
- actors/eam/src/ext.rs
- actors/evm/Cargo.toml
- actors/evm/src/lib.rs
This also re-numbers all the other method numbers, because we're removing method 2. This is going to be annoying... but it's better to do this now than to have a dead method.
fixes https://github.com/filecoin-project/ref-fvm/issues/1256
> EVM: use FRC-0042 for invoke

- test_vm/tests/evm_test.rs
Closes https://github.com/filecoin-project/ref-fvm/issues/1190
> EVM: add integration test for eam/init revert data propagation.

- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
I couldn't get logging to result in a syscall with the SDK (even with local patch to include https://github.com/filecoin-project/ref-fvm/pull/1431)
This brings log initialisation for the builtin actors into their repo, which I think is entirely appropriate anyway. And I can verify that logging produces a syscall.
> Implement log initialisation inline in FVM runtime

- actors/evm/src/interpreter/precompiles/evm.rs
- actors/evm/src/interpreter/precompiles/fvm.rs
- actors/evm/src/interpreter/precompiles/parameter.rs
Renamed the padding function for better clarity on it's function to hopefully avoid issue fixed in #1016 in the future. I also double checked its uses to ensure this mistake was unique.
> EVM: Rename read right pad for clarity

- actors/evm/src/interpreter/precompiles/fvm.rs
- actors/evm/tests/precompile.rs
This will log a more helpful reason than just empty vec. also add some logging. Split out from #1016 but not dependent on it.
This also caught that one of the failure tests was not failing with what it said it was. That is also fixed in this.
> EVM: Fix resolve address errors

- Cargo.lock
- actors/account/Cargo.toml
- actors/init/Cargo.toml
- actors/miner/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
This should be what's being used anyway because of the git patch, but we might as well bump it now. It makes some cargo patch funkiness go away on some FVM work I'm doing.
> Bump FRC42_dispatch to 3.0.0

- actors/evm/src/interpreter/precompiles/fvm.rs
return failure instead of empty success on invalid input. This doesn't require test changes because the current tests dont check for exit value, fixed in https://github.com/filecoin-project/builtin-actors/pull/1033 .
> EVM: precompile actor_type error

- Cargo.lock
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/datacap/src/lib.rs
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/evm/src/interpreter/system.rs
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/placeholder/Cargo.toml
- actors/power/Cargo.toml
- actors/power/tests/power_actor_tests.rs
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- runtime/Cargo.toml
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- state/Cargo.toml
- test_vm/Cargo.toml
- test_vm/src/lib.rs
https://github.com/filecoin-project/ref-fvm/issues/1020
Open questions:
- @Stebalien is in favour of making this change, so gonna do that.
> Runtime: Don't convert syscall errors

- actors/evm/src/interpreter/precompiles/evm.rs
- actors/evm/src/interpreter/precompiles/fvm.rs
- actors/evm/src/interpreter/precompiles/parameter.rs
- actors/evm/tests/call.rs
This patch:
1. Refactors the parameter reader to be less generic and easier to understand.
2. Refactors parameter reading to always use the reader (letting it take care of things like padding).
3. Adds a bunch of parameter reading tests.
> feat: refactor precompile parameter reading

- actors/evm/src/interpreter/execution.rs
- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/mod.rs
It was never implemented and is deprecated. This will now just be treated as an invalid instruction.
fixes https://github.com/filecoin-project/ref-fvm/issues/870
> fix: remove CallCode

- Cargo.lock
- actors/eam/src/ext.rs
- actors/eam/src/lib.rs
- actors/eam/tests/create.rs
- runtime/src/test_utils.rs
- test_vm/Cargo.toml
- test_vm/src/lib.rs
- test_vm/tests/evm_test.rs
See https://github.com/filecoin-project/ref-fvm/issues/1434
These are the core code changes; once we are happy with them I'll have to fix the tests and replace all create invocations with create_external in lotus side.
> refactor EAM interface

- actors/evm/src/interpreter/address.rs
- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/ext.rs
- actors/evm/src/interpreter/precompiles/mod.rs
- actors/evm/src/interpreter/uints.rs
This:
- Checks if address is in reserved precompile range, _then_ will try to resolve the exact one, otherwise return fail and no return value
- No longer panics in call/staticcall if precompile was found, instead return an ActorError
- Documents behavior of get_contract_type (used by delagatecall) if precompile address is not a valid precompile, but still within precompile range.
> EVM:  dont panic on invalid precompile address

- actors/evm/src/interpreter/system.rs
- runtime/src/actor_error.rs
- runtime/src/runtime/mod.rs
This commit:
1. Extracts the actor code checking to methods on the ActorError itself.
2. Uses them in the EVM.
> fix: check actor error codes

- actors/evm/src/interpreter/address.rs
- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/ext.rs
- actors/evm/src/interpreter/precompiles/mod.rs
This mostly just reduces conversions, but also makes some types a bit more obvious.
> fix: use EthAddress in more places

- actors/evm/tests/precompile.rs
This should make precompile tests easier to write, more comprehensive, and easier to understand
> EVM: Precompile test framework

- actors/eam/src/lib.rs
If we try to exit with a system exit code, we'll get the wrong exit code.
> fix: check for system errors in the eam

- actors/evm/src/interpreter/precompiles/fvm.rs
- actors/evm/src/interpreter/precompiles/mod.rs
- actors/evm/src/interpreter/precompiles/parameter.rs
- actors/evm/tests/call.rs
- actors/evm/tests/precompile.rs
1. Remove the `length` from `resolve_address` (just take bytes).
2. Fix `call_actor` to follow the solidity conventions with respect to offsets and lengths.
3. Add a new `call_actor_id` that takes an ID instead of an address.
> EVM: Refactor FVM precompiles

- actors/evm/src/interpreter/precompiles/evm.rs
- actors/evm/src/interpreter/precompiles/fvm.rs
- actors/evm/src/interpreter/precompiles/mod.rs
- actors/evm/src/lib.rs
- actors/evm/src/reader.rs
Basically, just make it non-precompile specific.
> EVM: move parameter reader so we can use it everywhere

- Cargo.lock
- actors/datacap/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/verifreg/Cargo.toml
- runtime/Cargo.toml
- test_vm/Cargo.toml
Replaces #1020. This change avoids flushing unless modified.
> chore: update hamt & amt

- actors/eam/src/lib.rs
- actors/eam/tests/create.rs
- actors/evm/tests/util.rs
Fixes https://github.com/filecoin-project/ref-fvm/issues/1480
> Fix: EAM: Successfully create actors over placeholders

- actors/eam/src/lib.rs
Now that we have this information, we may as well use it.
> fix: return early when trying to deploy over an existing contract

- actors/evm/tests/precompile.rs
Isn't an issue now, but this will error once we upgrade to >1.65.0 (and I want to use nightly for miri atm)
> EVM: derive copy for precompile enum in tests 

- actors/verifreg/src/lib.rs
- actors/verifreg/src/state.rs
This saves 464k gas (4.9%) on a simple transfer making a single allocation an no claims (or vice versa), on an otherwise empty state.
Progress on #1020
> Avoid redundant read/write of allocation/claims HAMT root when unchanged

- actors/evm/src/interpreter/precompiles/fvm.rs
- actors/evm/src/interpreter/precompiles/mod.rs
- actors/evm/tests/precompile.rs
also removes the unsafe we had laying around :)
unfortunately this will add a _small_ runtime cost on first call to a precompile every time an actor is initialized, but its a simple array init of fn pointers. `mem::size_of` said the evm precompile table is currently 72 bytes - which is really nothing compared to the 32 byte words we are tossing around.
> EVM: Remove get_actor_type and allow precompile lookup table to have empty slots

- actors/evm/src/interpreter/execution.rs
- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/context.rs
- actors/evm/src/interpreter/instructions/control.rs
- actors/evm/src/interpreter/instructions/ext.rs
- actors/evm/src/interpreter/instructions/hash.rs
- actors/evm/src/interpreter/instructions/lifecycle.rs
- actors/evm/src/interpreter/instructions/log_event.rs
- actors/evm/src/interpreter/instructions/memory.rs
- actors/evm/src/interpreter/instructions/mod.rs
- actors/evm/src/interpreter/instructions/stack.rs
- actors/evm/src/interpreter/instructions/state.rs
- actors/evm/src/interpreter/instructions/storage.rs
- actors/evm/src/interpreter/mod.rs
- actors/evm/src/interpreter/output.rs
- actors/evm/src/interpreter/stack.rs
- actors/evm/src/interpreter/system.rs
- actors/evm/src/lib.rs
- runtime/src/actor_error.rs
Remove "StatusCode" as we were just turning those into actor errors anyways. Instead, we return meaningful exit codes:
- 34: Invalid Instruction (assert)
- 35: Undefined Instruction (bad instruction)
- 36: Stack Underflow
- 37: Stack Underflow
- 38: Illegal Memory Access
- 39: Bad Jump Destination
This change also ensures that meaningful error messages get sent through the FVM (although they're not committed on-chain).
fixes #1195
> EVM: Remove StatusCode and return meaningful actor errors

- actors/account/src/lib.rs
- actors/cron/src/lib.rs
- actors/datacap/src/lib.rs
- actors/init/src/lib.rs
- actors/market/src/lib.rs
- actors/miner/src/lib.rs
- actors/multisig/src/lib.rs
- actors/paych/src/lib.rs
- actors/power/src/lib.rs
- actors/reward/src/lib.rs
- actors/system/src/lib.rs
- actors/verifreg/src/lib.rs
- runtime/src/dispatch.rs
1. Use absolute paths so we don't have to import things everywhere.
2. Support dispatch fallbacks (`_`).
3. Support dispatching to methods without decoding/encoding (`[raw]`).
> feat: improve dispatch macro

- actors/account/src/lib.rs
- actors/account/tests/account_actor_test.rs
- actors/ethaccount/src/lib.rs
- actors/ethaccount/tests/ethaccount_test.rs
This patch implements a "raw" fallback for both account types that simply accepts all methods greater than or equal to the min FRC0042 number.
Alternative to #1081
Fixes https://github.com/filecoin-project/builtin-actors/pull/1076
> feat: allow all unrestricted method numbers on accounts

- runtime/src/actor_error.rs
- runtime/src/runtime/fvm.rs
Extracted from the next branch.
Currently unused, but can be used to carry (optional) return data using the FVM3 SDK's exit method.
> feat: allow ActorErrors to carry optional data

- actors/market/src/ext.rs
- actors/market/src/lib.rs
- actors/market/tests/cron_tick_timedout_deals.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/market/tests/publish_storage_deals_failures.rs
- test_vm/src/util.rs
- test_vm/tests/publish_deals_test.rs
Replace existing control address accessor with new `is_controlling_address`
Closes #816
> Use is_controlling_address in actors

- actors/evm/tests/call.rs
- actors/evm/tests/delegate_call.rs
- actors/evm/tests/ext_opcodes.rs
- runtime/src/test_utils.rs
continuation of https://github.com/filecoin-project/builtin-actors/pull/1097 to add tests, adds send error to MockRuntime expectations.
> EVM: test send error changes

- Cargo.lock
- Cargo.toml
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/datacap/src/lib.rs
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/miner/src/state.rs
- actors/miner/src/types.rs
- actors/multisig/Cargo.toml
- actors/multisig/tests/multisig_actor_test.rs
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/power/src/types.rs
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- runtime/Cargo.toml
- runtime/src/actor_error.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/hash_algorithm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- state/Cargo.toml
- test_vm/Cargo.toml
- test_vm/src/lib.rs
This is a pre-factor that updates this repo to rely on FVM3 deps, without introducing or supporting any FEVM functionality. The new crates themselves do include some FEVM changes:
- hyperspace support (I'm hoping this is okay, it's just a testnet)
- The f4 address scheme, which is in FIP-0048, which has been Accepted as of today
Most of the changes here result from integrating the latest changes in the https://github.com/helix-onchain/filecoin repo.
Needs:
> Update to FVM SDK 3.0.0-alpha.22, shared 3.0.0-alpha.17, ipld_encoding 0.3.3

- actors/evm/src/interpreter/instructions/lifecycle.rs
- actors/evm/src/lib.rs
- actors/evm/tests/selfdestruct.rs
This is somewhat of a damned if we do, damned if we don't situation. This operation _can't_ fail in the EVM, but it _can_ fail in the FVM because we implement this with an actual send.
However, this is far from the only instruction that can fail unexpectedly (e.g., EXTCODEHASH).
🤷‍♂️
fixes https://github.com/filecoin-project/ref-fvm/issues/1558
> EVM: abort if we fail to transfer to the beneficiary on selfdestruct

- actors/placeholder/src/lib.rs
This is simply changes placeholders from rejecting all calls to accepting them.
Pairs with https://github.com/filecoin-project/ref-fvm/pull/1568
Part of https://github.com/filecoin-project/ref-fvm/issues/1567
> feat: accept all methods in the placeholder

- Cargo.lock
- actors/placeholder/Cargo.toml
> placeholder: drop deps on FVM SDK and shared

- actors/evm/src/interpreter/instructions/control.rs
- actors/evm/src/interpreter/test_util.rs
There are way to many refrences inside structs to be able to construct this manually (without some nasty hacks), so instead I've just cleaned up the types that had duplicate fields already accessable or not owned.
> Evm unittest fixes

- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/tests/call.rs
1. Turn solidity "transfers" into full calls, but only grant them 10M gas.
2. Remove a lot of special casing.
A simple alternative to https://github.com/filecoin-project/builtin-actors/pull/1113.
> EVM: simplify call logic and CALL on transfer

- actors/evm/src/interpreter/execution.rs
- actors/evm/src/interpreter/instructions/control.rs
- actors/evm/src/interpreter/mod.rs
- actors/evm/src/interpreter/system.rs
- actors/evm/src/interpreter/test_util.rs
Unit Test Macro and a bunch of Unit Tests
- Closes https://github.com/filecoin-project/ref-fvm/issues/1544
- Closes https://github.com/filecoin-project/ref-fvm/issues/1545
- Closes https://github.com/filecoin-project/ref-fvm/issues/1546
> EVM: unit tests: Control Flow, Call Context, Call

- Cargo.lock
- Cargo.toml
- actors/init/src/lib.rs
- actors/init/src/state.rs
- actors/init/tests/init_actor_test.rs
- actors/placeholder/Cargo.toml
- actors/placeholder/src/lib.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- state/src/check.rs
- test_vm/src/lib.rs
- test_vm/tests/test_vm_test.rs
This is a partial implementation of [FIP-0048](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0048.md). This PR:
- updates to the new `Actor` object, that includes an Optional field for Predictable addresses
- introduces the new `Placeholder` actor that has no state and accepts all calls 
- updates the init actor to store f4 addresses in its map
- adds a new `lookup_delegated_address` syscall to retrieve an actor's f4 address
It does NOT introduce the new Exec4 method specified in FIP-0048, as that method requires implementation of the Ethereum Address Manager actor. That will be included in a future PR.
> feat: Partial implementation of FIP-0048 (f4/delegated addresses)

- actors/evm/src/interpreter/instructions/memory.rs
- actors/evm/src/interpreter/memory.rs
- actors/evm/src/lib.rs
do alignment inside the function, and no-op if new_size would shrink memory.
> EVM: Fix `Memory::grow`

- actors/cron/src/lib.rs
- actors/datacap/src/lib.rs
- actors/init/src/lib.rs
- actors/market/src/lib.rs
- actors/miner/src/lib.rs
- actors/multisig/src/lib.rs
- actors/paych/src/lib.rs
- actors/power/src/lib.rs
- actors/power/tests/power_actor_tests.rs
- actors/reward/src/lib.rs
- actors/verifreg/src/lib.rs
- runtime/src/builtin/shared.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- test_vm/src/lib.rs
Extracted from `next`. Needs:
This PR adds a new `send_generalized` method to the `Runtime`. The key differences between `send` and `send_generalized` are that:
- `send_generalized` can take an optional `gas_limit` that restricts the total gas usage of the send
- `send_generalized` can carry optional `SendFlags` -- currently the only `SendFlag` the FVM supports is `READ_ONLY`
- `send_generalized` segregates failures arising from the syscall prior to target invocation (returned as an `ErrorNumber`) and those arising from the invocation itself (returned as an `ExitCode`).
This PR is a pre-factor necessary for landing the changes involved in the FEVM FIPs -- it introduces new functionality, but doesn't start to _use_ it anywhere.
> feat: runtime: Add send_generalized

- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- test_vm/src/lib.rs
Extracted from `next`.  Needs:
This PR simply introduces a getter to the `Runtime` to indicate whether an invocation is in `READ_ONLY` mode, and updates the test framework to consider this status as part of execution.
This PR is a pre-factor necessary for landing the changes involved in the FEVM FIPs -- it introduces new functionality, but doesn't start to _use_ it anywhere.
> feat: runtime: Add read_only getter

- runtime/src/actor_error.rs
- runtime/src/builtin/shared.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- test_vm/src/lib.rs
This way the user can directly bubble the send error with the `?` operator.
Unfortunately, I couldn't simplify `extract_send_result` because `Response` isn't implemented in this crate and `ActorError` is, so there's no way to implement `From<Response>` for `Result<T, ActorError>`.
> Introduce a SendError

- runtime/src/builtin/shared.rs
Needed for the `AsActorError` impl of `Result<T, E>`
> Runtime: Impl Display for SendError

- actors/evm/src/interpreter/instructions/control.rs
- actors/evm/src/interpreter/instructions/hash.rs
- actors/evm/src/interpreter/instructions/memory.rs
- actors/evm/src/interpreter/instructions/state.rs
- actors/evm/src/interpreter/test_util.rs
For https://github.com/filecoin-project/builtin-actors/pull/1144#pullrequestreview-1279767582 which makes two aesthetic crimes when it comes to DSLology: the embeded code for both constructs is interpretable garbage.
So:
`(rt: blah ...}` is `(rt) {blah ...}` which is optional and has nice block semantics.
and
`(m) [ blah...]` is `(m) {blah....}` again, since it doesn't have array semantcs.
I haz strong opinions when it comes to macro DSLs :)
> Fix macro DSL

- Cargo.lock
- actors/miner/tests/miner_actor_test_construction.rs
- actors/miner/tests/util.rs
- runtime/Cargo.toml
- runtime/src/actor_error.rs
- runtime/src/runtime/builtins.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- state/src/check.rs
- test_vm/src/lib.rs
This PR adds the following methods to the Runtime interface:
- `actor_balance`
- `gas_available`
- `tipset_timestamp`
- `tipset_cid`
- `hash`
- `hash_64`
- `recover_secp_public_key`
Note: This isn't the most cohesive PR, sorry :')
> Runtime: Add several new methods

- actors/miner/src/lib.rs
- actors/verifreg/src/lib.rs
There weren't any _actual_  state changes, but transactions cannot succeed in read-only mode at all.
> fix: miner and verifreg: make getters read-only

- actors/market/src/lib.rs
Perhaps the `DAG_CBOR` constant was not available then, but now it is.
> re-use DAG_CBOR

- actors/init/src/lib.rs
- actors/init/src/testing.rs
- actors/init/src/types.rs
- actors/init/tests/init_actor_test.rs
This PR adds the `Exec4` method described in FIP-0048, along with unit tests.
A later PR must restrict this new method to only being called by the future EAM Actor.
> feat: init actor: Add Exec4 method

- Cargo.lock
- Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/ethaccount/src/lib.rs
- actors/ethaccount/src/types.rs
- actors/ethaccount/tests/authenticate_message.rs
- actors/ethaccount/tests/ethaccount_test.rs
- actors/ethaccount/tests/util.rs
- runtime/src/builtin/singletons.rs
Implements the EthAccount actor, as defined in [FIP-0055](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0055.md). This PR does NOT introduce the Ethereum Address Manager actor described in FIP-0055, but makes reference to the ID address it will receive (10).
> FIP-0055: Introduce the EthAccount actor

- actors/evm/src/interpreter/instructions/log_event.rs
- actors/evm/src/interpreter/instructions/storage.rs
- actors/evm/src/interpreter/test_util.rs
- Closes https://github.com/filecoin-project/ref-fvm/issues/1548
- Closes https://github.com/filecoin-project/ref-fvm/issues/1551
> EVM: more unit tests

- Cargo.lock
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/evm/shared/Cargo.toml
- actors/evm/src/interpreter/instructions/log_event.rs
- actors/evm/tests/events.rs
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- runtime/Cargo.toml
- state/Cargo.toml
- test_vm/Cargo.toml
Unlike the previous version, this one _does not_ strip leading zeros from keys. We could, but:
1. It's easier not to.
2. It shouldn't make a difference in practice as keys are _usually_ hashes (i.e., random).
> feat: update fvm and switch to the new event structure

- Cargo.lock
- actors/evm/Cargo.toml
- actors/evm/src/interpreter/execution.rs
- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/control.rs
- actors/evm/src/interpreter/instructions/lifecycle.rs
- actors/evm/src/interpreter/memory.rs
- actors/evm/src/interpreter/output.rs
- actors/evm/src/interpreter/test_util.rs
- actors/evm/src/lib.rs
This was probably intended to reduce copying between EVM contracts, but it makes no difference for us beyond introducing strange types.
> EVM: remove Bytes

- Cargo.lock
- actors/evm/Cargo.toml
- actors/evm/src/interpreter/memory.rs
- actors/evm/src/interpreter/system.rs
- Remove OnceCell and replace it with an Option.
- Move lazy_static to the dev dependencies.
- Manually implement deref instead of importing a crate just for that.
- Remove a bunch of unused dependencies.
> EVM: remove a few more deps

- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- test_vm/src/lib.rs
I love negative lines of code.
> runtime: drop unused exit()

- Cargo.lock
- actors/eam/Cargo.toml
- actors/eam/src/ext.rs
- actors/eam/src/lib.rs
- actors/eam/tests/create.rs
- actors/evm/Cargo.toml
- actors/evm/src/lib.rs
- actors/evm/src/types.rs
Needs:
This PR introduces the EAM actor, as specified in FIP-0055: https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0055.md#ethereum-address-manager-eam.
> FIP-0055: Introduce the EAM actor

- actors/init/src/lib.rs
- actors/init/tests/init_actor_test.rs
An update from https://github.com/filecoin-project/FIPs/pull/616
> FIP-0050: Init actor: Do not export the Exec method

- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/instructions/ext.rs
Closes https://github.com/filecoin-project/ref-fvm/issues/1552
> EVM: Code tests

- actors/evm/src/interpreter/instructions/context.rs
On top of https://github.com/filecoin-project/builtin-actors/pull/1181
Closes https://github.com/filecoin-project/ref-fvm/issues/1555
> EVM: Context tests

- actors/evm/src/interpreter/instructions/lifecycle.rs
- actors/evm/src/interpreter/system.rs
Closes https://github.com/filecoin-project/ref-fvm/issues/1547
> EVM: lifecycle tests

- actors/miner/src/deadline_state.rs
- actors/miner/src/expiration_queue.rs
- actors/miner/src/lib.rs
- actors/miner/src/partition_state.rs
- actors/miner/src/types.rs
- actors/miner/tests/deadline_cron.rs
- actors/miner/tests/declare_faults.rs
- actors/miner/tests/declare_recoveries.rs
- actors/miner/tests/extend_sector_expiration_test.rs
- actors/miner/tests/util.rs
- runtime/src/test_utils.rs
Adding proper tests to the new proof extension mechanism.  
Proof expiration tests
This required addressing fairly involved technical debt in miner actor test harness.  Less direct changes to testing:
I'm also using this PR to address 3 fixes I deferred for expediency when merging the original branch here.
> Test and fix fip 47 implementation

- actors/evm/src/interpreter/instructions/memory.rs
Closes https://github.com/filecoin-project/ref-fvm/issues/1650
> EVM: memory read tests

- Cargo.lock
- actors/evm/Cargo.toml
- actors/evm/src/interpreter/precompiles/blake2f_impl.rs
- actors/evm/src/interpreter/precompiles/evm.rs
- actors/evm/src/interpreter/precompiles/mod.rs
That way, we:
1. Don't depend on a fork of an unmaintained library.
2. Use a much simpler blake2f implementation.
> EVM: use blake2f from parity's frontier

- actors/miner/src/lib.rs
Today if market cron freezes over in case of programmer error then any miner actors making use of cron to terminate sectors will also freeze.   We should prefer to not do this to make frozen cron easier to recover and less disruptive.  We don't gain much from this.  Any recovery of frozen cron is going to need a migration and that migration should be able to filter out deals that have terminated since market cron froze.  Frozen cron from programmer error isn't esoteric: this is exactly the cause of calibration reset last year.  With FVM approaching and new classes of exploits becoming possible it makes sense to do this hardening.
> Swallow deal termination error in cron

- actors/evm/src/interpreter/precompiles/fvm.rs
- actors/evm/src/lib.rs
We've decided that it's more important that hyperspace match mainnet.
> fix: remove hyperspace-specific hacks

- actors/evm/Makefile
see https://github.com/filecoin-project/ref-fvm/issues/1252
```
vyzo@carbon6 evm $ make tests/contracts/callvariants.hex
make: 'tests/contracts/callvariants.hex' is up to date.
vyzo@carbon6 evm $ touch tests/contracts/callvariants.eas 
vyzo@carbon6 evm $ make tests/contracts/callvariants.hex
eas tests/contracts/callvariants.eas | tr -d '\n' > tests/contracts/callvariants.hex
vyzo@carbon6 evm $ touch tests/contracts/callvariants_body.eas 
vyzo@carbon6 evm $ make tests/contracts/callvariants.hex
eas tests/contracts/callvariants.eas | tr -d '\n' > tests/contracts/callvariants.hex
vyzo@carbon6 evm $ make tests/contracts/callvariants.hex
make: 'tests/contracts/callvariants.hex' is up to date.
```
> chore: EVM tests: add callvariants build rule to Makefile

- .gitignore
- actors/account/src/lib.rs
- actors/account/src/types.rs
- actors/datacap/src/lib.rs
- actors/datacap/src/types.rs
- actors/evm/src/lib.rs
- actors/evm/src/types.rs
- actors/market/src/lib.rs
- actors/market/src/types.rs
- actors/miner/src/lib.rs
- actors/miner/src/types.rs
- actors/power/src/lib.rs
- actors/power/src/types.rs
- actors/reward/src/lib.rs
- actors/reward/src/types.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/src/types.rs
https://github.com/filecoin-project/builtin-actors/issues/817
> Add types for one-value params and returns

- Cargo.lock
- Cargo.toml
- actors/miner/src/lib.rs
- actors/miner/src/policy.rs
- runtime/src/runtime/policy.rs
Relies on https://github.com/filecoin-project/ref-fvm/pull/1713 to impl Ord so that the registered proofs can be stored in a BTreeSet
Requires https://github.com/filecoin-project/builtin-actors/pull/1244 so that the Helix library deps pull the same version of fvm_shared etc.
Closes https://github.com/filecoin-project/builtin-actors/issues/97
> Remove HashSet from policy

- actors/evm/src/lib.rs
- actors/evm/src/types.rs
- runtime/src/dispatch.rs
- runtime/src/lib.rs
This adds a new "dispatch default" feature to the method dispatch macro. This will automatically provide the "default" parameters to the method if none were passed in the message.
fixes https://github.com/filecoin-project/builtin-actors/issues/966
> fix: use the method dispatch macro in the EVM

- test_vm/src/lib.rs
- test_vm/src/util.rs
- test_vm/tests/authenticate_message_test.rs
- test_vm/tests/batch_onboarding.rs
- test_vm/tests/change_beneficiary_test.rs
- test_vm/tests/change_owner_test.rs
- test_vm/tests/commit_post_test.rs
- test_vm/tests/datacap_tests.rs
- test_vm/tests/evm_test.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/init_test.rs
- test_vm/tests/market_miner_withdrawal_test.rs
- test_vm/tests/multisig_test.rs
- test_vm/tests/power_scenario_tests.rs
- test_vm/tests/publish_deals_test.rs
- test_vm/tests/replica_update_test.rs
- test_vm/tests/terminate_test.rs
- test_vm/tests/test_vm_test.rs
- test_vm/tests/verified_claim_test.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
- test_vm/tests/withdraw_balance_test.rs
This rename frees up `VM` to be the name of the abstract trait that the tests will be injected with.
Step 0 for https://github.com/filecoin-project/builtin-actors/issues/1236
> rename test_vm::VM to test_vm::TestVM

- actors/market/src/testing.rs
- actors/market/tests/market_actor_test.rs
- actors/miner/tests/sectors.rs
- actors/miner/tests/util.rs
- state/src/check.rs
- test_vm/src/lib.rs
- test_vm/src/util.rs
- test_vm/tests/authenticate_message_test.rs
- test_vm/tests/batch_onboarding.rs
- test_vm/tests/change_beneficiary_test.rs
- test_vm/tests/change_owner_test.rs
- test_vm/tests/commit_post_test.rs
- test_vm/tests/datacap_tests.rs
- test_vm/tests/evm_test.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/init_test.rs
- test_vm/tests/market_miner_withdrawal_test.rs
- test_vm/tests/multisig_test.rs
- test_vm/tests/power_scenario_tests.rs
- test_vm/tests/publish_deals_test.rs
- test_vm/tests/replica_update_test.rs
- test_vm/tests/terminate_test.rs
- test_vm/tests/test_vm_test.rs
- test_vm/tests/verified_claim_test.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
- test_vm/tests/withdraw_balance_test.rs
Further groundwork for an abstract VM trait. Especially in the context of benchmarking it may be useful to inject TrackingBlockstores etc. in future. 
The current TestVM could not implement a method that returns a BS: Blockstore which would be required by a generic VM<BS: Blockstore> trait.
> replace concrete blockstore in TestVM with a generic trait

- Cargo.toml
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- state/Cargo.toml
- The v2 feature resolver will ensure that features don't get unified across test and non-test dependencies.
- Rust 2021 will allow some new idioms.
> chore: switch to rust 2021 edition & resolver 2

- actors/miner/src/lib.rs
This is a small pre-factor for FIP0056 because I'm handling the pledge the same way there.
Basically, instead of checking if we have enough funds to cover the pledge each time we update a sector, do so once at the end (and check the balance invariants). This will save a _bit_ of gas, but, more importantly, it avoids using two different "pledge deltas".
> Simplify pledge update on sector upgrade

- actors/market/src/deal.rs
- actors/market/src/lib.rs
- actors/market/src/state.rs
- actors/market/tests/cron_tick_deal_expiry.rs
- actors/market/tests/cron_tick_deal_slashing.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/market/tests/on_miner_sectors_terminate.rs
- runtime/src/runtime/policy.rs
- runtime/src/test_utils.rs
Increases the deal update interval to 30 days and reworks the scheduling to be independent of either the current epoch or old schedule. This means that new code can be deployed into mainnet that will re-distribute the updates across a 30-day period, effectively an on-the-fly migration. Plus it's a more robust construction anyway.
See https://github.com/filecoin-project/FIPs/discussions/638
This came out nicely - most of the work was updating tests with fragile assumptions.
Closes #1238.
> Increase market deal update processing interval to 30 days (FIP-0060)

- actors/account/src/lib.rs
- actors/cron/src/lib.rs
- actors/datacap/src/lib.rs
- actors/eam/src/lib.rs
- actors/ethaccount/src/lib.rs
- actors/evm/src/lib.rs
- actors/init/src/lib.rs
- actors/market/src/lib.rs
- actors/miner/src/lib.rs
- actors/multisig/src/lib.rs
- actors/paych/src/lib.rs
- actors/power/src/lib.rs
- actors/reward/src/lib.rs
- actors/system/src/lib.rs
- actors/verifreg/src/lib.rs
- runtime/Cargo.toml
- runtime/src/runtime/actor_code.rs
- runtime/src/runtime/fvm.rs
This is somewhat of an experiment in improving logs, but I think a useful one. Now that the log message formatting is in the built-in actors, we can improve it. I think it's worth landing, but probably isn't the best long term solution here.
```
[TRACE]<Init::1> called exec; params.code_cid: Cid(bafk2bzacechqgn3sj2vlvtjmc4gflanyzto667licltehusfjjd2fgxzxersu)
[TRACE]<Init::1> caller code CID: Cid(bafk2bzacecysql6qcae3ce5qtpcfi4redzthm3zh6yem4ysnpqsyyzt4z4orq)
[TRACE]<Init::1> robust address: Address { network: Mainnet, payload: Actor([37, 45, 230, 183, 58, 234, 176, 63, 50, 214, 200, 206, 15, 67, 199, 165, 229, 227, 169, 138]) }
```
1. The functionality could be pulled into the FVM SDK's `init_logging()` method, with additional parameters for the Logger initialisation
2. Probably better is …
> Include actor name and ID in log prefix

- actors/miner/src/lib.rs
- actors/miner/src/policy.rs
- actors/miner/src/testing.rs
- actors/miner/src/types.rs
- actors/miner/tests/extend_sector_expiration_test.rs
- actors/miner/tests/sector_assignment.rs
- actors/miner/tests/sectors_stores_test.rs
- actors/miner/tests/util.rs
- state/src/check.rs
- test_vm/src/util.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/replica_update_test.rs
Approach 2 from #914.
Additionally, given:
| A | B | C |
|   |   |   + new expiration
|   |   + old expiration
|   + new power base (current epoch)
+- old power base (usually the activation epoch)
Previously, we'd take the remaining weight from B and then normalize it over A + B + C (new_expiration - activation).
This isn't quite correct, but it was as correct as we could get without recording the power base epoch. However, now that we have the power base epoch, we should normalize it (spread it out over) B + C, not A.
In practice, this just means:
1. Updating the power base when extending a non-simple QaP sector.
2. Adjusting the tests to account for these changes.
> fix: sector activation epoch

- actors/market/src/policy.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/miner/src/lib.rs
- actors/miner/src/policy.rs
- actors/miner/src/testing.rs
- actors/miner/src/types.rs
- actors/miner/tests/extend_sector_expiration_test.rs
- actors/miner/tests/sector_assignment.rs
- actors/miner/tests/sectors_stores_test.rs
- actors/miner/tests/util.rs
- runtime/src/runtime/policy.rs
- state/src/check.rs
- test_vm/src/util.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/publish_deals_test.rs
- test_vm/tests/replica_update_test.rs
This PR speculatively reverts two of the code changes scoped for nv19 to accelerate the nv19 timeline and reduce upgrade risk
1. Sector activation bug fix: reverting this removes migration risk which is a requirement for accelerating the timeline and likely the right thing to do with the current timeline
2. FIP 0052 is reverted because it requires the sector activation bug fix to maintain the security invariant that sectors live no more than 5 years beyond their time of sealing.
> Revert activation bug fix and FIP 0052

- actors/miner/src/lib.rs
The [original code](https://github.com/filecoin-project/builtin-actors/blob/master/actors/miner/src/lib.rs#L922-L923) indexes into `precommits` before check `is_empty`. This PR moves the check right after `precommits` is assigned.
> `prove_commit_aggregate`: should check `is_empty` before indexing into `precommits`

- actors/miner/src/lib.rs
Proof length check has already happened [above](https://github.com/filecoin-project/builtin-actors/blob/master/actors/miner/src/lib.rs#L509) , so no need to check again.
> remove duplicate check

- actors/evm/shared/src/uints.rs
The special check for `(&U256::I128_MIN, &U256::ONE)` is in fact unnecessary, and this check incurs some extra gas for each `sdiv` instruction.
> optimize i256_div: remove unnecessary check

- test_vm/src/lib.rs
- test_vm/src/util.rs
- test_vm/tests/authenticate_message_test.rs
- test_vm/tests/batch_onboarding.rs
- test_vm/tests/change_beneficiary_test.rs
- test_vm/tests/change_owner_test.rs
- test_vm/tests/commit_post_test.rs
- test_vm/tests/datacap_tests.rs
- test_vm/tests/replica_update_test.rs
- Adds more methods to the VM trait in order to be able to implement check_invariants as a free method on the abstract trait
- Refactors a number of simple tests to take in the VM trait rather than a concrete TestVM
> Refactor some tests in the form of the abstract VM

- actors/evm/src/interpreter/instructions/mod.rs
In this context, `$arg` is undefined. In fact the zero arg case is not used, so it's also safe to remove it entirely.
> fix def_primop

- test_vm/src/lib.rs
- test_vm/src/util.rs
- test_vm/tests/batch_onboarding.rs
- test_vm/tests/evm_test.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/multisig_test.rs
- Adds a utility function for serializing cbor params
- Fixes a bug in the test_vm that was causing some message invocations to fail
- More of the easily transferred tests are ported to use the new dyn VM trait
> More test refactors

- test_vm/src/lib.rs
- test_vm/tests/commit_post_test.rs
- test_vm/tests/init_test.rs
- test_vm/tests/power_scenario_tests.rs
- test_vm/tests/publish_deals_test.rs
- test_vm/tests/replica_update_test.rs
- test_vm/tests/terminate_test.rs
- test_vm/tests/test_vm_test.rs
- test_vm/tests/verified_claim_test.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
- test_vm/tests/withdraw_balance_test.rs
Simple refactors of remaining tests. At this point all testing functionality has simple 1-1 ports. 
Then deduplicates some code in the TestVM
- removes apply_message (replaced by execute_message)
- TestVM::normalize_address, TestVM::get_state, TestVM::get_miner_balance, TestVM::get_miner_info replaced by free functions accepting a &dyn VM
> Refactor remaining tests with abstract VM trait

- Cargo.lock
- actors/miner/src/beneficiary.rs
- actors/miner/src/types.rs
- test_vm/Cargo.toml
- test_vm/src/expects.rs
- test_vm/src/lib.rs
- test_vm/src/trace.rs
- test_vm/src/util.rs
- test_vm/tests/commit_post_test.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/multisig_test.rs
- test_vm/tests/power_scenario_tests.rs
- test_vm/tests/publish_deals_test.rs
- test_vm/tests/replica_update_test.rs
- test_vm/tests/terminate_test.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
This is a clean-up and improvement of integration test support code. A few considerations:
- Strengthen expectations to always check from address and exit code, and almost always check value
- Decouple trace and expectations from TestVM internals so they can later be moved to FVM repos and shared with other integration test frameworks (like anorth/fvm-workbench)
- Reduce noise associated specifying expectation details in tests with builder style constructors
Limitations:
- No handling yet for subinvocations in builder methods
Future work
- Add customisation methods to, e.g. `Expect::send(...).with_exit(ErrInsufficientFunds)`.
- Add support for subinvocations in builder
- Add workflow-style builders that encapsulate expectations for a multi-call sequence between actors.
> Extract trace/expectations from test VM and add expectation builders

- actors/market/src/state.rs
- actors/miner/src/commd.rs
- test_vm/src/deals.rs
- test_vm/src/fakes.rs
- test_vm/src/lib.rs
- test_vm/src/util.rs
- test_vm/tests/batch_onboarding.rs
- test_vm/tests/batch_onboarding_deals_test.rs
- test_vm/tests/commit_post_test.rs
- test_vm/tests/publish_deals_test.rs
- test_vm/tests/replica_update_test.rs
Existing integration tests don't cover batch pre/prove-commit with deals, only one or the other. This test covers new ground by covering both.
This is currently light on checks and expectations as the initial motivation is benchmarking. Some state checks and call tree expectations can be added with a bit more work (potentially in a follow-up, for which I will file issues).
> Implemented an end-to-end integration test of batch/aggregate onboarding with verified deals.

- actors/miner/src/lib.rs
https://github.com/filecoin-project/builtin-actors/issues/1306
> refactor replica updates to use the batched activation and claim method

- actors/miner/src/ext.rs
- actors/miner/src/lib.rs
- actors/miner/src/types.rs
- actors/miner/tests/util.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/src/types.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
Work towards #1278.
TODOs
Batching of claim allocations saves both messaging overheads and state mutation costs by only updating the DataCap actor once. The full stack traces can be found [here](https://gist.github.com/alexytsu/8981c9bfe9525fc18d5a058f7d590c30).
The total gas costs for the PCA message drops approximately ~25%
Before:
```
Span[Root, self: {sum=0, none=0}, total: {sum=322,973,688, OnVerifyAggregateSeals=115,956,010, OnBlockLink=101,446,488, wasm_exec=43,387,915, OnBlockOpenBase=31,302,480, OnSyscall=14,112,000, wasm_memory_init=12,504,269, OnMethodInvocation=2,100,000, wasm_memory_grow=760,218, OnActorUpdate=475,000, OnBlockOpenPerByte=382,410, OnGetRandomness=344,160, OnBlockCreate=171,410, OnBlockRead=15,907, OnHashing=9,422, OnValueTransfer=6,000, OnGetActorCodeCid=0, …
```
> Batch ClaimAllocations during ProveCommitAggregate

- runtime/src/runtime/policy.rs
From the [implementation](https://github.com/filecoin-project/builtin-actors/blob/master/actors/miner/src/deadlines.rs#L106) it's clear that the dispute window is right after a Window PoSt window instead of a challenge window(which is `wpost_challenge_window` epochs ahead of the corresponding Window PoSt window)
> fix comment of wpost_dispute_window

- actors/miner/src/deadline_state.rs
`sectors.is_empty()` is already checked [at the beginning](https://github.com/filecoin-project/builtin-actors/blob/ea77289a435303aefc60a050fb4332f9728e5772/actors/miner/src/deadline_state.rs#L402), the check in the loop can be moved to the end after `sectors` have shrinked.
> check sectors.is_empty() at the more proper position

- actors/market/src/lib.rs
- actors/market/src/types.rs
- actors/market/tests/activate_deal_failures.rs
- actors/market/tests/batch_activate_deals.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/market/tests/random_cron_epoch_during_publish.rs
- actors/market/tests/verify_deals_for_activation_test.rs
- actors/miner/src/ext.rs
- actors/miner/src/lib.rs
- actors/miner/tests/util.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/src/types.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- runtime/src/util/batch_return.rs
- runtime/tests/batch_return_test.rs
- test_vm/src/expects.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/replica_update_test.rs
Addressing #1278 
A small tidying refactor and reduction of messaging overhead costs is seen here. Gas savings are not as significant as https://github.com/filecoin-project/builtin-actors/pull/1304 since the costliness of the state updates themselves have not been reduced per se. 
Design caveats:
- ActivateDeals is modified in place to become BatchActivateDeals (which implicitly assumes batches by sector)
- In order to more easily preserve a parallel mapping between params and results, callers (miner actor) of BatchActivateDeals no longer check for sectors with zero deals. Instead, these are handled gracefully (though through a shortcut path) in the market actor. 
TODOs
> Batch deal activations

- actors/miner/src/deadlines.rs
- runtime/src/runtime/policy.rs
This PR introduces a new field `wpost_deadline_window` to the `Policy` struct. Previously there was a [bug](https://github.com/filecoin-project/builtin-actors/blob/b712d1ed4ad6f6da57916caaed8af209daaf4db4/actors/miner/src/deadlines.rs#L142) but it happens that `wpost_challenge_window` and `wpost_deadline_window` are equal but they don't have to be.
`% policy.wpost_period_deadlines` is unnecessary since `current_epoch - current_period_start` is in range [0, wpost_proving_period), so `((current_epoch - current_period_start) / policy.wpost_deadline_window)` is in range [0, wpost_period_deadlines)
> fix new_deadline_info_from_offset_and_epoch

- Cargo.lock
- Cargo.toml
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/evm/shared/Cargo.toml
- actors/evm/src/interpreter/system.rs
- actors/evm/tests/misc.rs
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/miner/src/commd.rs
- actors/miner/src/lib.rs
- actors/miner/tests/state_harness.rs
- actors/miner/tests/util.rs
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- runtime/Cargo.toml
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- state/Cargo.toml
- test_vm/Cargo.toml
- bump versions inline with next helix set
- temp bump to allow helix-onchain filecoin to build its integration tests
- update to new fvm versions
> Update FVM types

- test_vm/src/deals.rs
- test_vm/src/lib.rs
- test_vm/src/util.rs
- test_vm/src/util/blockstore.rs
- test_vm/src/util/mod.rs
- test_vm/tests/authenticate_message_test.rs
- test_vm/tests/batch_onboarding.rs
- test_vm/tests/batch_onboarding_deals_test.rs
- test_vm/tests/change_beneficiary_test.rs
- test_vm/tests/change_owner_test.rs
- test_vm/tests/commit_post_test.rs
- test_vm/tests/datacap_tests.rs
- test_vm/tests/evm_test.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/init_test.rs
- test_vm/tests/market_miner_withdrawal_test.rs
- test_vm/tests/multisig_test.rs
- test_vm/tests/power_scenario_tests.rs
- test_vm/tests/publish_deals_test.rs
- test_vm/tests/replica_update_test.rs
- test_vm/tests/terminate_test.rs
- test_vm/tests/verified_claim_test.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
- test_vm/tests/withdraw_balance_test.rs
A trait that returns a dyn Blockstore is more flexible than returning a generic BS: Blockstore. 
At call sites requiring a concrete type, the dyn Blockstore can be wrapped.
> Have VM trait expose a dyn blockstore

- Cargo.lock
- Cargo.toml
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/evm/shared/Cargo.toml
- actors/evm/src/state.rs
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- runtime/Cargo.toml
- state/Cargo.toml
- test_vm/Cargo.toml
This makes it easier to update them and makes dependency upgrade diffs smaller. It should reduce rebase conflicts for the same reason.
> chore: switch to workspace deps common deps & workspace packages

- Cargo.lock
- Cargo.toml
Start depending on fvm next branch while we develop backwards incompatible features for FVM ascent. 
I had to bump the anyhow version dependency to be in sync with fvm as otherwise cargo could not resolve its version correctly. While doing that, it brought with it a new error `BTreeSet::<T>::new is not yet stable as a const fn` so I bumped also the rust version to be in sync with fvm rust version.
> Switch to FVM next branch

- state/src/check.rs
- test_vm/src/lib.rs
- test_vm/src/util/mod.rs
- test_vm/src/vm.rs
- test_vm/tests/batch_onboarding.rs
- test_vm/tests/change_beneficiary_test.rs
- test_vm/tests/change_owner_test.rs
- test_vm/tests/commit_post_test.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/init_test.rs
- test_vm/tests/market_miner_withdrawal_test.rs
- test_vm/tests/multisig_test.rs
- test_vm/tests/power_scenario_tests.rs
- test_vm/tests/publish_deals_test.rs
- test_vm/tests/replica_update_test.rs
- test_vm/tests/terminate_test.rs
- test_vm/tests/test_vm_test.rs
- test_vm/tests/verified_claim_test.rs
- test_vm/tests/verifreg_remove_datacap_test.rs
- update VM trait to align with anorth/fvm-workbench
Some methods that were previously on the abstract VM are deemed specific to the implementation of the TestVM in builtin-actors. To ease alignment with VM implementations in other contexts such as https://github.com/anorth/fvm-workbench, certain methods have been removed from the trait such as those relating to builtin-actors' notion of `Policy` and actor manifest.
> Update VM trait

- actors/market/src/lib.rs
- actors/market/src/types.rs
- actors/miner/src/ext.rs
- actors/miner/src/lib.rs
- actors/miner/tests/util.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/src/types.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
This PR reworks the verified registry ClaimAllocations method to follow the same pattern as the built-in market's ActivateDeals. Claims are grouped by sector, and a failed claim will cause all claims for that sector to fail. The all-or-nothing flag requests any failure to cause an abort.
This doesn't change the observable behaviour today because all-or-nothing is always set to true. But it does follow a pattern for batching now established (#1310) in the market actor, and prepares for the flag to be false when miner APIs support it (e.g. with [direct data onboarding](https://github.com/filecoin-project/FIPs/discussions/730)).
> Claim allocations processes batches by sector

- actors/market/src/deal.rs
- actors/market/src/lib.rs
- actors/market/src/state.rs
- actors/market/src/types.rs
- actors/market/tests/activate_deal_failures.rs
- actors/market/tests/batch_activate_deals.rs
- actors/market/tests/cron_tick_deal_expiry.rs
- actors/market/tests/cron_tick_deal_slashing.rs
- actors/market/tests/cron_tick_timedout_deals.rs
- actors/market/tests/deal_api_test.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/market/tests/on_miner_sectors_terminate.rs
- actors/market/tests/random_cron_epoch_during_publish.rs
- actors/market/tests/verify_deals_for_activation_test.rs
- actors/miner/src/ext.rs
- actors/miner/src/lib.rs
- actors/miner/tests/miner_actor_test_precommit_batch.rs
- actors/miner/tests/terminate_sectors_test.rs
- actors/miner/tests/util.rs
- runtime/src/runtime/policy.rs
- runtime/src/test_utils.rs
- test_vm/src/expects.rs
- test_vm/src/util/workflows.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/replica_update_test.rs
- test_vm/tests/terminate_test.rs
Adds `provider_sectors` to market state, a `HAMT[Address]HAMT[SectorNumber]SectorDeals`. The value is a sorted vec of deal IDs and the associated sector's expiration epoch. Also adds sector number to deal state, to permit finding and removing that mapping when a deal expires.
Prototype for part of direct data onboarding.
> Implement sector->deal mapping in built-in market actor

- actors/miner/src/lib.rs
- actors/miner/tests/miner_actor_test_precommit_batch.rs
- actors/miner/tests/util.rs
- integration_tests/src/tests/batch_onboarding.rs
- integration_tests/src/tests/batch_onboarding_deals_test.rs
- integration_tests/src/tests/commit_post_test.rs
- integration_tests/src/tests/extend_sectors_test.rs
- integration_tests/src/tests/replica_update_test.rs
- integration_tests/src/tests/terminate_test.rs
- integration_tests/src/tests/verified_claim_test.rs
- integration_tests/src/util/workflows.rs
- test_vm/tests/batch_onboarding.rs
- test_vm/tests/batch_onboarding_deals_test.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/power_scenario_tests.rs
Deprecate old precommit methods and enforce including CommD
Miner actor now enforces CompactCommD, meaning it is valid to provide `Some(CompactCommD(None))` in the precommit unsealed field to compactly specify a CC sector but not valid to specify `None` directly in this field.
> Remove old precommit methods

- actors/miner/src/lib.rs
- actors/miner/tests/miner_actor_test_precommit_batch.rs
- actors/miner/tests/util.rs
- integration_tests/src/tests/batch_onboarding.rs
- integration_tests/src/tests/batch_onboarding_deals_test.rs
- integration_tests/src/tests/commit_post_test.rs
- integration_tests/src/tests/extend_sectors_test.rs
- integration_tests/src/tests/replica_update_test.rs
- integration_tests/src/tests/terminate_test.rs
- integration_tests/src/tests/verified_claim_test.rs
- integration_tests/src/util/workflows.rs
- test_vm/tests/batch_onboarding.rs
- test_vm/tests/batch_onboarding_deals_test.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/power_scenario_tests.rs
This is #1352 applied to the integration branch `integration/direct-onboarding`.
- PreCommitSector and PreCommitBatch deprecated
- PreCommitBatchV2 now requires specifying (compact) CommD
- Move all testing to use PreCommitBatchV2
> Remove deprecated precommit methods

- actors/market/src/state.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/multisig/src/lib.rs
- actors/multisig/src/state.rs
- actors/multisig/src/testing.rs
- actors/multisig/src/types.rs
- actors/power/src/lib.rs
- actors/power/src/state.rs
- actors/power/src/testing.rs
- actors/power/src/types.rs
- actors/power/tests/harness/mod.rs
- actors/verifreg/src/expiration.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/src/state.rs
- actors/verifreg/src/testing.rs
- actors/verifreg/src/types.rs
- actors/verifreg/tests/harness/mod.rs
- integration_tests/src/tests/verified_claim_test.rs
- integration_tests/src/tests/verifreg_remove_datacap_test.rs
- runtime/src/util/map.rs
- runtime/src/util/mapmap.rs
- runtime/tests/mapmap_test.rs
Only the miner actor and some state check utilities remain.
The old Map is also implicitly used in MapMap and Set. I will update those to follow these patterns later too.
> Remove uses of Map from most actors

- actors/miner/src/testing.rs
- state/src/check.rs
- test_vm/src/lib.rs
This _doesn't_ migrate to the new `Map2` interface everywhere, it just avoids the use of `Hamt::load` and `Hamt::new`, which will be deprecated in the next release of `fvm_ipld_hamt`.
part of #1346
> fix: explicitly specify HAMT bitwidths everywhere

- Cargo.lock
- actors/market/src/lib.rs
- actors/market/src/types.rs
- actors/market/tests/activate_deal_failures.rs
- actors/market/tests/batch_activate_deals.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/market/tests/verify_deals_for_activation_test.rs
- actors/miner/src/ext.rs
- actors/miner/src/lib.rs
- actors/miner/tests/aggregate_prove_commit.rs
- actors/miner/tests/miner_actor_test_precommit_batch.rs
- actors/miner/tests/prove_commit.rs
- actors/miner/tests/util.rs
- integration_tests/src/expects.rs
- integration_tests/src/tests/extend_sectors_test.rs
- integration_tests/src/tests/replica_update_test.rs
- integration_tests/src/util/workflows.rs
- test_vm/Cargo.toml
- test_vm/src/fakes.rs
- test_vm/tests/extend_sectors_test.rs
- test_vm/tests/replica_update_test.rs
This avoids ProveReplicaUpdates calling the market twice consecutively.
Note this is based on `master`, it's not only part of direct data onboarding.
Closes #1308
> Adds CommD as option in return value from ActivateDeals

- .github/workflows/ci.yml
It's not helping and is more likely to break builds than to speed them up. In practice, it actually appears to be slowing them down.
related to #1366
> ci: remove the build cache

- integration_tests/src/expects.rs
- integration_tests/src/lib.rs
- integration_tests/src/tests/commit_post_test.rs
- integration_tests/src/tests/extend_sectors_test.rs
- integration_tests/src/tests/multisig_test.rs
- integration_tests/src/tests/power_scenario_tests.rs
- integration_tests/src/tests/publish_deals_test.rs
- integration_tests/src/tests/replica_update_test.rs
- integration_tests/src/tests/terminate_test.rs
- integration_tests/src/tests/verifreg_remove_datacap_test.rs
- integration_tests/src/util/mod.rs
- integration_tests/src/util/workflows.rs
- test_vm/src/lib.rs
- test_vm/src/messaging.rs
- vm_api/src/trace.rs
A more portable format for invocation traces that are designed to work on real FVMs such as https://github.com/anorth/fvm-workbench/pull/24
Closes https://github.com/filecoin-project/builtin-actors/issues/1365
> Portable Invocation Traces

- actors/market/src/ext.rs
- actors/market/src/lib.rs
- actors/market/src/state.rs
- actors/market/src/testing.rs
- actors/market/tests/activate_deal_failures.rs
- actors/market/tests/batch_activate_deals.rs
- actors/market/tests/cron_tick_deal_expiry.rs
- actors/market/tests/cron_tick_deal_slashing.rs
- actors/market/tests/cron_tick_timedout_deals.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/market/tests/on_miner_sectors_terminate.rs
- actors/market/tests/random_cron_epoch_during_publish.rs
- actors/market/tests/sector_content_changed.rs
- actors/market/tests/verify_deals_for_activation_test.rs
- actors/miner/src/ext.rs
- actors/miner/src/lib.rs
> Implements SectorContentChanged method in built-in market actor

- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- runtime/src/test_utils.rs
Some market tests iterated a number of times proportional to the deal updates interval, which was recently multiplied by 30. This change sets the policy update interval for those tests explicitly. We can probably gain quite a bit by setting explicit policy through many tests.
> Speed up very slow market test

- actors/miner/src/lib.rs
This PR extracts functionality shared between ProveCommit and ProveCommitAggregate to be used in the new ProveCommitV2 method(s).
The new method takes a vector of precommits, validates that they are ok for committing and creates a general precursor to the inputs needed by PoRep and snark pack PoRep
> Refactor: extract precommit validation and svi conversion to shared method

- Cargo.lock
- runtime/Cargo.toml
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/randomness.rs
Integrates https://github.com/filecoin-project/ref-fvm/pull/1848 from the FVM `next` workstream.
Test to come.
> feat: FVM no longer draws randomness for you

- actors/miner/src/lib.rs
- actors/miner/src/monies.rs
- actors/miner/src/state.rs
- actors/miner/src/types.rs
- actors/miner/tests/batch_method_network_fees_test.rs
- actors/miner/tests/miner_actor_test_precommit_batch.rs
- actors/miner/tests/prove_commit.rs
- actors/miner/tests/util.rs
- integration_tests/src/tests/batch_onboarding_deals_test.rs
- integration_tests/src/tests/commit_post_test.rs
- integration_tests/src/tests/extend_sectors_test.rs
- integration_tests/src/tests/replica_update_test.rs
- integration_tests/src/tests/terminate_test.rs
- integration_tests/src/util/workflows.rs
Sending of notifications is deferred for a subsequent PR.
Replaces #1379.
> Implements new ProveCommit batch+aggregate for direct onboarding

- Cargo.toml
Based on the discussion in https://github.com/filecoin-project/ref-fvm/issues/1856, the feature will disappear and should not be used anymore.
> Remove go-interop feat from the AMT crate

- actors/market/src/ext.rs
- actors/market/src/lib.rs
- actors/market/tests/activate_deal_failures.rs
- actors/market/tests/harness.rs
- actors/market/tests/sector_content_changed.rs
- actors/miner/src/lib.rs
- actors/miner/src/notifications.rs
- actors/miner/src/types.rs
Also simplifies return values to make notifications fire and forget. Plumbing notification results back through to a structure parallel with the input proved very complex, and of not much value. I intend to emit events for deal activation from the built-in market actor to provide insight into deals that were activated.
Note the return values are not yet populated, deferred for a future PR.
> Send SectorContentChanged from new onboarding methods

- Cargo.lock
- Cargo.toml
We were importing both a v0.1.0 and a v0.2.0 blockstore from the FVM, now we only import the latter.
This also upgrades to the latest clap version (FWIW).
> chore: upgrade actor bundler to use the latest blockstore

- actors/miner/src/lib.rs
- runtime/src/util/batch_return.rs
- runtime/src/util/mod.rs
This propagates exit codes from intermediate batch returns through to the final result (although I don't think we have much variety in them in the first place).
An alternative would be to iterate the original parameters and output, comparing sector numbers. We would then have to pick a single exit code to stand in for any failure.
> Compute batch returns for direct onboarding methods

- Cargo.lock
- Cargo.toml
- actors/miner/Cargo.toml
- actors/miner/src/lib.rs
- actors/miner/src/types.rs
- integration_tests/src/tests/extend_sectors_test.rs
- integration_tests/src/tests/replica_update_test.rs
See this [discussion](https://github.com/filecoin-project/FIPs/discussions/601) for more details. In short, we want to have an easily extensible flags field for the `SectorOnChainInfo` instead of a field per flag, which is wasteful.
@ZenGround0 Hopefully, I introduced your description correctly. Is the `u8` correct in this context?
Closes https://github.com/filecoin-project/builtin-actors/issues/1275
> replace simple_qa_power with extensible flags

- actors/miner/src/lib.rs
- actors/miner/src/types.rs
- actors/miner/tests/prove_replica_test.rs
- actors/miner/tests/util.rs
- integration_tests/src/tests/extend_sectors_test.rs
- integration_tests/src/tests/replica_update_test.rs
- test_vm/tests/replica_update_test.rs
- Remove code for unused PRU2 replacing with a stub that always fails 
- Remove most code from sector_activate_deals which existed only for the benefit of the PRU2 flow
- Claim the prove_replica_updates2 name for the DDO flow introduced in this integration branch
- Remove PRU2 from tests
Related PR: https://github.com/filecoin-project/go-state-types/pull/214
> Deprecate unused Prove Replica update 2

- actors/market/src/testing.rs
- actors/miner/src/lib.rs
- actors/miner/src/testing.rs
- actors/miner/src/types.rs
- actors/miner/tests/prove_commit.rs
- actors/miner/tests/prove_replica_test.rs
- actors/miner/tests/sectors_stores_test.rs
- integration_tests/src/tests/replica_update_test.rs
- integration_tests/src/util/workflows.rs
- state/src/check.rs
Stop writing deal ids into sector info upon commit
Improve the miner state check/summary framework to better work with cross market / miner check in the future 
- not yet following through on implementing the new market check, we need to construct the sector => deal index in market summary and then we can check the new live_data_sectors_map for inclusion of all sector numbers in the market index.
> Deprecate Deal IDs

- actors/miner/src/lib.rs
The existing logic suppresses any errors if multiple sector validations fail. Return an error if none of the sectors are able to be validated, specifically in the proof validation and data activation stages
> Return error if success count for proof validation or data activations is 0

- Cargo.lock
- Cargo.toml
- actors/miner/src/expiration_queue.rs
- actors/miner/tests/apply_rewards.rs
- actors/miner/tests/change_worker_address_test.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- runtime/Cargo.toml
- rust-toolchain.toml
This doesn't add support for synthetic porep, but splits:
https://github.com/filecoin-project/builtin-actors/pull/1335
Into two PRs.
> chore: update the fvm

- actors/miner/src/lib.rs
- actors/miner/tests/prove_replica_test.rs
- actors/miner/tests/util.rs
> Prove commit 2 simple tests

- actors/miner/src/lib.rs
- actors/miner/src/notifications.rs
- actors/miner/tests/prove_replica_failures_test.rs
- actors/miner/tests/prove_replica_test.rs
- actors/miner/tests/util.rs
Tests for PRU2 conditions that should cause the method to abort.
Further tests for success and partial success cases are coming later.
> PRU2 tests that abort the whole method

- actors/miner/tests/prove_commit2_test.rs
- actors/miner/tests/util.rs
This is a pure move, no functional change.
This makes space for more tests of both these methods without overloading a single file with both of them.
> Move prove_commit2 tests to separate file from pru tests

- actors/miner/src/lib.rs
- actors/miner/tests/prove_commit2_test.rs
- actors/miner/tests/prove_replica_failures_test.rs
- actors/miner/tests/prove_replica_test.rs
- actors/miner/tests/util.rs
Tests caught a couple of errors in tracking result set sizes through the validation stages.
> Tests and fixes for ProveReplicaUpdates2

- actors/account/src/lib.rs
- actors/ethaccount/src/lib.rs
- actors/evm/src/lib.rs
- actors/multisig/src/lib.rs
- runtime/src/dispatch.rs
- runtime/src/lib.rs
FIP-0071 (Deterministic State Access) requires the use of the `DAG_CBOR` codec, instead of the `CBOR` codec, where internal links (cids) should be considered "reachable". We use `CBOR` by default for method parameters as we don't _usually_ pass references by CID in methods (and using `CBOR` here will save us some gas).
However, there are two exceptions:
1. `EVM::bytecode` needs to return a reference to the contained bytecode. This reference needs to be considered "reachable".
2. `EVM::invoke_contract_delegate` needs to be passed a reference to some bytecode, so the parameters need to be `DAG_CBOR`.
This patch augments the dispatch system to allow specifying codecs in method signatures and fixes the EVM case. Specifically, an actor method may specify (either or both):
- Parameters: …
> dispatch: improve dispatch macro and allow specifying codecs

- actors/paych/src/lib.rs
- actors/paych/tests/paych_actor_test.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- test_vm/src/messaging.rs
part of https://github.com/filecoin-project/ref-fvm/issues/1837
> feat: remove beneficiary from self-destruct

- actors/paych/tests/paych_actor_test.rs
- runtime/src/test_utils.rs
The actor has been deleted so the assertions should reflect that. By removing the state from the mock runtime, this change will also let us catch any other testing bugs (and let's us assert that the actor was actually deleted).
> fix: correctly assert the state at the end of the paychan test

- actors/miner/tests/prove_commit2_test.rs
- actors/miner/tests/prove_replica_failures_test.rs
- actors/miner/tests/prove_replica_test.rs
This pattern, common elsewhere, can now be followed by new tests that adapt these.
> Check state invariants in direct onboarding tests

- actors/miner/src/lib.rs
- actors/miner/tests/prove_commit2_failures_test.rs
- actors/miner/tests/prove_commit2_test.rs
- actors/miner/tests/prove_replica_failures_test.rs
- actors/miner/tests/util.rs
This mirrors the existing tests for ProveReplicaUpdates2 and expands the harness method with a configuration object supporting similar control over the behaviour of mocked calls.
Tests for cases that partially succeed are to follow in another PR.
> Tests for ProveCommitSectors2 for cases that abort entirely

- actors/multisig/src/lib.rs
- actors/multisig/tests/multisig_actor_test.rs
> Multisig approve call should return error data back to the user

- actors/miner/src/state.rs
Closes #1426. 
See Idea: fix non caching mistake in https://github.com/filecoin-project/FIPs/discussions/771.
> Cache precommit state and use the cache state to expire all precommits in the proving deadline cron job

- actors/miner/tests/prove_commit2_test.rs
- actors/miner/tests/prove_replica_test.rs
- actors/miner/tests/util.rs
This is mostly the same tests adapted from prove_replica_update2.
One key test currently missing is that the implied CommD from the piece manifests matches that which was pre-committed with the sector. That needs a larger change to the test harness to make the CommD's less fake, which I'll attempt next.
> Tests for prove_commit_sectors2

- actors/market/src/lib.rs
- actors/market/tests/transient_marked_for_termination.rs
@anorth I wasn't sure if this was the particular change you intended.
From my understanding it would be safe here to switch on the details of the `DealProposal`.
i.e. if the current epoch is before the start_epoch of the proposal we can consider the deal yet to be activated and return `epoch_undefined` as before. 
else, we can conclude the deal is terminated and return USR_NOT_FOUND. In fact, I think if deal terminations are made synchronously (with associated cleanup), we wouldn't see this case anyway in the long term. In that end case, the current behaviour might make sense?
> Use ExitCode::USR_NOT_FOUND for missing state in GetDealActivation

- actors/miner/src/commd.rs
- actors/miner/src/lib.rs
- actors/miner/tests/prove_commit2_failures_test.rs
- actors/miner/tests/prove_commit2_test.rs
- actors/miner/tests/prove_replica_test.rs
- actors/miner/tests/util.rs
Tests that CommD computed from pieces must match that declared at precommit. Tests that updating an empty replica to be empty is permitted (later, when we allow updates to non-empty replicas, it won't be a no-op).
> More tests for direct data onboarding

- actors/miner/src/deadline_state.rs
- actors/miner/tests/move_partitions_test.rs
I think the comment `sector_count is both total sector count and total live sector count, since no sector is faulty here.` was wrong. You can have "dead" sectors (terminated or expired) ones. @TippyFlitsUK hit this case when testing moving partitions.
The question is what's the right thing to do. I think it's fine to just move partitions with terminated / expired sectors, and the text of the FIP doesn't disallow this. If so, I think this PR fixes this, and we can land it with a test.
Otherwise, we need to explicitly disallow moving partitions with expired sectors, which the code doesn't currently do.
> fix: miner: move partitions with expired/terminated sectors

- actors/miner/src/deadline_state.rs
backport of https://github.com/filecoin-project/builtin-actors/pull/1455
(removed the tests due to conflicts)
> fix: miner: move partitions with expired/terminated sectors (#1455)

- actors/verifreg/src/emit.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- runtime/src/test_utils.rs
- runtime/src/util/events.rs
- runtime/src/util/mod.rs
- test_vm/src/lib.rs
- test_vm/src/messaging.rs
Subsumes #1320 .
Based on discussions at #1320, https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0049.md AND https://github.com/filecoin-project/FIPs/discussions/754.
Implements events with minimal payload wherein the client has just enough information to determine whether to query state or not based on the payload of the recieved event.
> Actor events for the verified registry

- test_vm/src/lib.rs
- test_vm/src/messaging.rs
- test_vm/tests/suite/authenticate_message_test.rs
- test_vm/tests/suite/batch_onboarding.rs
- test_vm/tests/suite/batch_onboarding_deals_test.rs
- test_vm/tests/suite/change_beneficiary_test.rs
- test_vm/tests/suite/change_owner_test.rs
- test_vm/tests/suite/commit_post_test.rs
- test_vm/tests/suite/datacap_tests.rs
- test_vm/tests/suite/evm_test.rs
- test_vm/tests/suite/extend_sectors_test.rs
- test_vm/tests/suite/init_test.rs
- test_vm/tests/suite/market_miner_withdrawal_test.rs
- test_vm/tests/suite/move_partitions_test.rs
- test_vm/tests/suite/multisig_test.rs
- test_vm/tests/suite/power_scenario_tests.rs
- test_vm/tests/suite/publish_deals_test.rs
- test_vm/tests/suite/replica_update_test.rs
- test_vm/tests/suite/terminate_test.rs
- test_vm/tests/suite/test_vm_test.rs
- test_vm/tests/suite/verified_claim_test.rs
- test_vm/tests/suite/verifreg_remove_datacap_test.rs
- test_vm/tests/suite/withdraw_balance_test.rs
Follow up to #1446 for https://github.com/filecoin-project/builtin-actors/pull/1446#discussion_r1361229200.
> Test VM should use Rc<Blockstore> for consistency with the MockRuntime

- Cargo.lock
- integration_tests/src/util/mod.rs
- state/src/check.rs
- test_vm/src/lib.rs
- vm_api/src/lib.rs
This change adds a layer of abstraction for iterating over actor states. It is motivated by incompatibilities in the way actor states are stored/represented in here in the builtin-actor's TestVM and the 'real FVM' which underlies the test execution environment in anorth/fvm-workbench (https://github.com/anorth/fvm-workbench/issues/30)
Other options considered were:
In fact, both the `TestVM` and workbench `VM` store a `Hamt<BytesKey, ActorState>` within their respective blockstores. This respects the existing API and allows for the Hamt to be loaded in by the caller as necessary. Using a Hamt here also allows finer grain control of iteration with ActorStates being loaded out of the blockstore on an as-needed basis. 
In the ref-fvm however, the `StateTree` struct implementation hides the …
> Check invariants against a BTree rather than a Hamt

- integration_tests/src/tests/batch_onboarding.rs
- integration_tests/src/tests/change_beneficiary_test.rs
- integration_tests/src/tests/change_owner_test.rs
- integration_tests/src/tests/commit_post_test.rs
- integration_tests/src/tests/extend_sectors_test.rs
- integration_tests/src/tests/move_partitions_test.rs
- integration_tests/src/tests/multisig_test.rs
- integration_tests/src/tests/power_scenario_tests.rs
- integration_tests/src/tests/publish_deals_test.rs
- integration_tests/src/tests/replica_update_test.rs
- integration_tests/src/tests/terminate_test.rs
- integration_tests/src/tests/verified_claim_test.rs
- integration_tests/src/tests/verifreg_remove_datacap_test.rs
- integration_tests/src/util/mod.rs
- state/src/check.rs
- test_vm/src/lib.rs
- test_vm/tests/suite/replica_update_test.rs
- test_vm/tests/suite/test_vm_test.rs
Based off discussion in #1461 replacing it
Closes #1460 
- Corrects the name `total_supply` -> `circulating_supply` in the VM api
- Makes total_supply checks optional in `check_state_invariants`
Does not implement total_supply as part of the VM api
- There are no uses of it in the current code
- If tests do require this value, it can be calculated manually from `VM::actor_states` (or implemented as a utility function in _integration_tests/src/util/mod.rs_
> replace total_supply with circulating_supply

- .github/workflows/coverage.yml
Quick follow up on https://github.com/filecoin-project/builtin-actors/pull/1465
This will ensure we have two distinct entries in the Actions tab
I'm pretty sure we'll have to manually clean up the duplicate after this is merged - I'll take care of it
> ci: change the name of the coverage workflow

- actors/market/src/lib.rs
- actors/market/src/state.rs
- actors/market/src/types.rs
- actors/market/tests/deal_api_test.rs
Exposes the new deal->sector mapping in the market actor to smart contracts.
@alexytsu this demonstrates the hiding of whether cron has cleaned up async terminated sectors re #1441 – I think that should follow a similar pattern though they're unfortunately on different integration branches.
Note that there is one other internal state still revealed to callers. After a deal is published and passes its start epoch without being activated, there is some delay until cron cleans it up (and this will remain after FIP-0074). The GetDealSector exit code will change from EX_DEAL_NOT_ACTIVATED to EX_DEAL_EXPIRED when the proposal is cleaned up. We could inspect the proposal's start epoch and simulate EX_DEAL_EXPIRED if the proposal is eligible for clean-up. (In GetDealActivation, the change is from …
> Add GetDealSector exported API method to market actor

- integration_tests/src/tests/mod.rs
- integration_tests/src/tests/replica_update2_test.rs
- test_vm/tests/replica_update2_test.rs
- vm_api/src/trace.rs
This test copies the same deals/allocations/piece manifests, but applies via a replica update instead. This does result in quite a bit of duplication between the tests. If you think this is a problem, I'm open to ideas about improving it. Note that the expectations and assertions are just slightly different, accounting for the power that is gained immediately when updating, vs not when initially onboarding.
> Integration test for prove_replica_updates2

- Cargo.lock
- Cargo.toml
> chore: update fvm/helix libraries to to the final released versions (#1475)

- actors/market/src/emit.rs
- actors/market/src/lib.rs
- actors/market/src/state.rs
- actors/market/tests/activate_deal_failures.rs
- actors/market/tests/batch_activate_deals.rs
- actors/market/tests/cron_tick_deal_expiry.rs
- actors/market/tests/cron_tick_deal_slashing.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/market/tests/on_miner_sectors_terminate.rs
- actors/market/tests/publish_storage_deals_failures.rs
- actors/market/tests/random_cron_epoch_during_publish.rs
For #1464 .
This PR contains Market Actor events for the following deal lifecycle events:
1. Deal published
2. Deal activated
3. Deal terminated (when a sector is terminated by the Miner -> all deals in the sector get terminated)
4. Deal activated
We do not emit events for expired deals i.e. deals that have been published but not activated by their start epoch as that only ever happens in the cron job.
> Market Actor Events

- Cargo.toml
- actors/account/Cargo.toml
- actors/cron/Cargo.toml
- actors/datacap/Cargo.toml
- actors/eam/Cargo.toml
- actors/ethaccount/Cargo.toml
- actors/evm/Cargo.toml
- actors/evm/shared/Cargo.toml
- actors/init/Cargo.toml
- actors/market/Cargo.toml
- actors/miner/Cargo.toml
- actors/multisig/Cargo.toml
- actors/paych/Cargo.toml
- actors/placeholder/Cargo.toml
- actors/power/Cargo.toml
- actors/reward/Cargo.toml
- actors/system/Cargo.toml
- actors/verifreg/Cargo.toml
- runtime/Cargo.toml
- state/Cargo.toml
- test_vm/Cargo.toml
This PR updates the root workspace to specify version, license, and other metadata which we then refer to in all subcrates.
This means, bumping builtin-actor version now only requires changing the version in one place instead of touching 20+ crates (like in https://github.com/filecoin-project/builtin-actors/pull/1286)
> Specify version, license and other metadata in workspace

- README.md
* Current README reads from a pre-nv16 perspective.
* Bundle format description isn't quite right so I've clarified that, including schemas.
* List of released crates has expanded.
> doc: update docs from current POV, clarify bundle format

- Makefile
We now bump the version by editing the workspace `Cargo.toml`. The README will be fixed in a separate patch.
> chore: remove unused targets from the makefile

- runtime/src/util/batch_return.rs
This just avoids some awkward unwraps.
> Cleanup batch return merge logic

- runtime/src/util/batch_return.rs
Small nit, but builders generally take `self` by value to avoid cloning necessarily.
> Take the batch builder by-value

- actors/miner/src/lib.rs
- actors/miner/src/types.rs
- actors/miner/tests/prove_replica_failures_test.rs
- actors/miner/tests/util.rs
- integration_tests/src/tests/prove_commit2_test.rs
- integration_tests/src/tests/replica_update2_test.rs
This will require a corresponding update to the FIP.
> Make Prove{CommitSectors, ReplicaUpdates}3Params aggregate proof type optional

- actors/market/src/lib.rs
- actors/market/src/state.rs
- actors/market/tests/harness.rs
- integration_tests/src/util/mod.rs
Continuing on from a question I raised in https://github.com/filecoin-project/FIPs/pull/930 about the wrapping of an array in a struct, this is seeing what it looks like with that done in code.
> Convert SectorDealIDs to an alias for Vec<DealID>, removing struct

- actors/verifreg/src/emit.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- integration_tests/src/util/workflows.rs
Without this it naively serialises using the underlying Rust BigInt representation:
[sign,[data,data,...]]
BigInts are going to be a footgun for these events, any time we encounter a `DataCap`, `TokenAmount` or some other `BigInt` wrapper since we need this explicit serde callout. I'll follow up tomorrow with a PR to the FIP-0083 doc to add some clarification around what "bigint" means for serialising this field, then hopefully future FIP authors will take note of that.
---
Example field value from this event without this fix: `8201821a4876e80017` which is `[1,[1215752192,23]]`, or specifically:
```
82                                                # array(2)
01                                              #   uint(1)
82                                              #   array(2)
1a …
```
> Serialise bigint as idiomatic Filecoin form

- actors/market/Cargo.toml
- actors/market/src/policy.rs
- actors/market/tests/publish_storage_deals_failures.rs
- actors/miner/src/lib.rs
- actors/miner/src/policy.rs
- actors/miner/src/sectors.rs
- actors/miner/src/state.rs
- actors/miner/tests/compact_sector_numbers_tests.rs
- actors/miner/tests/exported_getters.rs
- actors/miner/tests/miner_actor_test_commitment.rs
- actors/miner/tests/prove_commit.rs
- actors/miner/tests/sector_number_allocation.rs
- actors/reward/src/state.rs
- integration_tests/src/tests/commit_post_test.rs
- runtime/src/builtin/network.rs
- runtime/src/lib.rs
- runtime/src/runtime/policy.rs
Specifically:
- `MAX_SECTOR_NUMBER`
- `Spacetime`
- `SectorQuality`
- `TOTAL_FILECOIN`
- `EPOCH_DURATION_SECONDS`
- `BLOCKS_PER_EPOCH`
> Move some constants & types out of fvm_shared

- actors/market/src/lib.rs
- actors/market/src/testing.rs
- actors/market/tests/on_miner_sectors_terminate.rs
Adds market-internal state invariants between deal stats and provider-sector-deal mapping.
> Add market state invariants and fix a mistake in tests.

- integration_tests/src/tests/batch_onboarding.rs
- integration_tests/src/tests/commit_post_test.rs
- integration_tests/src/tests/replica_update_test.rs
- integration_tests/src/tests/terminate_test.rs
- test_vm/src/lib.rs
When running in fvm the sender is checked for non-implicit executions, which matters when running these in fvm-workbench.
This has already been done to most integration tests, and `cron_tick` does a full execute-and-check, which is more than some of these tests are currently doing.
> fix(integration): cron_tick to use implicit executions to avoid sender checks

- actors/evm/src/interpreter/instructions/lifecycle.rs
- actors/evm/tests/call.rs
- actors/evm/tests/create.rs
- actors/evm/tests/delegate_call.rs
- actors/evm/tests/precompile.rs
- actors/market/tests/deal_termination.rs
- actors/market/tests/settle_deal_payments.rs
- actors/market/tests/verify_deals_for_activation_test.rs
- actors/miner/src/lib.rs
- actors/miner/tests/extend_sector_expiration_test.rs
- actors/multisig/src/lib.rs
- integration_tests/src/tests/commit_post_test.rs
- integration_tests/src/tests/prove_commit3_test.rs
- integration_tests/src/tests/replica_update3_test.rs
- integration_tests/src/tests/verified_claim_test.rs
- runtime/src/lib.rs
- runtime/src/util/map.rs
- rust-toolchain.toml
- vm_api/src/trace.rs
Some of the lints were... kind of 🙄, but it's easier to appease the animated paperclip than to argue with it.
> chore: update rust to 1.76.0 and fix new clippy lints

- actors/miner/src/deadline_state.rs
- actors/miner/src/lib.rs
- actors/miner/src/state.rs
- actors/miner/src/testing.rs
- actors/miner/tests/state_harness.rs
- test_vm/src/lib.rs
For #1346. This is the last direct use of `Map` by actors, the others are embedded inside other structures like `Set`.
> Replace Map with Map2 in miner actor

- actors/market/src/lib.rs
- actors/market/src/state.rs
- actors/market/src/testing.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_test.rs
- actors/market/tests/random_cron_epoch_during_publish.rs
- actors/multisig/tests/util.rs
- actors/verifreg/tests/harness/mod.rs
- integration_tests/src/tests/multisig_test.rs
- runtime/src/lib.rs
- runtime/src/util/map.rs
- runtime/src/util/mod.rs
- runtime/src/util/set.rs
- runtime/src/util/set_multimap.rs
- runtime/tests/set_multimap_test.rs
- runtime/tests/set_test.rs
> Update Set and SetMultimap to use Map2 internally and match new conventions

- actors/verifreg/src/types.rs
very minor, just noticed this while doing a quick audit for https://github.com/filecoin-project/FIPs/pull/961
> fix(verifreg): make RemovedExpiredClaimsReturn deal with ClaimIDs

- actors/market/src/state.rs
- actors/market/tests/activate_deal_failures.rs
- actors/market/tests/batch_activate_deals.rs
- actors/market/tests/cron_tick_deal_expiry.rs
- actors/market/tests/cron_tick_deal_slashing.rs
- actors/market/tests/cron_tick_timedout_deals.rs
- actors/market/tests/deal_termination.rs
- actors/market/tests/harness.rs
- actors/market/tests/market_actor_legacy_tests.rs
- actors/market/tests/market_actor_test.rs
- actors/market/tests/on_miner_sectors_terminate.rs
- actors/market/tests/random_cron_epoch_during_publish.rs
- actors/market/tests/sector_content_changed.rs
- actors/market/tests/settle_deal_payments.rs
- actors/market/tests/transient_marked_for_termination.rs
We have this invariant complaining with nv22, `no deal ids in sector X` for the new `ProviderSectors` mapping: https://github.com/filecoin-project/go-state-types/blob/ad909a3d6ebef5ebc5688b4310e954e27da2203b/builtin/v13/market/invariants.go#L294
I don't think it's the migration that's the cause of this since it's checking the `len==0` case: https://github.com/filecoin-project/go-state-types/blob/ad909a3d6ebef5ebc5688b4310e954e27da2203b/builtin/v13/migration/miner.go#L76-L78
We have 2 ways that we remove items from `provider_sectors` in actors, `pop_sector_deal_ids` and `remove_sector_deal_ids`. The former does cleanup when empty. But the latter just removes and saves. This PR proposes removing in both cases when we get to an empty `DealID` array.
Before I write any tests for this I want …
> fix(market): clean up provider_sectors when empty

- actors/miner/src/lib.rs
minor nit, but I stumbled on this one today, needs a single space
```
00: f01002 (method 24) -- can only dispute window posts during the dispute window(1800 epochs after the challenge window closes) (18)\n (RetCode=18)
```
> fix(miner): add missing space in error message

- Cargo.lock
- Cargo.toml
- actors/verifreg/Cargo.toml
- actors/verifreg/tests/verifreg_actor_test.rs
Starting with ClaimAllocationsParams for now, matching with Go versions of this in go-state-types.
See https://github.com/filecoin-project/go-state-types/pull/263 for the matching PR and a longer description of why/what this is.
> test: verifreg: add initial cbor encoding forms tests

- actors/miner/src/lib.rs
@NemanjaLu92 pointed out that aggregate fee is paid _after_ activations while discussing the need for this for the NI-PoRep method, so this comment was likely incorrect in `prove_commit_sectors3`. I thought this was worth checking with a isolated PR since it should be relatively straightforward to clarify.
> doc(miner): minor correction to aggregate fee comment in PCS3

- actors/power/src/types.rs
left-over from https://github.com/filecoin-project/builtin-actors/pull/1540 where the method was deprecated
> chore!: remove SubmitPoRepForBulkVerifyParams

- actors/verifreg/src/emit.rs
- actors/verifreg/src/lib.rs
- actors/verifreg/tests/harness/mod.rs
- actors/verifreg/tests/verifreg_actor_test.rs
- integration_tests/src/expects.rs
- integration_tests/src/tests/extend_sectors_test.rs
- integration_tests/src/tests/prove_commit3_test.rs
- integration_tests/src/tests/replica_update3_test.rs
- integration_tests/src/tests/replica_update_test.rs
- integration_tests/src/tests/verified_claim_test.rs
- integration_tests/src/tests/verifreg_remove_datacap_test.rs
- integration_tests/src/util/workflows.rs
These two were late to nv22 and were only merged into the release/v13 branch so are missing from master. I suppose we should have a master-first policy to prevent this!
* [Add client to verifier balance event](https://github.com/filecoin-project/builtin-actors/commit/0f205c378983ac6a08469b9f400cbb908eef64e2) (0f205c378983ac6a08469b9f400cbb908eef64e2)
* [Updates to Actor events based on community feedback for NV22 (#1531)](https://github.com/filecoin-project/builtin-actors/commit/2c7332805b1fb1170895573f7a55e89d6c043a47) (2c7332805b1fb1170895573f7a55e89d6c043a47)
The events assertion in integration tests have become optional since then so these commits didn't quite cleanly apply.
> cherry-pick late release/v13 commits onto master

- actors/miner/src/lib.rs
- actors/miner/src/types.rs
- actors/power/src/ext.rs
Removed in https://github.com/filecoin-project/builtin-actors/pull/1540 but I believe it's still needed to activate preseals; unless there's an alternative route to this?
Ref: https://github.com/filecoin-project/lotus/blob/b73d4e0481517b395a0e9aa9af5dab8bedc18285/chain/gen/genesis/miners.go#L494-L509
Tests for this were tangled up in the prove commit + cron stuff that was removed, this probably needs new tests if it's going back, but I'm not sure yet what that would entail.
> fix: restore ConfirmSectorProofsValid

- integration_tests/src/tests/prove_commit_niporep_test.rs
- test_vm/tests/suite/prove_commit_niporep_test.rs
The main thing we are looking at here is that the very first proving period after niporep onboarding matters. We can specify which deadline the sector has, we should be required to prove the sector the first time that deadline comes up.
1. Onboard one niporep sector
2. Move past the first proving deadline (that we specified) and fail to submit window post, check
3. Recover sector
4. Move to the next proving deadline and window post
5. Move to next deadline and check sector is active
6. Move to the next proving deadline and window post, then check we have 1 optimistic submission
> test(niporep): integration test for failing first wdpost

- actors/miner/src/lib.rs
> fix: remove Option around SectorPreCommitInfoInner.unsealed_cid

- actors/miner/src/lib.rs
- actors/miner/src/policy.rs
- actors/miner/tests/aggregate_prove_commit.rs
- actors/miner/tests/policy_test.rs
- actors/miner/tests/util.rs
Ref: https://github.com/filecoin-project/builtin-actors/issues/1573
As outlined in #1573, as long as `QUALITY_BASE_MULTIPLIER` == `DEAL_WEIGHT_MULTIPLIER` then we factor out `deal_space` in QAP calculations. It appears to me from the [language of the spec](https://spec.filecoin.io/#section-systems.filecoin_mining.sector.sector-quality) that it was imagined that the "DealWeightMultiplier (DWM)" was something that could be tuned but unless anyone imagines a world where we tinker with anything other than the "VerifiedDealWeightMultiplier (VDWM)" then we should just do away with deal_weight entirely in the calculations to avoid confusion and overhead.
In terms of what this does to `quality_for_weight`, here's what I see in that code as it is currently. Where `WSS` is …
> fix(miner)!: remove DEAL_WEIGHT_MULTIPLIER and its input to QAP calc

- Cargo.lock
- actors/miner/Cargo.toml
- actors/verifreg/Cargo.toml
- runtime/Cargo.toml
- runtime/tests/types_test.rs
Matches tests in https://github.com/filecoin-project/go-state-types/pull/286
> chore(miner): add BatchReturn serialization tests

- actors/evm/src/interpreter/precompiles/fvm.rs
- actors/evm/src/interpreter/precompiles/mod.rs
- actors/evm/tests/precompile.rs
- actors/evm/tests/util.rs
- runtime/src/runtime/fvm.rs
- runtime/src/runtime/mod.rs
- runtime/src/test_utils.rs
- test_vm/src/messaging.rs
Adds a runtime method for fetching drand beacon randomness without necessarily mixing in additional entropy. Expose beacon randomness through new EVM precompile.
There is some redundancy in the runtime methods here. The mixing of entropy could be factored out of the existing runtime beacon randomness method and into a wrapper function. I have code for this, but it has moderate impact on existing tests, which check randomness values assuming this mixing happened inside the runtime layer.
This is an alternative to #1576.
> Expose beacon randomness through new EVM precompile via new runtime method (FIP-0095)

- .github/workflows/release-check.yml
This is a change similar to the one we discovered we had to introduce in filecoin-ffi.
> ci: fix the github release url for uploading assets

- actors/evm/src/interpreter/execution.rs
- actors/evm/src/interpreter/instructions/memory.rs
- actors/evm/src/interpreter/instructions/mod.rs
Closes issue https://github.com/filecoin-project/builtin-actors/issues/1457
Adds MCOPY opcode to EVM actor in order to be in compliance with https://eips.ethereum.org/EIPS/eip-5656
> feat(evm): add MCOPY opcode

- Cargo.lock
- actors/market/src/ext.rs
- actors/market/src/lib.rs
- actors/power/Cargo.toml
- actors/power/tests/types_test.rs
Plus a minor naming fix I noticed while looking over #1557. The market actor copy of `CurrentTotalPowerReturn` is named `CurrentTotalPowerReturnParams`.
This is on top of #1557, and I'll wait till that's merged before marking this ready for review.
> chore(power): add CurrentTotalPowerReturn serialization tests

- Cargo.lock
- Cargo.toml
Creating a builtin v15.0.0-rc1 release, following the process here: https://github.com/filecoin-project/builtin-actors/blob/master/RELEASE.md
> chore: release 15.0.0-rc1

- actors/market/src/lib.rs
- actors/market/src/state.rs
Fixes #1498  
Changes made:
1. Caching proposals and states before iterating through deals.
2. Helper functions to query deal proposal and deal state from cached data.
> fix(market): load proposals and states roots once in on_miner_sectors_terminate

- runtime/src/util/map.rs
Now that we have external iterators, we don't need this error smuggling.
> refactor: avoid tricky error downcasting in the Map

- actors/evm/src/interpreter/instructions/control.rs
- actors/evm/src/interpreter/instructions/lifecycle.rs
- actors/evm/src/interpreter/instructions/mod.rs
- actors/evm/src/interpreter/output.rs
- actors/evm/src/lib.rs
This makes it possible to tell on which instruction the contract reverted where as previously the message wasn't all that useful. The runtime cost should be negligible.
> Include the program counter in contract-reverted messages

- Cargo.lock
- Cargo.toml
Publish a v16.0.0-dev1 release, so that we can start testing of https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0097.md.
> chore: release 16.0.0-dev1

- .github/workflows/coverage.yml
v3 is no longer supported as per https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> chore: update upload-artifact action to v4

- Cargo.lock
- actors/miner/src/deadline_state.rs
- actors/miner/src/expiration_queue.rs
- actors/miner/src/lib.rs
- actors/miner/src/types.rs
- actors/miner/tests/types_test.rs
PR against feature branch `feat/fip-0100` so we can review incrementally.
Closes: https://github.com/filecoin-project/builtin-actors/issues/1613
Closes: https://github.com/filecoin-project/builtin-actors/issues/1614
Closes: https://github.com/filecoin-project/builtin-actors/issues/1615
Just type changes and tests for their serialization forms so far.
* `Deadline`
- Add `total_power: PowerPair`
- Add `daily_fee: TokenAmount`
* `SectorOnChainInfo`
- Add `daily_fee: TokenAmount` as an optional field
- Tests that it can load both 15 and 16 field forms but always saves 16 field form
* `ExpirationSet`
- Add `fee_deduction: TokenAmount` as an optional field
- Tests that it can load both 5 and 6 field forms but always save 6 field form
> fip-0100: type changes and tests

- actors/miner/src/policy.rs
- actors/miner/tests/policy_test.rs
- runtime/src/runtime/policy.rs
Stacking a PR here so it's mainly asking for a sanity-check review and checking if anything's out of place or I'm not following convention.
Stacked on #1620 for the `feat/fip-0100` branch.
Closes: https://github.com/filecoin-project/builtin-actors/issues/1612
* Adds a `daily_proof_fee(policy: &Policy, circulating_supply: TokenAmount)` for the miner actor
* Adds `DAILY_FEE_CIRCULATING_SUPPLY_MULTIPLIER_NUM` and `DAILY_FEE_CIRCULATING_SUPPLY_MULTIPLIER_DENOM` for a 7.4e-15 multiplier as per the FIP: https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0100.md#per-sector-fee-added
Added a test to sanity check, it also ~matches what was given as a current-day estimate [here](https://github.com/filecoin-project/FIPs/discussions/1105#discussioncomment-12148441).
> fip-0100: add daily_proof_fee() and fee constants

- actors/miner/src/deadline_state.rs
- actors/miner/src/expiration_queue.rs
- actors/miner/src/expiration_queue/tests.rs
- actors/miner/src/lib.rs
- actors/miner/src/partition_state.rs
- actors/miner/src/testing.rs
- actors/miner/tests/deadline_state_test.rs
- actors/miner/tests/expiration_queue.rs
- actors/miner/tests/miner_actor_test_partitions.rs
- actors/miner/tests/record_skipped_faults.rs
- actors/miner/tests/types_test.rs
- actors/miner/tests/util.rs
Draft. Doesn't even pass all the existing tests yet, but I wanted to try and bang this out to at least get started to see what it might look like. I need to put a bit more thought into precisely where we're handling it and what we're doing.
> fip-0100: initial pass at daily_fee accounting

- Cargo.lock
- Cargo.toml
- actors/miner/Cargo.toml
- actors/miner/tests/types_test.rs
- actors/power/Cargo.toml
- actors/power/tests/types_test.rs
- actors/verifreg/Cargo.toml
- actors/verifreg/tests/verifreg_actor_test.rs
- runtime/Cargo.toml
- runtime/tests/types_test.rs
I was responsible for adding this in the first place but I've since noticed there are already 2 hex libraries in the dependencies list and a macro is fine for this use.
> chore(deps): remove const-hex dependency

- actors/miner/src/deadline_state.rs
- actors/miner/src/lib.rs
- actors/miner/src/partition_state.rs
- actors/miner/src/sectors.rs
- actors/miner/src/state.rs
- actors/miner/tests/deadline_state_test.rs
- actors/miner/tests/sectors.rs
- actors/miner/tests/sectors_stores_test.rs
- actors/miner/tests/state_harness.rs
Redoing #1625, same content, single commit
* fip-0100: move compact_partitions logic into deadline
* fip-0100: remove sectors in AMT not state
* fip-0100: Deadline::add_sectors flag to optionally accumulate fees
> fip-0100: move compact_partitions logic into deadline

- actors/miner/src/lib.rs
If we snap/extend across multiple deadlines (which appears to be untested), we would have summed up the power from all proceeding deadlines.
> fip-0100: fix power accounting on snap/extend

- actors/miner/src/lib.rs
- actors/miner/tests/extend_sector_expiration_test.rs
When, on extension, we encounter a legacy sector with a zero fee, update it based on the current circulating supply.
fixes #1634
> fip-0100: update the daily sector fee on extension when zero

- actors/miner/src/lib.rs
- actors/miner/src/policy.rs
- actors/miner/src/state.rs
- actors/miner/src/types.rs
- actors/miner/tests/daily_fees_test.rs
- actors/miner/tests/util.rs
- runtime/src/runtime/policy.rs
This applies the BR cap, adds a constant for the 50% and adds some testing to make sure it's properly applied across various states:
* Single vs multiple sectors
* BR cap happens on first cron vs normal cron with BR cap later
* Miss PoST and see that we still have the same power-based cap
* Recover fault, same payment
* For multiple sectors: terminate a sector and verify that the BR cap is proportional to remaining power
* Reset the network reward and watch the fee payment go back to uncapped
This doesn't go near the new QAP multiplier for FIP-0100, I wanted to get these pieces pushed so I can deal with that separately.
> fip-0100: 50%24hBR cap on payable daily_fee

- actors/miner/src/lib.rs
- actors/miner/src/state.rs
- actors/miner/src/testing.rs
- actors/miner/src/vesting_state.rs
- actors/miner/tests/apply_rewards.rs
- actors/miner/tests/deadline_cron.rs
- actors/miner/tests/repay_debt_test.rs
- actors/miner/tests/state_harness.rs
- actors/miner/tests/util.rs
- actors/miner/tests/vesting_unvested_funds.rs
This lets us efficiently take fees from vesting funds without loading/storing this object each time. It also lets us check if there are funds to vest without having to load any additional state, because the "next" batch of vesting funds are always stored in the root state object.
If FIP-0100 passes, we'll likely want this change as we'll otherwise read/write the vesting funds queue on every deadline for every miner.
fixes #1594
> feat: refactor vesting funds into a head and a tail

- .github/workflows/ci.yml
- .github/workflows/deny.yml
- Makefile
The latest version of rustup doesn't install the toolchain automatically.
> build: ensure we have the correct toolchain installed

- actors/miner/src/lib.rs
- actors/miner/src/policy.rs
- actors/miner/tests/daily_fees_test.rs
- actors/miner/tests/extend_sector_expiration_test.rs
- actors/miner/tests/policy_test.rs
- actors/miner/tests/prove_replica_failures_test.rs
- actors/miner/tests/prove_replica_test.rs
- actors/miner/tests/util.rs
- integration_tests/src/tests/prove_commit3_test.rs
- integration_tests/src/tests/prove_commit_niporep_test.rs
- runtime/Cargo.toml
- runtime/src/runtime/policy.rs
- test_vm/src/lib.rs
7.4e-15 per 32GiB QAP -> 2.1536e-25 per byte QAP
Closes: https://github.com/filecoin-project/builtin-actors/issues/1637
~_(Draft while I add tests that properly cover this—existing tests that care about fees are all 32GiB QAP)_~
> fip-0100: QAP multiplier for daily_fee

- actors/miner/src/lib.rs
- actors/miner/tests/miner_actor_test_precommit_batch.rs
- integration_tests/src/tests/batch_onboarding.rs
- integration_tests/src/tests/batch_onboarding_deals_test.rs
- integration_tests/src/tests/commit_post_test.rs
- integration_tests/src/tests/prove_commit3_test.rs
- integration_tests/src/tests/replica_update3_test.rs
- integration_tests/src/tests/replica_update_test.rs
- integration_tests/src/util/workflows.rs
- runtime/src/runtime/policy.rs
- test_vm/tests/suite/replica_update_test.rs
> chore: remove PRE_COMMIT_SECTOR_BATCH_MAX_SIZE and other gas-limited parameters

- actors/miner/src/expiration_queue.rs
- actors/miner/src/lib.rs
- actors/miner/src/policy.rs
- actors/miner/tests/daily_fees_test.rs
- actors/miner/tests/extend_sector_expiration_test.rs
- actors/miner/tests/policy_test.rs
- integration_tests/src/tests/prove_commit3_test.rs
- runtime/src/runtime/policy.rs
- runtime/src/test_utils.rs
Ref: https://github.com/filecoin-project/FIPs/discussions/1105#discussioncomment-12471015
* Reduce daily_fee to 5.56e-15 / 32GiB, we use a per-byte rounded multiplier of 1.61817e-25, which is a bit more precise than the previous per-byte rounded multiplier, we use `161817 / 1_000_000_000_000_000_000_000_000_000_000` (161817e-30).
* Add grace period for extensions of legacy sectors using a network-version mechanism. As long as the network version is less than 26 then we don't put a `daily_fee` on sectors that don't have one during extensions.
> fip-0100: proposed adjustments from feedback round

- .github/workflows/release-check.yml
- .github/workflows/releaser.yml
- .github/workflows/upload-release-assets.yml
- RELEASE.md
Resolves https://github.com/filecoin-project/builtin-actors/issues/1656
In this PR I extracted the release upload action to a separate workflow that can be triggered either manually or from other workflows. After this PR is merged, the release flow will be as follows:
1. I create a release PR.
2. CI creates a draft release.
3. ~~Release assets are uploaded to the draft release.~~
4. I merge the release PR.
5. CI ensures the draft release exists.
6. CI uploads release assets to the draft release.
7. CI publishes the draft release.
If this sounds reasonable to you, I'm going to proceed with the tests of this flow in a fork of this repository.
> ci: upload release again before the release is published

- actors/miner/src/deadline_state.rs
- actors/miner/src/lib.rs
~Ongoing discussion: if the fee is a proof fee, that is you're paying per window post, then should you pay for every deadline you're posting _including_ the last one.~
~Currently we pop expired sectors and deduct the fees from those before we figure out how much to pay.~
/cc @irenegia
> chore(docs): add minor clarifying docs on FIP-0100 power & fee use

- actors/datacap/src/lib.rs
- actors/evm/shared/src/uints.rs
- actors/evm/src/interpreter/memory.rs
- actors/evm/src/interpreter/system.rs
- actors/evm/src/lib.rs
- integration_tests/src/tests/batch_onboarding_deals_test.rs
- rust-toolchain.toml
- test_vm/src/messaging.rs
- vm_api/src/util/blockstore.rs
In theory, this enables the WASM multiple return values proposal. But my testing with the FVM indicates that everything "just works".
We've explicitly disabled this our compiler settings but... I haven't observed those options making a difference.
My plan is to merge this because everything does appear to be working correctly and we're not making any progress by sitting around holding our breaths.
fixes #1650
> chore: update to rust 1.86.0

- Cargo.lock
- Cargo.toml
- actors/evm/src/interpreter/precompiles/evm.rs
- integration_tests/Cargo.toml
- runtime/Cargo.toml
- runtime/src/test_utils.rs
The former is deprecated in favor of the latter.
> feat: switch from libsecp256k1 to k256

- Cargo.lock
- Cargo.toml
- integration_tests/Cargo.toml
- integration_tests/macro/Cargo.toml
Mostly patch/minor versions, but this has a few major updates:
- hex-literal (very safe)
- thiserror (probably safe)
- rlp (msrv bump)
- ctor (test only)
> chore: update remaining deps

- actors/evm/src/interpreter/instructions/call.rs
- actors/evm/src/interpreter/precompiles/evm.rs
- actors/evm/src/interpreter/precompiles/fvm.rs
- actors/evm/src/interpreter/precompiles/mod.rs
- actors/evm/src/interpreter/system.rs
- actors/evm/tests/call.rs
- actors/evm/tests/precompile.rs
- actors/evm/tests/util.rs
Previously, we'd query the remaining gas for every precompile call. Now, we only query the remaining gas when actually making a real call (i.e., only in the "native call" precompile.
Unfortunately, we make a syscall to query gas because we don't yet have a way to directly access this information from wasm. Ideally we'd implement https://github.com/filecoin-project/FIPs/discussions/845 and avoid this issue entirely, but that's a much larger project.
This should save ~14k gas per pre-compile call, which isn't nothing.
> feat(evm): save a syscall for most precompile calls

- .github/workflows/ci.yml
There have been a couple of critical updates to install-action since the last pinned version which should fix the CI issues with nextest.
> chore(ci): update install-action to address nextest errors

- .github/workflows/coverage.yml
- codecov.yml
This PR adds:
- Runs `coverage` on every PR
- Adds `codecov.yml` for customising the test coverage generation
> chore(coverage): allow code coverage to run of pull request

- actors/multisig/src/lib.rs
- integration_tests/src/tests/multisig_test.rs
- test_vm/tests/suite/multisig_test.rs
For the past 5 years we've put up with the builtin multisig having re-entrant approvals.  We haven't revisitied this since the launch of fvm but when composed with a smart contract the unexpected nature of this behavior could be used as a primitive in an attack relying on trust or social engineering.  Let's close up this security hole now.
The new test produces stack overflow on test_vm when applied to master without the fix since it is not as clever as ref fvm.  With the fix the test passes demonstrating that the issue is gone for good.
> Remove reentrant approval -- checks effects interactions
